### PR TITLE
[backend] nil filter operators for empty strings and dates (#6517)

### LINKED ISSUE #6517: "is not empty" operator does not work on CPE attribute
## Description

Filtering Softwares with "cpe is not empty" list Software with empty CPE.

### PR DESCRIPTION
**Pull request by Archidoit**
- backend: nil and not_nil operators now handles empty string and empty dates
- frontend: nil and not_nil operators now available for dates filters (exemple: last_seen for malwares, publication date for reports, etc)

issue: https://github.com/OpenCTI-Platform/opencti/issues/6517

### CODE REVIEW

File: opencti-platform/opencti-graphql/src/database/engine.js [hunk 1]
```diff
@@ -1682,15 +1682,20 @@ const buildLocalMustFilter = async (validFilter) => {
...
   const noValuesFiltering = [];
   const { key, values, nested, operator = 'eq', mode: localFilterMode = 'or' } = validFilter;
+  if (isEmptyField(key)) {
+    throw FunctionalError('A filter key must be defined', { key });
+  }
   const arrayKeys = Array.isArray(key) ? key : [key];
+  const headKey = R.head(arrayKeys);
+  const dontHandleMultipleKeys = nested || operator === 'nil' || operator === 'not_nil';
+  if (dontHandleMultipleKeys && arrayKeys.length > 1) {
+    throw UnsupportedError('Filter must have only one field', { keys: arrayKeys });
```
Comment (labo-flg) [inline opencti-platform/opencti-graphql/src/database/engine.js]:
```suggestion
    throw UnsupportedError('Filter must have only one field', { keys: arrayKeys, operator });
```
This way we know if its because of the operator or nested

File: opencti-platform/opencti-graphql/tests/02-integration/01-database/filterGroup-test.js [hunk 2]
```diff
@@ -703,6 +704,52 @@ describe('Complex filters combinations for elastic queries', () => {
     expect(queryResult.data.reports.edges.length).toEqual(4);
     expect(queryResult.data.reports.edges.map((n) => n.node.name).includes('Report3')).toBeFalsy();
   });
+  it('should list entities according to filters: \'nil\' / \'not_nil\' operators on strings', async () => {
```
Comment (labo-flg) [inline opencti-platform/opencti-graphql/tests/02-integration/01-database/filterGroup-test.js:707]: could you also add tests for dates ?

**Comment by labo-flg** [comment]
tested locally ✅

**Review by labo-flg — CHANGES_REQUESTED** [review]
Missing some tests not_nil on dates too, and we're good :)

**Review by labo-flg — APPROVED** [review]
