### PR TITLE
[backend] Fix search in files query (#5129)

### LINKED ISSUE #5129: Double quote are not taken into account in the file text indexing search
## Description

When searching for a string with double quote, the search in texts from indexed files is done without the double quote

## Environment

2. OpenCTI version: 5.12.4 (testing)

## Reproducible Steps

- On testing platform, search "XL4 macros" (with double quotes)
- click one of the result in the file tab
- search the string "XL4 macros" directly in the pdf
- no result (the matching string is "macros")

## Expected Output

No results in the file tab, as no files contains the complete string "XL4 macros"

## Actual Output

2 results

### PR DESCRIPTION
**Pull request by SouadHadjiat**
### Proposed changes

* use query_string which handles natively double quote queries

### Related issues

* https://github.com/OpenCTI-Platform/opencti/issues/5129

### Checklist

- [x] I consider the submitted work as finished
- [x] I tested the code for its functionality
- [ ] I wrote test cases for the relevant uses case
- [ ] I added/update the relevant documentation (either on github or on notion)
- [ ] Where necessary I refactored code to improve the overall quality

### CODE REVIEW

File: opencti-platform/opencti-graphql/src/database/file-search.js [hunk 1]
```diff
@@ -132,16 +132,26 @@ const buildFilesSearchResult = (data, first, searchAfter, connectionFormat = tru
...
+  return decodedSearch;
+};
 const elBuildSearchFilesQueryBody = async (context, user, options = {}) => {
   const { search = null, fileIds = [], entityIds = [] } = options; // search options
   const { includeAuthorities = false } = options;
   const dataRestrictions = await buildDataRestrictions(context, user, { includeAuthorities });
   const must = [...dataRestrictions.must];
   const mustNot = [...dataRestrictions.must_not];
   if (search) {
+    const decodedSearch = decodeSearch(search);
```
Comment (richard-julien) [inline opencti-platform/opencti-graphql/src/database/file-search.js:151]: I think specialElasticCharsEscape should be used

**Review by labo-flg — APPROVED** [review]

**Comment by labo-flg** [comment]
From an elastic newby perspective it seems ok to me.
Which is not much I reckon.

File: opencti-platform/opencti-graphql/src/database/file-search.js (hunk 1 above)
Comment (SouadHadjiat) [reply opencti-platform/opencti-graphql/src/database/file-search.js:151]: why do we need `specialElasticCharsEscape` ?

Comment (richard-julien) [reply opencti-platform/opencti-graphql/src/database/file-search.js:151]: To prevent query to crash because user is not aware of elasticsearch query syntax

Comment (SouadHadjiat) [reply opencti-platform/opencti-graphql/src/database/file-search.js:151]: Then we can use `simple_query_string` which will work with special characters even with syntax errors : 
https://www.elastic.co/guide/en/elasticsearch/reference/current/query-dsl-simple-query-string-query.html
https://opensearch.org/docs/latest/query-dsl/full-text/simple-query-string/

Comment (richard-julien) [reply opencti-platform/opencti-graphql/src/database/file-search.js:151]: Should done the trick. Dont hesitate to try some weird search phrase to see the behavior

Comment (SouadHadjiat) [reply opencti-platform/opencti-graphql/src/database/file-search.js:151]: yes I tried already and there is no error
