### PR TITLE
[backend] launch container sharing task with system user instead of context user (#11570)

### LINKED ISSUE #11570: Propagating container orga sharing to elements added in container is done with context user instead of internal user
## Description

Because createContainerSharingTask is done with context user instead of an internal bypass user, createContainerSharingTask can fail if the context user doesn't have the proper capabilities and/or organizations

## Environment

1. OS (where OpenCTI server runs): { e.g. Mac OS 10, Windows 10, Ubuntu 16.4, etc. }
2. OpenCTI version: { e.g. OpenCTI 1.0.2 }
3. OpenCTI client: { e.g. frontend or python }
4. Other environment details:

## Reproducible Steps

Steps to create the smallest reproducible scenario:
1. { e.g. Run ... }
2. { e.g. Click ... }
3. { e.g. Error ... }

### PR DESCRIPTION
**Pull request by JeremyCloarec**
### Proposed changes

* launch container sharing task with system user instead of context user
*

### Related issues

* #11570 
*

### Checklist

- [ ] I consider the submitted work as finished
- [ ] I tested the code for its functionality
- [ ] I wrote test cases for the relevant uses case (coverage and e2e)
- [ ] I added/update the relevant documentation (either on github or on notion)
- [ ] Where necessary I refactored code to improve the overall quality

### CODE REVIEW

File: opencti-platform/opencti-graphql/src/database/middleware.js [hunk 1]
```diff
@@ -960,7 +960,7 @@ const createContainerSharingTask = (context, type, element, relations = []) => {
   if (targetGrantIds.length > 0) {
     const sharingDescription = `${type} organizations of ${element.name} to contained objects`;
     const input = { ids: targetGrantIds, scope: 'KNOWLEDGE', actions: [{ type, context: { values: elementGrants } }], description: sharingDescription };
-    taskPromise = createListTask(context, context.user, input);
+    taskPromise = createListTask(context, SYSTEM_USER, input);
```
Comment (aHenryJard) [inline opencti-platform/opencti-graphql/src/database/middleware.js]: Could you please create a new AuthUser dedicated to this in https://github.com/OpenCTI-Platform/opencti/blob/master/opencti-platform/opencti-graphql/src/utils/access.ts

Comment (JeremyCloarec) [reply opencti-platform/opencti-graphql/src/database/middleware.js]: Are you sure we want a dedicated internal user for this? We usually use the `SYSTEM_USER` in these kind of cases of data consistency (we use it in mergeEntitiesRaw for deleting old relations, in loadElementsWithDependencies to clean up invalid relations etc..)

**Review by aHenryJard — APPROVED** [review]
All good.
