### PR TITLE
[frontend] Fix toggle shift and Loader (#5405)

### LINKED ISSUE #7591: The new loader should not be used at it is not ready
## Description

The new loader should not be used at it is not ready

### PR DESCRIPTION
**Pull request by Kedae**
Solve issues and closes #7591

### CODE REVIEW

File: opencti-platform/opencti-front/src/components/dataGrid/components/DataTableBody.tsx [hunk 1]
```diff
@@ -150,6 +152,43 @@ const DataTableBody = ({
...
+      let firstIndex = R.findIndex(
+        (n: { id: string }) => n.id === R.head(R.values(selectedElements))?.id,
+        resolvedData,
+      );
+      if (currentIndex > firstIndex) {
+        let entities: { id: string }[] = [];
+        while (firstIndex <= currentIndex) {
+          entities = [...entities, resolvedData[firstIndex]];
+          // eslint-disable-next-line no-plusplus
+          firstIndex++;
```
Comment (labo-flg) [inline opencti-platform/opencti-front/src/components/dataGrid/components/DataTableBody.tsx]:
```suggestion
          firstIndex += 1;
```

File: opencti-platform/opencti-front/src/components/dataGrid/components/DataTableBody.tsx [hunk 2]
```diff
@@ -150,6 +152,43 @@ const DataTableBody = ({
...
+        const forcedRemove = R.values(selectedElements).filter(
+          (n) => !entities.map((o) => o.id).includes(n.id),
+        );
+        return onToggleEntity(entities, event, forcedRemove);
+      }
+      let entities: { id: string }[] = [];
+      while (firstIndex >= currentIndex) {
+        entities = [...entities, resolvedData[firstIndex]];
+        // eslint-disable-next-line no-plusplus
+        firstIndex--;
```
Comment (labo-flg) [inline opencti-platform/opencti-front/src/components/dataGrid/components/DataTableBody.tsx]:
```suggestion
        firstIndex -= 1;
```

**Review by labo-flg — APPROVED** [review]
Tested OK, minor comments, take it or leave it :)
