### PR TITLE
[frontend] Fix quick subcription button(#5963)

### LINKED ISSUE #5963: Quick subcription button is not working properly
## Description

1. Go to a threat actor
2. Click on the bell

=> The subscription is created but button is not turned to active. Re-clicking do nothing (where it should open a panel). You have to reload the full page.

### PR DESCRIPTION
**Pull request by CelineSebe**
### Proposed changes

* [frontend] Take out usePreloadedQuery function
* [frontend] Add useEffect to update existingInstanceTriggersEdges

### Related issues

* #5963 
*

### Checklist

- [ ] I consider the submitted work as finished
- [ ] I tested the code for its functionality
- [ ] I wrote test cases for the relevant uses case
- [ ] I added/update the relevant documentation (either on github or on notion)
- [ ] Where necessary I refactored code to improve the overall quality

### Further comments

If this is a relatively large or complex change, kick off the discussion by explaining why you chose the solution you did and what alternatives you considered, etc...

### CODE REVIEW

**Review by frapuks — APPROVED** [review]
it works

**Review by Kedae — CHANGES_REQUESTED** [review]
We need to check with @Archidoit what was the goal of the previous code

File: opencti-platform/opencti-front/src/private/components/common/stix_core_objects/StixCoreObjectQuickSubscriptionContent.tsx [hunk 1]
```diff
@@ -141,19 +137,7 @@ StixCoreObjectQuickSubscriptionContentProps
...
-      .then((data) => {
-        setExistingInstanceTriggersEdges(
-          (data as StixCoreObjectQuickSubscriptionContentPaginationQuery$data)
-            ?.triggersKnowledge?.edges ?? [],
-        );
-      });
-  };
-
   const handleOpen = () => {
-    searchInstanceTriggers();
```
Comment (Archidoit) [inline opencti-platform/opencti-front/src/private/components/common/stix_core_objects/StixCoreObjectQuickSubscriptionContent.tsx:156]: @Kedae  this was to update the instance triggers list in case the user had deleted/updated one of triggers via the quick subscription edition panel

Comment (Archidoit) [reply opencti-platform/opencti-front/src/private/components/common/stix_core_objects/StixCoreObjectQuickSubscriptionContent.tsx:156]: but seems to work without it now that the 'pagination keys' are the same as Céline told me , strange

**Review by Kedae — APPROVED** [review]

**Review by Kedae — CHANGES_REQUESTED** [review]
I read wrong Cathia's message, we need to discuss it

**Review by Kedae — APPROVED** [review]
