### PR TITLE
[frontend/backend] Fix the separator in CSV feed's header(#6658)

### LINKED ISSUE #6658: Headers in CSV feeds are not respecting the separator
## Description

1. Create a CSV feed with a separator ";"
2. Enable headers

=> Headers are separated with "," instead of the given separator.

##Step to reproduce
1. go to [https://testing.octi.staging.filigran.io/dashboard/data/sharing/feeds?orderAsc=true&searchTerm=&sortBy=name](https://testing.octi.staging.filigran.io/dashboard/data/sharing/feeds?orderAsc=true&searchTerm=&sortBy=name)
2. CLick on "Test 6658" 

image

### PR DESCRIPTION
**Pull request by CelineSebe**
### Proposed changes

* modify the "join"
* improve the column display of CSV feeds
* turn feedbackCreation into a tsx function component

### Related issues

* #6658 

### Checklist

- [ ] I consider the submitted work as finished
- [ ] I tested the code for its functionality
- [ ] I wrote test cases for the relevant uses case (coverage and e2e)
- [ ] I added/update the relevant documentation (either on github or on notion)
- [ ] Where necessary I refactored code to improve the overall quality

### CODE REVIEW

File: opencti-platform/opencti-front/src/private/components/data/feeds/FeedCreation.jsx [hunk 1]
```diff
@@ -168,6 +168,7 @@ const sharedUpdater = (store, userId, paginationOptions, newEdge) => {
 
 const FeedCreation = (props) => {
   const { t, classes } = props;
+  const { t_i18n } = useFormatter();
```
Comment (labo-flg) [inline opencti-platform/opencti-front/src/private/components/data/feeds/FeedCreation.jsx:151]: if you are using `t_i18n` from `useFormatter` instead of `props.t`, you need to complete this refactor.

`compose(inject18n` (which was injecting the `t` prop) is no longer useful when using the hook `useFormatter`. And all mention to the `t` prop shall be removed.

**Review by labo-flg — CHANGES_REQUESTED** [review]
All tested ok, only some comments about the refactoring

File: opencti-platform/opencti-front/src/private/components/data/feeds/FeedCreation.jsx (hunk 1 above)
Comment (CelineSebe) [reply opencti-platform/opencti-front/src/private/components/data/feeds/FeedCreation.jsx:151]: Done.. Thanks :)

File: opencti-platform/opencti-front/src/private/components/data/feeds/FeedCreation.jsx [hunk 2]
```diff
@@ -671,12 +636,6 @@ const FeedCreation = (props) => {
...
-  classes: PropTypes.object,
-  theme: PropTypes.object,
-  t: PropTypes.func,
 };
 
-export default R.compose(
-  inject18n,
-  withStyles(styles, { withTheme: true }),
-)(FeedCreation);
+export default FeedCreation;
```
Comment (labo-flg) [inline opencti-platform/opencti-front/src/private/components/data/feeds/FeedCreation.jsx:635]: @CelineSebe I pushed a little commit to get rid of withStyle also while we're at it 🙂

**Review by labo-flg — APPROVED** [review]
