### PR TITLE
[backend] handle exception thrown from getSession in sessionStore (#10987)

### LINKED ISSUE #10987: fix(redis): Redis client fails to reconnect after a Redis restart
## Description

Redis has been restarted for maintenance reason, and after that the platform has never been able to connect to redis again. Redis was unavalaible for about 20 seconds.

Error logs started with lots of:
```
Error: All sentinels are unreachable. Retrying from scratch after 10ms.
    at connectToNext (/opt/opencti/build/back.js:822:8229)
    at SentinelConnector.connect (/opt/opencti/build/back.js:822:9451)
    at /opt/opencti/build/back.js:822:38972
    at new Promise (<anonymous>)
    at EventEmitter.connect (/opt/opencti/build/back.js:822:38534)
    at Timeout._onTimeout (/opt/opencti/build/back.js:822:32353)
    at listOnTimeout (node:internal/timers:588:17)
    at processTimers (node:internal/timers:523:7)
```
And
```
MaxRetriesPerRequestError: Reached the max retries per request limit (which is 20). Refer to "maxRetriesPerRequest" option for details.
    at Socket.<anonymous> (/opt/opencti/build/back.js:822:32698)
    at Object.onceWrapper (node:events:633:26)
    at Socket.emit (node:events:518:28)
    at TCP.<anonymous> (node:net:351:12)
```

And after a while the logs is full of:
```
Execution timeout, too many concurrent call on the same entities
```
with different participantId each time.

## Environment

1. OS (where OpenCTI server runs): { e.g. Mac OS 10, Windows 10, Ubuntu 16.4, etc. }
2. OpenCTI version: 6.6.10
3. OpenCTI client: { e.g. frontend or python }
4. Other environment details: Redis 7.4.2, Sentinel mode

## Reproducible Steps

Steps to create the smallest reproducible scenario:
1. { e.g. Run ... }
2. { e.g. Click ... }
3. { e.g. Error ... }

## Expected Output

The platform redis client connect back to redis when the Redis is back online.

## Actual Output

A platform restart has been required to solve the issue.

### PR DESCRIPTION
**Pull request by JeremyCloarec**
### Proposed changes

* some scenarios could cause the lock used in sessionStore-redis to never release: when the getSession failed, the exception wasn't handled properly, causing the lock to be kept indefinitely

### Related issues

* #10987
*

### Checklist

- [x] I consider the submitted work as finished
- [x] I tested the code for its functionality
- [ ] I wrote test cases for the relevant uses case (coverage and e2e)
- [ ] I added/update the relevant documentation (either on github or on notion)
- [ ] Where necessary I refactored code to improve the overall quality

### CODE REVIEW

File: opencti-platform/opencti-graphql/src/database/redis.ts [hunk 1]
```diff
@@ -123,6 +123,14 @@ const sentinelOptions = async (clusterNodes: Partial<SentinelAddress>[]): Promis
...
     failoverDetector: conf.get('redis:sentinel_failover_detector') ?? false,
     updateSentinels: conf.get('redis:sentinel_update_sentinels') ?? true,
+    sentinelReconnectStrategy: (retryAttempts: number) => {
+      const sentinelMaxReconnect = conf.get('redis:sentinel_max_reconnects');
+      if (!!sentinelMaxReconnect && retryAttempts >= sentinelMaxReconnect) {
+        logApp.error('Shutting down: redis sentinel was not able to reconnect');
+        process.exit(1);
+      }
+      return 60000;
+    },
```
Comment (labo-flg) [inline opencti-platform/opencti-graphql/src/database/redis.ts]: is it still relevant ?
This concept of "fail fast" is nowhere else in the app yet, and it might be breaking change for some people, depending on how they manage their platform infra.
cc @richard-julien

Comment (JeremyCloarec) [reply opencti-platform/opencti-graphql/src/database/redis.ts]: removing for now since it is not a necessary change

**Review by labo-flg — APPROVED** [review]
