### PR TITLE
[frontend] Fix tooltip issue when adding a filter(#6036)

### LINKED ISSUE #6036: Filter tooltip placement bug when creating a widget
## Description

The tooltips appear outside of the widget creation box (above or below).

## Reproducible Steps

Steps to create the smallest reproducible scenario:
1- Go to a Dashboard > Create a widget 
2- Horizontal bar > Knowledge Bar
3- Add a filter
4- Click on filter to scroll through all options

## Actual Output

Bug tooltip arrow

https://github.com/OpenCTI-Platform/opencti/assets/87119259/7fc19edf-1f02-42c8-8956-a9b593ca1085

### PR DESCRIPTION
**Pull request by CelineSebe**
### Proposed changes

* followCursor props

### Related issues

* #6036 

### Checklist

- [ ] I consider the submitted work as finished
- [ ] I tested the code for its functionality
- [ ] I wrote test cases for the relevant uses case
- [ ] I added/update the relevant documentation (either on github or on notion)
- [ ] Where necessary I refactored code to improve the overall quality

### Further comments

If this is a relatively large or complex change, kick off the discussion by explaining why you chose the solution you did and what alternatives you considered, etc...

### CODE REVIEW

File: opencti-platform/opencti-front/src/components/filters/FilterChipPopover.tsx [hunk 1]
```diff
@@ -290,7 +290,7 @@ export const FilterChipPopover: FunctionComponent<FilterChipMenuProps> = ({
             ? filterValues.filter((fVal) => fVal && fVal.key === subKey && fVal.values.includes(option.value)).length > 0
             : filterValues.includes(option.value);
           return (
-            <Tooltip title={option.label} key={option.label}>
+            <Tooltip title={option.label} key={option.label} followCursor={true}>
```
Comment (jpkha) [inline opencti-platform/opencti-front/src/components/filters/FilterChipPopover.tsx]: You can write just "followCursor"

**Review by jpkha — APPROVED** [review]
