### PR TITLE
[backend] Fix organization admin user can't delete/edit user account status  (#8011)

### LINKED ISSUE #8011: When a user is administrator of an organization, he should be able to manage the users of this organization (enable / disable)
## Description

1. Promote a user as admin of an organization
2. Login as this user
3. Try to disable a user part of the organization

=> It should be possible, it is not.

### PR DESCRIPTION
**Pull request by marieflorescontact**
### Proposed changes
* Fix organization admin user can't delete/edit user
* backend tests
* Add refresh session if plateform organization is updated
* Ensure session is updated in the cache

### Related issues

* #8011
* #8101

### Checklist

- [x] I consider the submitted work as finished
- [x] I tested the code for its functionality
- [x] I wrote test cases for the relevant uses case (coverage and e2e)
- [ ] I added/update the relevant documentation (either on github or on notion)
- [x] Where necessary I refactored code to improve the overall quality

### CODE REVIEW

File: opencti-platform/opencti-graphql/tests/02-integration/02-resolvers/user-test.js [hunk 1]
```diff
@@ -684,3 +699,181 @@ describe('User has no capability query behavior', () => {
...
+        }
+      }
+    `;
+    const queryResult = await adminQuery({
+      query: UPDATE_QUERY,
+      variables: { id: testOrganizationId, input: { key: 'grantable_groups', value: [amberGroupId] } },
+    });
+    expect(queryResult.data.organizationFieldPatch.grantable_groups.length).toEqual(1);
+    expect(queryResult.data.organizationFieldPatch.grantable_groups[0]).toEqual({ id: amberGroupId });
+  }); */
```
Comment (lndrtrbn) [inline opencti-platform/opencti-graphql/tests/02-integration/02-resolvers/user-test.js]: Should be kept or removed?

File: opencti-platform/opencti-graphql/tests/02-integration/02-resolvers/user-test.js [hunk 2]
```diff
@@ -684,3 +699,181 @@ describe('User has no capability query behavior', () => {
...
+  afterAll(async () => {
+    it('should remove the capability to administrate the Organization', async () => {
```
Comment (lndrtrbn) [inline opencti-platform/opencti-graphql/tests/02-integration/02-resolvers/user-test.js]: Tests inside afterAll function? Thats seems odd

File: opencti-platform/opencti-graphql/src/database/session.js [hunk 3]
```diff
@@ -112,14 +112,23 @@ export const killUserSessions = async (userId) => {
...
 export const markSessionForRefresh = async (id) => {
+  const { store } = applicationSession;
   const currentSession = await getSession(id);
   if (currentSession) {
     const newSession = { ...currentSession, session_refresh: true };
-    await setSession(id, newSession, currentSession.expiration);
+    const sessId = id.includes(store.prefix) ? id.split(store.prefix)[1] : id;
+    store.set(sessId, newSession); // this will ensure the session is updated in the cache
+    // TODO check what to do with currentSession.expiration
+    // await setSession(id, newSession, currentSession.expiration);
```
Comment (lndrtrbn) [inline opencti-platform/opencti-graphql/src/database/session.js:122]: TODO ?

File: opencti-platform/opencti-graphql/tests/02-integration/02-resolvers/user-test.js (hunk 1 above)
Comment (marieflorescontact) [reply opencti-platform/opencti-graphql/tests/02-integration/02-resolvers/user-test.js]: oups. removed

File: opencti-platform/opencti-graphql/tests/02-integration/02-resolvers/user-test.js (hunk 2 above)
Comment (marieflorescontact) [reply opencti-platform/opencti-graphql/tests/02-integration/02-resolvers/user-test.js]: it's an essential clean up step, but it's still clean up, which is why I've put it in a beforeAll.
I had so many problems with these tests that I added assertions to make sure the steps were all done correctly...In your opinion, do I keep a beforeAll without “it” or do I keep the “it” that I move after the others?

Comment (lndrtrbn) [reply opencti-platform/opencti-graphql/tests/02-integration/02-resolvers/user-test.js]: I suppose you mean `afterAll` and not `beforeAll`. 
If it's clean up then you are not really testing stuff so keep `afterAll` but without any `it` or assertions in it. If it's indeed a test then it should be done outside the `afterAll` step

File: opencti-platform/opencti-graphql/src/domain/user.js [hunk 4]
```diff
@@ -898,7 +898,7 @@ export const userDelete = async (context, user, userId) => {
     // When user is organization admin, we make sure that the deleted user is in one of the administrated organizations of the admin
     const userData = await storeLoadById(context, user, userId, ENTITY_TYPE_USER);
     const myAdministratedOrganizationsIds = user.administrated_organizations.map(({ id }) => id);
-    if (!userData.objectOrganization.find((orga) => myAdministratedOrganizationsIds.includes(orga))) {
+    if (!userData['rel_granted.internal_id'].find((orga) => myAdministratedOrganizationsIds.includes(orga))) {
```
Comment (SouadHadjiat) [inline opencti-platform/opencti-graphql/src/domain/user.js]: should be `userData[RELATION_PARTICIPATE_TO]`

File: opencti-platform/opencti-graphql/src/database/session.js (hunk 3 above)
Comment (SouadHadjiat) [reply opencti-platform/opencti-graphql/src/database/session.js:122]: I wrote this because before we used to refresh the session without changing its TTL, but now that we call store.set, it will reset the TTL I guess. I didn't have time to investigate more, so I wrote the TODO to not forget about it.

Comment (lndrtrbn) [reply opencti-platform/opencti-graphql/src/database/session.js:122]: And it can be merge with it or should it be investigated before merging ?

Comment (marieflorescontact) [reply opencti-platform/opencti-graphql/src/database/session.js:122]: @SouadHadjiat

File: opencti-platform/opencti-graphql/src/utils/access.ts [hunk 5]
```diff
@@ -390,6 +390,10 @@ export const isUserHasCapabilities = (user: AuthUser, capabilities: string[] = [
   return capabilities.every((capability) => isUserHasCapability(user, capability));
 };
 
+export const isAdminWithoutSettingsSetAccessCapability = (user: AuthUser) => {
```
Comment (SouadHadjiat) [inline opencti-platform/opencti-graphql/src/utils/access.ts]: maybe rename to "isOnlyOrgaAdmin" ?

File: opencti-platform/opencti-graphql/src/modules/notification/notification-domain.ts [hunk 6]
```diff
@@ -232,7 +233,7 @@ export const triggerDelete = async (context: AuthContext, user: AuthUser, trigge
     throw ForbiddenAccess();
   }
   // If user is only organization admin, check if he has access on all targets
-  if (!isUserHasCapability(user, SETTINGS_SET_ACCESSES) && isUserHasCapability(user, VIRTUAL_ORGANIZATION_ADMIN)) {
+  if (!isAdminWithoutSettingsSetAccessCapability(user)) {
```
Comment (SouadHadjiat) [inline opencti-platform/opencti-graphql/src/modules/notification/notification-domain.ts]: should be `if (isAdminWithoutSettingsSetAccessCapability(user))`, without the `!`

File: opencti-platform/opencti-graphql/src/domain/user.js [hunk 7]
```diff
@@ -981,7 +982,7 @@ export const userIdDeleteRelation = async (context, user, userId, toId, relation
 };
 
 export const userDeleteOrganizationRelation = async (context, user, userId, toId) => {
-  if (!isUserHasCapability(user, SETTINGS_SET_ACCESSES) && isUserHasCapability(user, VIRTUAL_ORGANIZATION_ADMIN)) {
+  if (!isAdminWithoutSettingsSetAccessCapability(user)) {
```
Comment (SouadHadjiat) [inline opencti-platform/opencti-graphql/src/domain/user.js]: should be `if (isAdminWithoutSettingsSetAccessCapability(user))`, without the `!`

File: opencti-platform/opencti-graphql/src/domain/user.js [hunk 8]
```diff
@@ -930,7 +931,7 @@ export const userAddRelation = async (context, user, userId, input) => {
   }
   // Check in case organization admins adds non-grantable goup a user
   const myGrantableGroups = R.uniq(user.administrated_organizations.map((orga) => orga.grantable_groups).flat());
-  if (!isUserHasCapability(user, SETTINGS_SET_ACCESSES) && isUserHasCapability(user, VIRTUAL_ORGANIZATION_ADMIN)) {
+  if (!isAdminWithoutSettingsSetAccessCapability(user)) {
```
Comment (SouadHadjiat) [inline opencti-platform/opencti-graphql/src/domain/user.js]: should be `if (isAdminWithoutSettingsSetAccessCapability(user))`, without the `!`

File: opencti-platform/opencti-graphql/src/domain/user.js [hunk 9]
```diff
@@ -416,7 +417,7 @@ export const roleEditContext = async (context, user, roleId, input) => {
 };
 
 export const assignOrganizationToUser = async (context, user, userId, organizationId) => {
-  if (!isUserHasCapability(user, SETTINGS_SET_ACCESSES) && isUserHasCapability(user, VIRTUAL_ORGANIZATION_ADMIN)) {
+  if (!isAdminWithoutSettingsSetAccessCapability(user)) {
```
Comment (SouadHadjiat) [inline opencti-platform/opencti-graphql/src/domain/user.js]: should be `if (isAdminWithoutSettingsSetAccessCapability(user))`, without the `!`

File: opencti-platform/opencti-graphql/src/domain/user.js [hunk 10]
```diff
@@ -669,7 +670,7 @@ export const userEditField = async (context, user, userId, rawInputs) => {
   const userToUpdate = await internalLoadById(context, user, userId);
   // Check in an organization admin edits a user that's not in its administrated organizations
   const myAdministratedOrganizationsIds = user.administrated_organizations.map((orga) => orga.id);
-  if (!isUserHasCapability(user, SETTINGS_SET_ACCESSES) && isUserHasCapability(user, VIRTUAL_ORGANIZATION_ADMIN)) {
+  if (!isAdminWithoutSettingsSetAccessCapability(user)) {
```
Comment (SouadHadjiat) [inline opencti-platform/opencti-graphql/src/domain/user.js]: should be `if (isAdminWithoutSettingsSetAccessCapability(user))`, without the `!`

File: opencti-platform/opencti-graphql/src/domain/user.js [hunk 11]
```diff
@@ -894,11 +895,11 @@ export const deleteAllNotificationByUser = async (userId) => {
  * @returns {Promise<*>}
  */
 export const userDelete = async (context, user, userId) => {
-  if (!isUserHasCapability(user, SETTINGS_SET_ACCESSES) && isUserHasCapability(user, VIRTUAL_ORGANIZATION_ADMIN)) {
+  if (!isAdminWithoutSettingsSetAccessCapability(user)) {
```
Comment (SouadHadjiat) [inline opencti-platform/opencti-graphql/src/domain/user.js]: should be `if (isAdminWithoutSettingsSetAccessCapability(user))`, without the `!`

File: opencti-platform/opencti-graphql/src/modules/organization/organization-domain.ts [hunk 12]
```diff
@@ -47,14 +47,17 @@ export const editAuthorizedAuthorities = async (context: AuthContext, user: Auth
...
-  const members: BasicStoreEntity[] = await listAllFromEntitiesThroughRelations(context, user, organizationId, RELATION_PARTICIPATE_TO, ENTITY_TYPE_USER);
+  if (!organization) {
+    throw FunctionalError('Organization not found');
+  }
+  const members: BasicStoreEntity[] = await listAllFromEntitiesThroughRelations(context, user, organization.id, RELATION_PARTICIPATE_TO, ENTITY_TYPE_USER);
   const updatedUser = members.find(({ id }) => id === memberId);
   // Check if user is part of Orga. If not, throw exception
   if (!updatedUser) {
-    throw FunctionalError('User is not part of the organization');
+    throw FunctionalError('User is not part of the organization', { members, memberId });
```
Comment (SouadHadjiat) [inline opencti-platform/opencti-graphql/src/modules/organization/organization-domain.ts]: I don't think we should add { members, memberId } data here. maybe it was useful for testing

File: opencti-platform/opencti-graphql/src/database/session.js (hunk 3 above)
Comment (SouadHadjiat) [reply opencti-platform/opencti-graphql/src/database/session.js:122]: Yes I think we can merge it, I'll remove this TODO in my current PR on sessions

**Review by SouadHadjiat — APPROVED** [review]
