### PR TITLE
[backend] manage unknown exception in FileIndexManager (#5822)

### LINKED ISSUE #5822: File indexing blocked
## Description

File indexing has been blocked for several days/weeks. The counter is no longer progressing and remains stuck on my 1300th file.

## Environment

OCTI 5.12.26
OpenSearch (AWS cloud)

## Logs

`{"category":"APP","errors":[{"attributes":{"genre":"TECHNICAL","http_status":500},"message":"The specified key does not exist.","name":"UNKNOWN_ERROR","stack":"UNKNOWN_ERROR: The specified key does not exist.
    at error (/opt/opencti/build/src/config/errors.js:8:10)
    at UnknownError (/opt/opencti/build/src/config/errors.js:76:47)
    at Object._logWithError (/opt/opencti/build/src/config/conf.js:311:23)
    at Object.error (/opt/opencti/build/src/config/conf.js:321:48)
    at fileIndexHandler (/opt/opencti/build/src/manager/fileIndexManager.ts:159:18)
    at /opt/opencti/build/src/manager/fileIndexManager.ts:202:9
    at Tft.#runHandlerAndScheduleTimeout (/opt/opencti/build/node_modules/set-interval-async/dist/set-interval-async-timer.cjs:36:13)
    at Timeout._onTimeout (/opt/opencti/build/node_modules/set-interval-async/dist/set-interval-async-timer.cjs:29:13)"},{"message":"The specified key does not exist.","name":"NoSuchKey","stack":"NoSuchKey: The specified key does not exist.
    at de_NoSuchKeyRes (/opt/opencti/build/node_modules/@aws-sdk/client-s3/dist-cjs/protocols/Aws_restXml.js:5196:23)
    at de_GetObjectCommandError (/opt/opencti/build/node_modules/@aws-sdk/client-s3/dist-cjs/protocols/Aws_restXml.js:3440:25)
    at processTicksAndRejections (node:internal/process/task_queues:95:5)
    at /opt/opencti/build/node_modules/@smithy/middleware-serde/dist-cjs/index.js:35:20
    at /opt/opencti/build/node_modules/@aws-sdk/middleware-signing/dist-cjs/awsAuthMiddleware.js:30:20
    at /opt/opencti/build/node_modules/@smithy/middleware-retry/dist-cjs/index.js:320:38
    at /opt/opencti/build/node_modules/@aws-sdk/middleware-flexible-checksums/dist-cjs/flexibleChecksumsMiddleware.js:63:20
    at /opt/opencti/build/node_modules/@aws-sdk/middleware-sdk-s3/dist-cjs/region-redirect-endpoint-middleware.js:14:24
    at /opt/opencti/build/node_modules/@aws-sdk/middleware-sdk-s3/dist-cjs/region-redirect-middleware.js:9:20
    at /opt/opencti/build/node_modules/@aws-sdk/middleware-logger/dist-cjs/loggerMiddleware.js:7:26
    at getFileContent (/opt/opencti/build/src/database/file-storage.js:157:18)
    at loadFilesToIndex (/opt/opencti/build/src/manager/fileIndexManager.ts:53:19)"}],"level":"error","manager":"FILE_INDEX_MANAGER","message":"Platform unmanaged direct error","timestamp":"2024-02-05T00:23:12.995Z","version":"5.12.26"}`

### PR DESCRIPTION
**Pull request by aHenryJard**
### Proposed changes

* Hard to reproduce locally, so I have tested (issue and fix) with a unit test.

### Related issues

* https://github.com/OpenCTI-Platform/opencti/issues/5822

### Checklist

- [x] I consider the submitted work as finished
- [x] I tested the code for its functionality
- [x] I wrote test cases for the relevant uses case
- [ ] I added/update the relevant documentation (either on github or on notion)
- [ ] Where necessary I refactored code to improve the overall quality

### Further comments

If this is a relatively large or complex change, kick off the discussion by explaining why you chose the solution you did and what alternatives you considered, etc...

### CODE REVIEW

File: opencti-platform/opencti-graphql/src/manager/fileIndexManager.ts [hunk 1]
```diff
@@ -199,7 +207,7 @@ const initFileIndexManager = () => {
     start: async () => {
       logApp.info('[OPENCTI-MODULE] Starting file index manager');
       scheduler = setIntervalAsync(async () => {
-        await fileIndexHandler();
+        await fileIndexHandler(); // here
```
Comment (aHenryJard) [inline opencti-platform/opencti-graphql/src/manager/fileIndexManager.ts]:
```suggestion
        await fileIndexHandler();
```

**Review by marieflorescontact — APPROVED** [review]
So great to see a test with mocks!!!! 🔥🔥🔥
