### PR TITLE
[backend] prevent wrong type for empty pid (#6968)

### LINKED ISSUE #6968: Can't remove pid of a process
Create a process (it is a type of observable) with PID = 22 and command_line = 'command'.
Edit the process to remove the PID. An error occurs : 
image

Note: We should be able to remove the PID of a process since it is possible to create a process with no PID.

### PR DESCRIPTION
**Pull request by frapuks**
### Proposed changes

- Manage value of PID (type number) when removing the value (empty string is sending)

### Related issues

- close #6968 

### Checklist

- [x] I consider the submitted work as finished
- [x] I tested the code for its functionality
- [ ] I wrote test cases for the relevant uses case (coverage and e2e)
- [ ] I added/update the relevant documentation (either on github or on notion)
- [ ] Where necessary I refactored code to improve the overall quality

### CODE REVIEW

File: opencti-platform/opencti-graphql/src/domain/stixCyberObservable.js [hunk 1]
```diff
@@ -273,6 +273,7 @@ export const stixCyberObservableEditField = async (context, user, stixCyberObser
     input,
     opts
   );
+  if (isEmptyField(stixCyberObservable.pid)) stixCyberObservable.pid = undefined;
```
Comment (Archidoit) [inline opencti-platform/opencti-graphql/src/domain/stixCyberObservable.js]: are you sure there is no other solution than implemented this specific line for pid ? For instance 'dst_packets' (for Network traffic) is also of type 'number' and we can remove it without problem and without implemented a specific line like that...

**Comment by Archidoit** [comment]
Working but the code solution may not be the best...

**Comment by Archidoit** [comment]
Working well, code ok for me 👍

**Review by SarahBocognano — APPROVED** [review]

**Review by Archidoit — APPROVED** [review]
