### PR TITLE
[backend] Improve Attack Pattern knowledge matrix view performance (#6662)

### LINKED ISSUE #6662: Attack pattern knowledge matrix query perf issue
## Description

When viewing the attack patterns of an entity (in knowledge view), the query used to display this view can send a lot of requests to the database, leading in some cases to errors : 

```
"message":"Fail to execute engine pagination","name":"DATABASE_ERROR","stack":"DATABASE_ERROR: Fail to execute engine pagination\n    at error (/opt/opencti/build/src/config/errors.js:8:10)\n    at DatabaseError (/opt/opencti/build/src/config/errors.js:58:48)\n    at /opt/opencti/build/src/database/engine.js:2862:15\n    at processTicksAndRejections (node:internal/process/task_queues:95:5)\n    at listEntitiesThroughRelationsPaginated (/opt/opencti/build/src/database/middleware-loader.ts:477:28)"},{"message":"search_phase_execution_exception\n\tCaused by:\n\t\tes_rejected_execution_exception: rejected execution of TimedRunnable{original=org.elasticsearch.action.search.FetchSearchPhase$1@525f033, creationTimeNanos=5678643698163724, startTimeNanos=0, finishTimeNanos=-1, failedOrRejected=false} on TaskExecutionTimeTrackingEsThreadPoolExecutor[name = opencti-prod-1/search, queue capacity = 1000, task execution EWMA = 2.5ms, total task execution time = 9.8d, org.elasticsearch.common.util.concurrent.TaskExecutionTimeTrackingEsThreadPoolExecutor@3b8ce72[Running, pool size = 13, active threads = 13, queued tasks = 999, completed tasks = 521468374]]","name":"ResponseError","stack":"ResponseError: search_phase_execution_exception\n\tCaused by:\n\t\tes_rejected_execution_exception: rejected execution of TimedRunnable{original=org.elasticsearch.action.search.FetchSearchPhase$1@525f033, creationTimeNanos=5678643698163724, startTimeNanos=0, finishTimeNanos=-1, failedOrRejected=false} on TaskExecutionTimeTrackingEsThreadPoolExecutor[name = opencti-prod-1/search, queue capacity = 1000, task execution EWMA = 2.5ms, total task execution time = 9.8d, org.elasticsearch.common.util.concurrent.TaskExecutionTimeTrackingEsThreadPoolExecutor@3b8ce72[Running, pool size = 13, active threads = 13, queued tasks = 999, completed tasks = 521468374]]\n    at Bon.request (/opt/opencti/build/node_modules/@elastic/transport/src/Transport.ts:553:17)\n    at processTicksAndRejections (node:internal/process/task_queues:95:5)\n    at qrt.SearchApi [as search] (/opt/opencti/build/node_modules/@elastic/elasticsearch/src/api/api/search.ts:89:10)\n    at listEntitiesThroughRelationsPaginated (/opt/opencti/build/src/database/middleware-loader.ts:477:28)"}],"inner_relation_creation":0,"level":"error","message":"Fail to execute engine pagination","operation":"StixDomainObjectAttackPatternsKillChainStixCoreRelationshipsQuery","operation_query":"query StixDomainObjectAttackPatternsKillChainStixCoreRelationshipsQuery($fromOrToId:[String]$elementWithTargetTypes:[String]$first:Int$filters:FilterGroup){...StixDomainObjectAttackPatternsKillChain_data} ...
````

## Environment

1. OS (where OpenCTI server runs): { e.g. Mac OS 10, Windows 10, Ubuntu 16.4, etc. }
2. OpenCTI version: 6.0.9
3. OpenCTI client: frontend
4. Other environment details:

## Reproducible Steps

not reproduced.

## Additional information

Issue raised in the slack community

### PR DESCRIPTION
**Pull request by SouadHadjiat**
### Proposed changes

* optimize attackPatterns query (use aggregations for isSubAttackPattern), use batch loading for parentAttackPatterns and subAttackPatterns
* add pagination and filters for sub connections (coursesOfAction, parentAttackPatterns, subAttackPatterns), because we were only retrieving the first 20, without any way to retrieve more.
* create a dedicated and optimized query for attack pattern matrix view : attackPatternsMatrix
* TODO : code cleanup, renaming, frontend refactoring ?

### Related issues

* #6662 

### Checklist

- [x] I consider the submitted work as finished
- [x] I tested the code for its functionality
- [ ] I wrote test cases for the relevant uses case (coverage and e2e)
- [ ] I added/update the relevant documentation (either on github or on notion)
- [ ] Where necessary I refactored code to improve the overall quality

### Further comments

After first 2 commits, perf test with +2k attack patterns (exported from testing)
- on master: query takes 20s
Capture d'écran 2024-08-26 160150

- on branch: query takes 7s
image

- on branch - after replacing with attackPatternsMatrix query : query takes less than 1s
Capture d'écran 2024-08-28 114752

### CODE REVIEW

File: opencti-platform/opencti-graphql/src/database/engine.js [hunk 1]
```diff
@@ -2990,6 +2990,47 @@ export const elAggregationRelationsCount = async (context, user, indexName, opti
     });
 };
 
+export const elAggregationNestedTermsWithFilter = async (context, user, indexName, aggregation, opts = {}) => {
+  const { types = [], size = 500 } = opts;
```
Comment (aHenryJard) [inline opencti-platform/opencti-graphql/src/database/engine.js]: Could we use one size parameter for the default value here ? like default_pagination_result for example ?

File: opencti-platform/opencti-graphql/src/database/engine.js [hunk 2]
```diff
@@ -2990,6 +2990,47 @@ export const elAggregationRelationsCount = async (context, user, indexName, opti
...
+      return aggBucketsResult.map((b) => {
+        let label = b.key;
+        if (typeof label === 'number') {
+          label = String(b.key);
+        }
+        return { label, key: b.key, value: b.doc_count };
+      });
+    })
+    .catch((err) => {
+      throw DatabaseError('Aggregation computation count fail', { cause: err, query });
```
Comment (aHenryJard) [inline opencti-platform/opencti-graphql/src/database/engine.js:3030]: Maybe add context in metadata here, to know the source of query (manager vs ui)

File: opencti-platform/opencti-graphql/src/resolvers/attackPattern.js [hunk 3]
```diff
@@ -18,19 +19,25 @@ import {
...
+
+const batchLoadSubAttackPatterns = batchLoader(batchChildAttackPatternsPaginated);
+const batchLoadParentAttackPatterns = batchLoader(batchParentAttackPatternsPaginated);
+const batchLoadIsSubAttackPattern = batchLoader(batchIsSubAttackPattern);
 
 const attackPatternResolvers = {
   Query: {
     attackPattern: (_, { id }, context) => findById(context, context.user, id),
     attackPatterns: (_, args, context) => findAll(context, context.user, args),
+    attackPatternsMatrix: (_, __, context) => getAttackPatternsMatrix(context, context.user),
```
Comment (aHenryJard) [inline opencti-platform/opencti-graphql/src/resolvers/attackPattern.js:32]: Could you please cover this new API with a resolver test ? My first idea would be to add a call in https://github.com/OpenCTI-Platform/opencti/blob/master/opencti-platform/opencti-graphql/tests/02-integration/02-resolvers/attackPattern-test.js

**Review by aHenryJard — APPROVED** [review]
