### PR TITLE
[backend] fix playbook attributPathMapping for SCOs (#9226)

### LINKED ISSUE #9226: [Playbook] Label application on Observable doesn't work
## Description

Playbooks don't add labels if the **entity already contains one**. This effect seems to occur **only on Observable** objects.

## Environment

OCTI 6.4.2

## Reproducible Steps

Steps to create the smallest reproducible scenario:
1. Create two label "LabelA" and "LabelB"
2. Create an Observable Text and apply the LabelA on it
3. Create the following playbook
    - Listener on "update" event and "Entity type = Text"
    - Manipulate knowledge: Add -> Label -> LabelB
    - Send for ingestion
    - (start the playbook)

4. Go to the Observable Text and modify it (add a description for example)
5. Wait for the playbook to execute
-> No label added despite the correct execution of the playbook according to the execution traces

You can redo the same experiment without having a label on the observable at the beginning (so without adding "LabelA" at the start) -> you will see that it works

## Expected Output

I expect to have both labels, i.e. to have my old label LabelA, as well as my new label LabelB

## Actual Output

The new label is not added (the entity remains unchanged)

### PR DESCRIPTION
**Pull request by JeremyCloarec**
### Proposed changes

* labels and createdBy weren't set properly on SCOs in playbook update knowledge component

### Related issues

* #9226 

### Checklist

- [x] I consider the submitted work as finished
- [x] I tested the code for its functionality
- [ ] I wrote test cases for the relevant uses case (coverage and e2e)
- [ ] I added/update the relevant documentation (either on github or on notion)
- [ ] Where necessary I refactored code to improve the overall quality

### CODE REVIEW

**Comment by SarahBocognano** [comment]
We can link this one because the mapping in createdBy wasn't ok. Your PR fix it :
https://github.com/OpenCTI-Platform/opencti/issues/9065

File: opencti-platform/opencti-graphql/src/modules/playbook/playbook-components.ts [hunk 1]
```diff
@@ -566,13 +566,11 @@ const attributePathMapping: any = {
     [ABSTRACT_STIX_RELATIONSHIP]: `/${objectMarking.stixName}`,
   },
   [INPUT_LABELS]: {
-    [ABSTRACT_STIX_DOMAIN_OBJECT]: `/${objectLabel.stixName}`,
-    [ABSTRACT_STIX_CYBER_OBSERVABLE]: `/extensions/${STIX_EXT_OCTI_SCO}/${objectLabel.stixName}`,
```
Comment (lndrtrbn) [inline opencti-platform/opencti-graphql/src/modules/playbook/playbook-components.ts:570]: Could you explain the change please?

Comment (JeremyCloarec) [reply opencti-platform/opencti-graphql/src/modules/playbook/playbook-components.ts:570]: The `PLAYBOOK_UPDATE_KNOWLEDGE_COMPONENT` that manipulates knowledge uses those `attributePathMapping` to decide where to put the added labels configured in the playbook. But it was using an incorrect path to put those labels: it was putting them in the` /extensions/${STIX_EXT_OCTI_SCO}` path of stix object, instead of putting them at the root of the stix object. Because they were at the incorrect path, they were then ignored during the bundle ingestion by the worker.
So now, instead of handling them at a different path than domain objects, we now use the same path for observable and domain objects. So we can configure the path for all stix core object instead.

**Review by SarahBocognano — APPROVED** [review]
