### PR TITLE
[backend] Fix merge of vocabularies

### LINKED ISSUE #4258: Merging of vocabularies is broken
## Description

1. Go to Settings / Taxonomies / Vocabularies
2. Go to attack_motivation_ov
3. Select personal-gain and personal-satisfaction

image

4. Merge them

Background task finished, the 2 vocabularies are still in the list.

### PR DESCRIPTION
**Pull request by Kedae**

### CODE REVIEW

File: opencti-platform/opencti-graphql/src/domain/backgroundTask-common.js [hunk 1]
```diff
@@ -168,5 +169,5 @@ export const createListTask = async (context, user, input) => {
 };
 
 export const isTaskEnabledEntity = (entityType) => {
```
Comment (RomuDeuxfois) [inline opencti-platform/opencti-graphql/src/domain/backgroundTask-common.js:180]: We can add an information message for the user where the entity passed as a parameter is not managed on the back side.
What do you think ?

**Comment by Archidoit** [comment]
Sugestions for design in Background task lists:
- 'Settings' translation
- set 'Settings' scope color to sth else than grey (not lisible and a color associated to deprecated/not-important)
image

**Comment by Archidoit** [comment]
Behavior OK 👍

File: opencti-platform/opencti-front/src/components/TaskScope.tsx [hunk 2]
```diff
@@ -42,6 +42,14 @@ const TaskScope: FunctionComponent<TaskScopeProps> = ({ label, scope }) => {
   const classes = useStyles();
   const style = classes.chip;
   switch (scope) {
+    case 'SETTINGS':
+      return (
+        <Chip
+          classes={{ root: style }}
+          style={inlineStyles.rose}
```
Comment (Archidoit) [inline opencti-platform/opencti-front/src/components/TaskScope.tsx]: same color as scope = 'RULE'

**Review by SarahBocognano — COMMENTED** [review]
Tested ✅ Works fine

File: opencti-platform/opencti-front/src/components/TaskScope.tsx (hunk 2 above)
Comment (Kedae) [reply opencti-platform/opencti-front/src/components/TaskScope.tsx]: Done

File: opencti-platform/opencti-graphql/src/domain/backgroundTask-common.js (hunk 1 above)
Comment (Kedae) [reply opencti-platform/opencti-graphql/src/domain/backgroundTask-common.js:180]: The API handles that, we just didn't add it in front and it could hide the fact that we put the toolbar somewhere we don't want to.
