### PR TITLE
[frontend/backend] Fix default value of variable "first" that cannot be null (#7905)

### LINKED ISSUE #7905: Can no longer access the "Data" tab of an Incident
## Description

Can no longer access the "Data" tab of an Incident (Event > Incident) -> An error is raised

## Environment

OCTI 6.2.10

## Reproducible Steps

Steps to create the smallest reproducible scenario:
1. Go to an Incident ("Event > Incident")
2. Open the "Data" tab

Screenshot 2024-08-01 085431

Screenshot 2024-08-01 085439

### PR DESCRIPTION
**Pull request by lndrtrbn**
### Proposed changes

* In front: change count variable of markings query to first to sync with backend name
* In back: avoid passing null to Elastic for pagination because not acceptable value

### Related issues

* #7905 

### Checklist

- [x] I consider the submitted work as finished
- [x] I tested the code for its functionality
- [ ] I wrote test cases for the relevant uses case (coverage and e2e)
- [ ] I added/update the relevant documentation (either on github or on notion)
- [x] Where necessary I refactored code to improve the overall quality

### Further comments

Elastic does not accept `null` value for its "size" parameter. Which correspond to the "first" option in our backend. We manage this option with a default value in case it was `undefined` but not when it was `null`. Now both cases fall back in default value.

### CODE REVIEW

File: opencti-platform/opencti-graphql/src/database/engine.js [hunk 1]
```diff
@@ -2974,7 +2976,8 @@ export const elPaginate = async (context, user, indexName, options = {}) => {
     );
 };
 export const elList = async (context, user, indexName, opts = {}) => {
-  const { first = ES_DEFAULT_PAGINATION, maxSize = undefined } = opts;
+  const { maxSize = undefined } = opts;
+  const first = opts.first ?? ES_DEFAULT_PAGINATION;
```
Comment (SouadHadjiat) [inline opencti-platform/opencti-graphql/src/database/engine.js:2980]: what is the difference between `const { first = ES_DEFAULT_PAGINATION } = opts;` and `const first = opts.first ?? ES_DEFAULT_PAGINATION;` ?

Comment (Kedae) [reply opencti-platform/opencti-graphql/src/database/engine.js:2980]: The null handling. { first = ES... } does not apply if first is null.

**Review by aHenryJard — COMMENTED** [review]
Can you add the reproduction of issue in this test ? https://github.com/OpenCTI-Platform/opencti/blob/11faded7a432cb1dc1c84b1c58f6d90ac66b0d13/opencti-platform/opencti-graphql/tests/02-integration/02-resolvers/markingDefinition-test.js#L88-L90

(I mean same query as we have with null => should not crash)

**Review by Archidoit — APPROVED** [review]
