### PR TITLE
[frontend] retro compatibility for entities relations histories (#4012)

### LINKED ISSUE #4012: In the history of a sector, the relationship historic is not correct
## Description

image

Originally:

* Only contains create / delete of relationships

Even if we would like to display also the modifications of the relationships:

* Icon is incorrect
* Message is not clear about which relationship has been modified so most of those messages are useless

### PR DESCRIPTION
**Pull request by Archidoit**
issue: https://github.com/OpenCTI-Platform/opencti/issues/4012

Explanation: 
in the history of an entity, the right panel shows the history of the relations of the entity. It should only show creations and deletions (not updates).

New history entities (after june 2023): 'create' or 'delete' is contained in event_scope
old history entities: 'create' or 'delete' is contained in event_type

The modifications here enable to take both new and old history entities into account (retro compatibility)

### CODE REVIEW

File: opencti-platform/opencti-front/src/private/components/common/stix_core_objects/StixCoreObjectHistory.jsx [hunk 1]
```diff
@@ -70,7 +70,7 @@ class StixCoreObjectHistory extends Component {
               filters: [
                 { key: 'entity_id', values: [stixCoreObjectId] },
                 {
-                  key: 'event_type',
+                  key: 'event_scope',
```
Comment (SouadHadjiat) [inline opencti-platform/opencti-front/src/private/components/common/stix_core_objects/StixCoreObjectHistory.jsx]: I'm not sure to understand why we should use `event_scope `instead of `event_type`. When I request `logs` in the demo graphql playground, `event_scope` is empty, while `event_type` contains the right values. Example with this report : https://demo.opencti.io/dashboard/analyses/reports/3a5e57e9-fdab-4421-b903-c7edeaf627d1

```
query {
  logs(
    first: 10
    filters: [{key: [entity_id], values: ["3a5e57e9-fdab-4421-b903-c7edeaf627d1"]}]
  ) {
    edges {
      node {
        id
        event_type
        event_scope
        entity_type
        timestamp
      }
    }
  }
}
```

Comment (Archidoit) [reply opencti-platform/opencti-front/src/private/components/common/stix_core_objects/StixCoreObjectHistory.jsx]: When you request the History objects in elastic, you can see that event_type contains a global type (like 'mutation'), and event_scope more precise types (like 'delete', 'update', etc).

Comment (Archidoit) [reply opencti-platform/opencti-front/src/private/components/common/stix_core_objects/StixCoreObjectHistory.jsx]: image

Comment (Archidoit) [reply opencti-platform/opencti-front/src/private/components/common/stix_core_objects/StixCoreObjectHistory.jsx]: event_type is updated with the value of event_scope, but not at the moment of the query I modified : 
image
(capture of the resolver log.js)

Comment (SouadHadjiat) [reply opencti-platform/opencti-front/src/private/components/common/stix_core_objects/StixCoreObjectHistory.jsx]: but `event_scope` has been introduced recenlty, has it been migrated to have a value for older logs ? From what I can see in the demo, `event_scope` is null for old logs, so the filter will get 0 results for this case

Comment (Archidoit) [reply opencti-platform/opencti-front/src/private/components/common/stix_core_objects/StixCoreObjectHistory.jsx]: ow i'm going to check that

Comment (Archidoit) [reply opencti-platform/opencti-front/src/private/components/common/stix_core_objects/StixCoreObjectHistory.jsx]: fixed

**Comment by Archidoit** [comment]
PR ready for review

**Review by SarahBocognano — COMMENTED** [review]
Tested for recent history✅
(I cannot test history from before May 2023 because I didn't have any data stored)

**Review by SouadHadjiat — COMMENTED** [review]
looks good, tested locally ✅

**Review by SouadHadjiat — APPROVED** [review]
