### PR TITLE
[frontend] fix broken layout on open import dialog (#10761)

### LINKED ISSUE #10761: Layout is broken when loading the import panel
## Description

Layout is broken when loading the import panel

1. Search bar is still displayed
2. Loader on the right misplaced / wired

https://github.com/user-attachments/assets/200adaa4-8ba9-4f85-a5cc-c02445f4e7e6

### PR DESCRIPTION
**Pull request by delemaf**
### Proposed changes

* Fix flashing import dialog

### Related issues

* Closes https://github.com/OpenCTI-Platform/opencti/issues/10761

### Checklist

- [x] I consider the submitted work as finished
- [x] I tested the code for its functionality
- [ ] I wrote test cases for the relevant uses case (coverage and e2e)
- [ ] I added/update the relevant documentation (either on github or on notion)
- [x] Where necessary I refactored code to improve the overall quality

### CODE REVIEW

File: opencti-platform/opencti-front/src/private/components/common/files/import_files/ImportFilesDialog.tsx [hunk 1]
```diff
@@ -478,8 +478,17 @@ const ImportFiles = ({ open, handleClose }: ImportFilesDialogProps) => {
...
 const ImportFilesDialog = ({ open, entityId, handleClose }: ImportFilesDialogProps) => {
+  const [dialogKey, setDialogKey] = useState(0);
+
+  useEffect(() => {
+    // Resets all dialog state on close by forcing a complete component remount via key change
+    if (!open) {
+      setDialogKey((prev) => prev + 1);
+    }
+  }, [open]);
+
```
Comment (lndrtrbn) [inline opencti-platform/opencti-front/src/private/components/common/files/import_files/ImportFilesDialog.tsx]: This solution looks more like a workaround to a bad use of some React concepts somewhere.
Can you explain the issue that this fix is supposed to solve ? (I mean technically, not functionally)

**Comment by Archidoit** [comment]
Working well 👍

File: opencti-platform/opencti-front/src/private/components/common/files/import_files/ImportFilesDialog.tsx (hunk 1 above)
Comment (delemaf) [reply opencti-platform/opencti-front/src/private/components/common/files/import_files/ImportFilesDialog.tsx]: It's a key-controlled reset (it doesn't really unmount the component) but it's more a workaround, I'll try to reset the state instead :+1:

Comment (delemaf) [reply opencti-platform/opencti-front/src/private/components/common/files/import_files/ImportFilesDialog.tsx]: After investigation it was the loader that broke the topbar, so I'll keep the ImportFilesDialog unmounted instead of resetting state

**Review by frapuks — APPROVED** [review]
