### PR TITLE
[frontend/backend] fix ordering in Activity (#5464)

### LINKED ISSUE #5464: Sorting the "event type" column in the Settings > Activity window crash
## Description

When we try to sort the data in the Settings > Activity window, on the "Event type" column, the window crashes (i.e. an error appears).

## Environment

OCTI 5.12.15

## Reproducible Steps

Steps to create the smallest reproducible scenario:
1. Go to Settings > Activity
2. Click on "entity type" (the name of the column) to order the list based on this column.
-> Crash

## Screenshots

Screenshot 2024-01-11 135943

Screenshot 2024-01-11 140143

### PR DESCRIPTION
**Pull request by Archidoit**
issue: https://github.com/OpenCTI-Platform/opencti/issues/5464

### CODE REVIEW

File: opencti-platform/opencti-front/src/private/components/settings/activity/audit/Audit.tsx [hunk 1]
```diff
@@ -124,7 +124,7 @@ const Audit = () => {
     user: {
       label: 'User',
       width: '15%',
-      isSortable: true,
+      isSortable: false,
```
Comment (labo-flg) [inline opencti-platform/opencti-front/src/private/components/settings/activity/audit/Audit.tsx:127]: why disabling sorting on users ?

Comment (labo-flg) [reply opencti-platform/opencti-front/src/private/components/settings/activity/audit/Audit.tsx:127]: ok, not part of LogsOrdering enum, got it :)

**Review by labo-flg — APPROVED** [review]
