### PR TITLE
[backend] Restrict organization access capability check failing (#4509)

### LINKED ISSUE #4509: Restrict organization access capability check failing
## Description

Users with "Restrict organization access" are unable to perform organization sharing. When attempted the message "You are not allowed to do this appears" instead of success.

## Environment

1. OS Ubuntu
2. OpenCTI version: OpenCTI 5.10.3
3. OpenCTI client: front-end
4. Other environment details:

## Reproducible Steps

Steps to create the smallest reproducible scenario:
1. Standup fresh instance of OpenCTI with docker-compose
2. Create role with 'Restrict organization access' capability, add it to a group, create a user and add to that group.
3. Create an organization
4. Create a report
5. Attempt to share the report to the organization

## Expected Output

Successful share

## Actual Output

A message appears "You are not allowed to do this"

## Additional information

After some digging it appears the capability check at:
https://github.com/OpenCTI-Platform/opencti/blob/5.10.3/opencti-platform/opencti-graphql/src/database/middleware.js#L1973
is failing.

The call to !userHaveCapability(user, KNOWLEDGE_ORGANIZATION_RESTRICT)
is passing 'KNOWLEDGE_KNUPDATE_KNORGARESTRICT' imported from opencti-graphql/src/utils/access.ts

but the userHaveCapability function is splitting up the values in user.capabilities such that it is trying to match that string against
one of:
['KNOWLEDGE',      'KNUPDATE',        'KNORGARESTRICT']
after the calls to split('_') and flatten().

If KNOWLEDGE_ORGANIZATION_RESTRICT is imported from opencti-graphql/src/schema/general.js
it will be set to 'KNORGARESTRICT' which will successfully match and this appears to work if I make the change locally. I don't believe it would interfere with other uses of that constant in middleware.js.

### PR DESCRIPTION
**Pull request by marieflorescontact**
### Proposed changes

* Use isUserHasCapability instead of userHaveCapability
*

### Related issues

* [issue/4509](https://github.com/OpenCTI-Platform/opencti/issues/4509)
*

### Checklist

- [x] I consider the submitted work as finished
- [x] I tested the code for its functionality
- [ ] I wrote test cases for the relevant uses case
- [ ] I added/update the relevant documentation (either on github or on notion)
- [x] Where necessary I refactored code to improve the overall quality

### Further comments

If this is a relatively large or complex change, kick off the discussion by explaining why you chose the solution you did and what alternatives you considered, etc...

### CODE REVIEW

File: opencti-platform/opencti-graphql/src/database/middleware.js [hunk 1]
```diff
@@ -1933,7 +1945,7 @@ export const updateAttribute = async (context, user, id, type, inputs, opts = {}
         }
       } else {
         // Special access check for RELATION_GRANTED_TO meta
-        if (relType === RELATION_GRANTED_TO && !userHaveCapability(user, KNOWLEDGE_ORGANIZATION_RESTRICT)) {
+        if (relType === RELATION_GRANTED_TO && !isUserHasCapability(user, KNOWLEDGE_ORGANIZATION_RESTRICT)) {
```
Comment (Goumies) [inline opencti-platform/opencti-graphql/src/database/middleware.js:1948]: Can we refactor `isUserHasCapability` to `doesUserHasCapability` ?

Comment (marieflorescontact) [reply opencti-platform/opencti-graphql/src/database/middleware.js:1948]: I don't know because the method has many uses and also because in the platform we have several different methods based on this "isUser..." model such as `isUserHasAccessToElemen`t or `isUserHasCapability`. But you're right, it should be `does` instead of `is`

Comment (guillaumejparis) [reply opencti-platform/opencti-graphql/src/database/middleware.js:1948]: Mmm problem is we have this syntax on others variables for example : 
  isBypassUser
  isUserCanAccessStoreElement
  isUserHasCapability
If we want to harmonize everything it will be a full issue I suppose

Comment (marieflorescontact) [reply opencti-platform/opencti-graphql/src/database/middleware.js:1948]: yes I agree with you @guillaumejparis  that's what it seems to me too

**Review by RomuDeuxfois — APPROVED** [review]
