### PR TITLE
[backend] Fix auth0 provider for env variable (#9554)

### LINKED ISSUE #9554: Auth0 issue when using environment variable for clientID
## Description

Authentification using auth0 does not work anymore and in logs there is:
```
TypeError: client_id is required
```

## Environment

1. OS (where OpenCTI server runs):
2. OpenCTI version: 6.4.6
3. OpenCTI client:
4. Other environment details:

## Reproducible Steps

Steps to create the smallest reproducible scenario:
1. { e.g. Run ... }
2. { e.g. Click ... }
3. { e.g. Error ... }

### PR DESCRIPTION
**Pull request by aHenryJard**
### Proposed changes

* Fix env var for auth0

### Related issues

* closes #9554 

### Checklist

- [ ] I consider the submitted work as finished
- [ ] I tested the code for its functionality
- [ ] I wrote test cases for the relevant uses case (coverage and e2e)
- [ ] I added/update the relevant documentation (either on github or on notion)
- [ ] Where necessary I refactored code to improve the overall quality

### CODE REVIEW

File: opencti-platform/opencti-graphql/src/config/conf.js [hunk 1]
```diff
@@ -253,8 +253,8 @@ export const logApp = {
     if (appLogTransports.length > 0 && appLogger.isLevelEnabled(level)) {
       const data = addBasicMetaInformation(LOG_APP, error, { ...meta, source: 'backend' });
       // Prevent meta information to be too massive.
-      const limitedData = limitMetaErrorComplexity(data);
-      appLogger.log(level, message, limitedData);
+      // const limitedData = limitMetaErrorComplexity(data);
```
Comment (labo-flg) [inline opencti-platform/opencti-graphql/src/config/conf.js]: why this ? if necessary to keep, please add a comment

Comment (richard-julien) [reply opencti-platform/opencti-graphql/src/config/conf.js]: Seen with Angelique, its a problem i need to fix on my side

**Comment by labo-flg** [comment]
Ci build failing for a failed test @richard-julien 
>   × Logger test suite > Log object is correctly limited
>     → expected 56 to not deeply equal 56
