### PR TITLE
[backend] fix public dashboard with platform organization (#6948)

### LINKED ISSUE #6948: Public dashboards with platform organization are not working
## Description

1. Go to Security => Policy
2. Set a platform organization
3. Go to your public dashboard

=> Everything is 0 or restricted.

### PR DESCRIPTION
**Pull request by marieflorescontact**
### Proposed changes

* add `inside_platform_organization` set to true to user used for private dashboard api calling

### Related issues

* [issue/6948](https://github.com/OpenCTI-Platform/opencti/issues/6948)

### Checklist

- [x] I consider the submitted work as finished
- [x] I tested the code for its functionality
- [ ] I wrote test cases for the relevant uses case (coverage and e2e)
- [ ] I added/update the relevant documentation (either on github or on notion)
- [ ] Where necessary I refactored code to improve the overall quality

### CODE REVIEW

File: opencti-platform/opencti-graphql/src/modules/publicDashboard/publicDashboard-utils.ts [hunk 1]
```diff
@@ -106,7 +106,8 @@ export const getWidgetArguments = async (
     ...platformUser,
     origin: { user_id: platformUser.id, referer: 'public-dashboard' },
     allowed_marking: allowedMaxMarkings,
-    capabilities: [accessKnowledgeCapability]
+    capabilities: [accessKnowledgeCapability],
+    inside_platform_organization: true,
```
Comment (lndrtrbn) [inline opencti-platform/opencti-graphql/src/modules/publicDashboard/publicDashboard-utils.ts]: Why hard coding the value to `true` ? Can't we use the value of the `platformUser` ?

**Review by lndrtrbn — APPROVED** [review]
