### PR TITLE
[backend] fix clean up of denormalized rel if multiple rel of same type exists (#7208)

### LINKED ISSUE #7208: When having 2 relations with the same type between the 2 entities, deleting the first one leads to purge _rel
## Description

When having 2 relations with the same type between the 2 entities, deleting the first one leads to purge _rel

### PR DESCRIPTION
**Pull request by JeremyCloarec**
### Proposed changes

* keep 'duplicates' in computeDeleteElementsImpacts. If a 'duplicate' id is found, it is there for a good reason: it needs to be taken into account, because it means that there are 2 relations of the same type and same target
* change script in elRemoveRelationConnection to only remove first occurence of cleanUpIds

### Related issues

* #7208 
*

### Checklist

- [x] I consider the submitted work as finished
- [x] I tested the code for its functionality
- [ ] I wrote test cases for the relevant uses case (coverage and e2e)
- [ ] I added/update the relevant documentation (either on github or on notion)
- [ ] Where necessary I refactored code to improve the overall quality

### CODE REVIEW

File: opencti-platform/opencti-graphql/src/database/engine.js [hunk 1]
```diff
@@ -3728,18 +3728,31 @@ export const elRemoveRelationConnection = async (context, user, elementsImpact)
           const [relationType, relationIndex, side, sideType] = typeAndIndex.split('|');
           const refField = isStixRefRelationship(relationType) && isInferredIndex(relationIndex) ? ID_INFERRED : ID_INTERNAL;
           const rel_key = buildRefRelationKey(relationType, refField);
-          let source = `if (ctx._source['${rel_key}'] != null) ctx._source['${rel_key}'] = ctx._source['${rel_key}'].stream().filter(id -> !params.cleanupIds.contains(id)).collect(Collectors.toList())`;
```
Comment (richard-julien) [inline opencti-platform/opencti-graphql/src/database/engine.js:3731]: Why not just removing the first occurrence?

Comment (JeremyCloarec) [reply opencti-platform/opencti-graphql/src/database/engine.js:3731]: That's because we don't always want to only remove the first occurence: if we delete the target for example, we will want to delete 2 occurences if we had two relations of the same type to this target (cleanupIds will contain the target ID twice in this case)

**Review by SouadHadjiat — APPROVED** [review]
