### PR TITLE
[backend] Error log rework (#5257)

### LINKED ISSUE #5257: An unknown error has occurred without exception details when initialization fails
## Description

If platform initialization fails for some reason, we log an unknown error has occurred without any details about the exception that was raised during initialization.

`ERR [OPENCTI] Platform start fail | category=APP error={"context":{"category":"technical","error":{},"http_status":500,"reason":"[OPENCTI] Platform initialization fail"},"message":"An unknown error has occurred","name":"UnknownError","stack":"UnknownError: An unknown error has occurred\n    at error (/opt/opencti/build/src/config/errors.js:8:10)\n    at UnknownError (/opt/opencti/build/src/config/errors.js:72:47)\n    at platformInit (/opt/opencti/build/src/initialization.js:386:13)\n    at processTicksAndRejections (node:internal/process/task_queues:95:5)\n    at platformStart (/opt/opencti/build/src/boot.js:231:5)"} timestamp=2023-12-18T11:43:52.611Z version=5.12.9`

## Environment

1. OS (where OpenCTI server runs): { e.g. Mac OS 10, Windows 10, Ubuntu 16.4, etc. }
2. OpenCTI version: 5.12.9
3. OpenCTI client: frontend
4. Other environment details:

### PR DESCRIPTION
**Pull request by richard-julien**
See #5257

- Improve logging to prevent any error overrides. Format will include now a list of errors if cascading occurs.
- Prefixed message no longer required in error logs
- Fixing async warning for manager start

### CODE REVIEW

File: opencti-platform/opencti-graphql/src/config/errors.js [hunk 1]
```diff
@@ -1,43 +1,47 @@
-import { createError } from 'apollo-errors';
+import { ApolloError, createError } from 'apollo-errors';
 
-const CATEGORY_TECHNICAL = 'technical';
-const CATEGORY_BUSINESS = 'business';
+const CATEGORY_TECHNICAL = 'TECHNICAL';
```
Comment (aHenryJard) [inline opencti-platform/opencti-graphql/src/config/errors.js:3]: Question: why don't we use the exception type to set the error category instead of having constant here ? We could also set the category inside the error type.

File: opencti-platform/opencti-graphql/src/graphql/loggerPlugin.js [hunk 2]
```diff
@@ -29,7 +29,7 @@ const tryResolveKeyPromises = async (data) => {
   }
 };
 
-const API_CALL_MESSAGE = 'API Call'; // If you touch this, you need to change the performance agent
+const API_CALL_MESSAGE = 'GRAPHQL_API'; // If you touch this, you need to change the performance agent
```
Comment (aHenryJard) [inline opencti-platform/opencti-graphql/src/graphql/loggerPlugin.js:32]: Did you changed the performance agent ? I have no idea on what is the performance agent on my side.

File: opencti-platform/opencti-graphql/src/manager/connectorManager.js [hunk 3]
```diff
@@ -132,7 +132,7 @@ const connectorHandler = async () => {
 const initConnectorManager = () => {
   let scheduler;
   return {
-    start: () => {
+    start: async () => {
```
Comment (aHenryJard) [inline opencti-platform/opencti-graphql/src/manager/connectorManager.js:135]: this change seems unrelated to error/log management, is it intended ?

File: opencti-platform/opencti-graphql/src/manager/expiredManager.js [hunk 4]
```diff
@@ -94,7 +94,7 @@ const expireHandler = async () => {
 const initExpiredManager = () => {
   let scheduler;
   return {
-    start: () => {
+    start: async () => {
```
Comment (aHenryJard) [inline opencti-platform/opencti-graphql/src/manager/expiredManager.js:97]: this change seems unrelated to error/log management, is it intended ?

File: opencti-platform/opencti-graphql/src/manager/retentionManager.js [hunk 5]
```diff
@@ -84,7 +84,7 @@ const retentionHandler = async () => {
 const initRetentionManager = () => {
   let scheduler;
   return {
-    start: () => {
+    start: async () => {
```
Comment (aHenryJard) [inline opencti-platform/opencti-graphql/src/manager/retentionManager.js:87]: ditto, this change seems unrelated to error/log management, is it intended ?

**Review by aHenryJard — COMMENTED** [review]
That's a huge improvement, thanks. I tested locally exception/errors quickly, logging works as expected as far as I see.

The "async()" changes does not seems to be related to error log rework, if it's intended to add  them in the same PR, please add it to the PR description. Will wait on feedback on this last part to validate the PR.

File: opencti-platform/opencti-graphql/src/graphql/loggerPlugin.js (hunk 2 above)
Comment (richard-julien) [reply opencti-platform/opencti-graphql/src/graphql/loggerPlugin.js:32]: Yes, it will be impacted after the merge.
Performance agent is the automated internal performance tests of the solution.

File: opencti-platform/opencti-graphql/src/manager/connectorManager.js (hunk 3 above)
Comment (richard-julien) [reply opencti-platform/opencti-graphql/src/manager/connectorManager.js:135]: Its unrelated, just a warning fix

File: opencti-platform/opencti-graphql/src/manager/expiredManager.js (hunk 4 above)
Comment (richard-julien) [reply opencti-platform/opencti-graphql/src/manager/expiredManager.js:97]: Its unrelated, just a warning fix

File: opencti-platform/opencti-graphql/src/manager/retentionManager.js (hunk 5 above)
Comment (richard-julien) [reply opencti-platform/opencti-graphql/src/manager/retentionManager.js:87]: Its unrelated, just a warning fix

**Comment by richard-julien** [comment]
> That's a huge improvement, thanks. I tested locally exception/errors quickly, logging works as expected as far as I see.
> 
> The "async()" changes does not seems to be related to error log rework, if it's intended to add them in the same PR, please add it to the PR description. Will wait on feedback on this last part to validate the PR.

Added in PR description. Thanks for the review!

**Review by aHenryJard — APPROVED** [review]
