### PR TITLE
[frontend] Remove "update" or "delete" button on attack pattern within an incident kill chain view(#8330)

### LINKED ISSUE #8330: Hamburger buttons to update or delete an attack pattern within an incident doesn't work and redirect to the attack pattern page.
## Description

When clicking on the hamburger buttons to update or delete an attack pattern within an incident, the modification drop down menu appears just 2 sec and then redirect to the attack pattern page.

## Environment

2. OpenCTI version: 6.2.18

## Reproducible Steps

1. Go to an incident page
2. Knowledge
3. In Techniques, select Attack Pattern
4. Select Kill chain vue
5. On an attack pattern, click on the hamburger buttons at the right side
6. The modification window appears just 2 sec 
7. The click redirect to the attack pattern page.

## Expected Output

Display the modification drop down menu to click on the update or delete button.

## Actual Output

The modification drop down menu appears just 2 sec and the click redirect to the attack pattern page.

### PR DESCRIPTION
**Pull request by CelineSebe**
### Proposed changes

* 
### Related issues

* #8330 

### Checklist

- [ ] I consider the submitted work as finished
- [ ] I tested the code for its functionality
- [ ] I wrote test cases for the relevant uses case (coverage and e2e)
- [ ] I added/update the relevant documentation (either on github or on notion)
- [ ] Where necessary I refactored code to improve the overall quality

### CODE REVIEW

**Review by marieflorescontact — APPROVED** [review]
locally tested ok 👌

File: opencti-platform/opencti-front/src/private/components/common/stix_domain_objects/StixDomainObjectAttackPatternsKillChainLines.tsx [hunk 1]
```diff
@@ -204,11 +201,7 @@ const StixDomainObjectAttackPatternsKillChainLines: FunctionComponent<StixDomain
                                     )}
                                   </IconButton>
                                 ) : (
-                                  <StixCoreRelationshipPopover
-                                    stixCoreRelationshipId={attackPattern.id}
-                                    paginationOptions={paginationOptions}
-                                    onDelete={onDelete}
-                                  />
+                                  <></>
```
Comment (JeremyCloarec) [inline opencti-platform/opencti-front/src/private/components/common/stix_domain_objects/StixDomainObjectAttackPatternsKillChainLines.tsx]: This is OK, but I think it would be cleaner if this was simplified to
```
{ coursesOfAction ? (
   component
)}
```
now that we no longer do anything when coursesOfAction=false

**Review by JeremyCloarec — APPROVED** [review]
