### PR TITLE
[frontend] Fix error message when attempting to create an artifact without file (#6052)

### LINKED ISSUE #6052: No error message when attempting to create an artifact without file
## Description

In theory, when a object is attempted to be created, there is a validation on the mandatory fields. This validation occurs, but no error message is displayed. It would be great to have an error message indicating to the user that a file must be uploaded for sake of clarity (like other entities).

## Environment

1. OS (where OpenCTI server runs): { e.g. Mac OS 10, Windows 10, Ubuntu 16.4, etc. }
2. OpenCTI version: { e.g. OpenCTI 1.0.2 }
3. OpenCTI client: { e.g. frontend or python }
4. Other environment details:

## Reproducible Steps

Steps to create the smallest reproducible scenario:
1. go to artifact
2. click on the + to create
3. click on create
4. nothing happens

## Expected Output

See an error message because I did not upload a file

## Actual Output

Nothing happen

### PR DESCRIPTION
**Pull request by CelineSebe**
### Proposed changes

* [Frontend] Add a useEffect to set the errorText in the CustomFileUploader component

### Related issues

* #6052 

### Checklist

- [ ] I consider the submitted work as finished
- [ ] I tested the code for its functionality
- [ ] I wrote test cases for the relevant uses case
- [ ] I added/update the relevant documentation (either on github or on notion)
- [ ] Where necessary I refactored code to improve the overall quality

### Further comments

If this is a relatively large or complex change, kick off the discussion by explaining why you chose the solution you did and what alternatives you considered, etc...

### CODE REVIEW

File: opencti-platform/opencti-graphql/src/domain/stixCyberObservable.js [hunk 1]
```diff
@@ -389,6 +389,9 @@ export const artifactImport = async (context, user, args) => {
   const artifact = await addStixCyberObservable(context, user, artifactData);
   const meta = { version };
   await upload(context, user, `import/${artifact.entity_type}/${artifact.id}`, resolvedFile, { entity: artifact, meta });
+  if (!upload) {
+    throw FunctionalError('Something went wrong with the file upload');
+  }
```
Comment (labo-flg) [inline opencti-platform/opencti-graphql/src/domain/stixCyberObservable.js]: the upload variable seems undefined

```suggestion
  const upload = await upload(context, user, `import/${artifact.entity_type}/${artifact.id}`, resolvedFile, { entity: artifact, meta });
  if (!upload) {
    throw FunctionalError('Something went wrong with the file upload');
  }
```

**Comment by labo-flg** [comment]
Seen in pair review:

it's more like a frontend display issue. The yup validation is working fine as it is in `ArtifactCreation`. It's just that the error message is not displayed.

We need to pass down the formik errors to the `CustomFileUpload` so that it's internal error state is updated on formik error received, and not only on the custom error it checks on his own.

This way user gets a good feedback in the form.

As for the observable creation form, it's a lot more work as this is used for all types of observables, without yup validation... and backend errors are not always understandable. See #5454

**Review by SarahBocognano — APPROVED** [review]
Tested ✅

**Comment by CelineSebe** [comment]
I just added a createArtifact test. I would appreciate a review of this part if possible.

File: opencti-platform/opencti-front/src/private/components/common/files/CustomFileUploader.tsx [hunk 2]
```diff
@@ -60,12 +63,21 @@ const CustomFileUploader: FunctionComponent<CustomFileUploadProps> = ({
...
   sizeLimit = 0, // defaults to 0 = no limit
+  formikErrors,
 }) => {
   const { t_i18n } = useFormatter();
   const classes = useStyles();
   const [fileNameForDisplay, setFileNameForDisplay] = useState('');
   const [errorText, setErrorText] = useState('');
 
+  useEffect(() => {
+    if (formikErrors?.file) {
```
Comment (lndrtrbn) [inline opencti-platform/opencti-front/src/private/components/common/files/CustomFileUploader.tsx:74]: By passing the entire `formikErrors` object and hardcoding the property `.file` here we force to use this component with the property `file` instead of leaving the liberty to the caller to chose by itself how the property should be named. But I see it is already made this way for `setFieldValue` below so... Ok, don't bother change the entire component.

File: opencti-platform/opencti-front/tests_e2e/artifact/createArtifact.spec.ts [hunk 3]
```diff
@@ -0,0 +1,15 @@
...
+import { expect, test } from "../fixtures/baseFixtures";
+
+
+test('Validate a new artifact file', async ({ page }) => {
+        const artifactPage = new ArtifactPage(page);
+        const artifactImport = new ArtifactImportPage(page);
+        await page.goto('/dashboard/observations/artifacts')
+        await artifactPage.addNewArtifactImport().click();
+        artifactImport.getFileInput();
+        // await artifactImport.fillFileInput('File');
```
Comment (lndrtrbn) [inline opencti-platform/opencti-front/tests_e2e/artifact/createArtifact.spec.ts]: To remove? 
And it seems you have indentation issues. Is the linter applied on test files here?

File: opencti-platform/opencti-front/tests_e2e/model/ArtifactImport.pageModel.tsx
Comment (lndrtrbn) [inline opencti-platform/opencti-front/tests_e2e/model/ArtifactImport.pageModel.tsx:1]: Why have an other page model for import button instead of having all in the Artifact page model?

File: opencti-platform/opencti-front/tests_e2e/artifact/createArtifact.spec.ts [hunk 4]
```diff
@@ -0,0 +1,15 @@
+import { ArtifactPage} from "../model/Artifact.pageModel";
+import { ArtifactImportPage} from "../model/ArtifactImport.pageModel";
+import { expect, test } from "../fixtures/baseFixtures";
+
+
+test('Validate a new artifact file', async ({ page }) => {
```
Comment (lndrtrbn) [inline opencti-platform/opencti-front/tests_e2e/artifact/createArtifact.spec.ts]: Be more explicit on what the test is testing: should display an error if trying to create an artifact without a file

File: opencti-platform/opencti-front/tests_e2e/model/ArtifactImport.pageModel.tsx
Comment (lndrtrbn) [reply opencti-platform/opencti-front/tests_e2e/model/ArtifactImport.pageModel.tsx:1]: In my opinion you can regroup those two, especially as they are both very small

File: opencti-platform/opencti-front/tests_e2e/artifact/createArtifact.spec.ts (hunk 3 above)
Comment (CelineSebe) [reply opencti-platform/opencti-front/tests_e2e/artifact/createArtifact.spec.ts]: Indeed, thanks :)
No issue with the linter

File: opencti-platform/opencti-front/tests_e2e/model/ArtifactImport.pageModel.tsx
Comment (CelineSebe) [reply opencti-platform/opencti-front/tests_e2e/model/ArtifactImport.pageModel.tsx:1]: It allows placing the data-test-id on the Artifact page root. It seems to be a good practice to place this element fairly high in the file hierarchy. I believe they serve as anchor points that can be reused for other tests.

Comment (lndrtrbn) [reply opencti-platform/opencti-front/tests_e2e/model/ArtifactImport.pageModel.tsx:1]: But regrouping does not mean you can't do that

File: opencti-platform/opencti-front/tests_e2e/artifact/createArtifact.spec.ts (hunk 3 above)
Comment (lndrtrbn) [reply opencti-platform/opencti-front/tests_e2e/artifact/createArtifact.spec.ts]: After testing, there is an issue as the linter seems not linting e2e spec files but not related to your PR.

File: opencti-platform/opencti-front/tests_e2e/model/ArtifactImport.pageModel.tsx
Comment (CelineSebe) [reply opencti-platform/opencti-front/tests_e2e/model/ArtifactImport.pageModel.tsx:1]: If I understand correctly, you want me to group the functions in the same pageModel?
If that's the case, I prefer to separate the actions by screen... I find that we understand better what's happening

File: opencti-platform/opencti-front/tests_e2e/artifact/createArtifact.spec.ts (hunk 3 above)
Comment (CelineSebe) [reply opencti-platform/opencti-front/tests_e2e/artifact/createArtifact.spec.ts]: I see the indentation issue now, it's fixed! Thank you

File: opencti-platform/opencti-front/tests_e2e/model/ArtifactImport.pageModel.tsx
Comment (lndrtrbn) [reply opencti-platform/opencti-front/tests_e2e/model/ArtifactImport.pageModel.tsx:1]: You still are on the same screen, the content inside `ArtifactImport.pageModel` is just the form of the page `Artifacts` to create new ones.  But anyway, as you prefer 🙂

**Review by lndrtrbn — APPROVED** [review]
