### PR TITLE
[backend] Fix parse_exception: request body is required (#6552)

### LINKED ISSUE #6552: parse_exception: request body is required when Retention Policy is executed
Seeing lots of the message below in the logs.
```
{
  "category": "APP",
  "errors": [
    {
      "attributes": {
        "genre": "TECHNICAL",
        "http_status": 500
      },
      "message": "parse_exception\n\tRoot causes:\n\t\tparse_exception: request body is required",
      "name": "UNKNOWN_ERROR",
      "stack": "UNKNOWN_ERROR: parse_exception\n\tRoot causes:\n\t\tparse_exception: request body is required\n    at error (/opt/opencti/build/src/config/errors.js:8:10)\n    at UnknownError (/opt/opencti/build/src/config/errors.js:76:47)\n    at Object._logWithError (/opt/opencti/build/src/config/conf.js:331:23)\n    at Object.error (/opt/opencti/build/src/config/conf.js:341:48)\n    at executeProcessing (/opt/opencti/build/src/manager/retentionManager.js:42:14)\n    at processTicksAndRejections (node:internal/process/task_queues:95:5)\n    at retentionHandler (/opt/opencti/build/src/manager/retentionManager.js:69:9)\n    at /opt/opencti/build/src/manager/retentionManager.js:90:9\n    at Y_t.#runHandlerAndScheduleTimeout (/opt/opencti/build/node_modules/set-interval-async/dist/set-interval-async-timer.cjs:36:13)\n    at Timeout._onTimeout (/opt/opencti/build/node_modules/set-interval-async/dist/set-interval-async-timer.cjs:29:13)"
    },
    {
      "message": "parse_exception\n\tRoot causes:\n\t\tparse_exception: request body is required",
      "name": "ResponseError",
      "stack": "ResponseError: parse_exception\n\tRoot causes:\n\t\tparse_exception: request body is required\n    at Uon.request (/opt/opencti/build/node_modules/@elastic/transport/src/Transport.ts:553:17)\n    at processTicksAndRejections (node:internal/process/task_queues:95:5)\n    at Trt.BulkApi [as bulk] (/opt/opencti/build/node_modules/@elastic/elasticsearch/src/api/api/bulk.ts:75:10)\n    at elRemoveRelationConnection (/opt/opencti/build/src/database/engine.js:3128:7)\n    at elDeleteElements (/opt/opencti/build/src/database/engine.js:3189:3)\n    at internalDeleteElementById (/opt/opencti/build/src/database/middleware.js:3355:7)\n    at deleteElementById (/opt/opencti/build/src/database/middleware.js:3377:32)\n    at executeProcessing (/opt/opencti/build/src/manager/retentionManager.js:39:7)\n    at retentionHandler (/opt/opencti/build/src/manager/retentionManager.js:69:9)\n    at /opt/opencti/build/src/manager/retentionManager.js:90:9\n    at Y_t.#runHandlerAndScheduleTimeout (/opt/opencti/build/node_modules/set-interval-async/dist/set-interval-async-timer.cjs:36:13)\n    at Timeout._onTimeout (/opt/opencti/build/node_modules/set-interval-async/dist/set-interval-async-timer.cjs:29:13)"
    }
  ],
  "id": "7463e007-0cd4-4a1e-aba6-ee56d8c67e27",
  "level": "error",
  "manager": "RETENTION_MANAGER",
  "message": "Platform unmanaged direct error",
  "timestamp": "2024-04-02T07:44:42.729Z",
  "version": "6.0.8"
}
```

Seems consisten with the execution of this rule 

image

Ubuntu 22.04 baremetal.
Each platform service in cluster or dedicated VMWare VM

## Expected Output

Objects matched by the rule being deleted

## Actual Output

Objects acumulated in remaining in the rule

## Additional information

Other rules are working flawlesly

### PR DESCRIPTION
**Pull request by SouadHadjiat**
### Proposed changes

* add a test on body length before calling elBulk

### Related issues
Issue not reproduced locally

* #6552 

### Checklist

- [x] I consider the submitted work as finished
- [ ] I tested the code for its functionality
- [ ] I wrote test cases for the relevant uses case (coverage and e2e)
- [ ] I added/update the relevant documentation (either on github or on notion)
- [ ] Where necessary I refactored code to improve the overall quality

### CODE REVIEW

File: opencti-platform/opencti-graphql/src/database/engine.js [hunk 1]
```diff
@@ -3162,7 +3162,9 @@ const elRemoveRelationConnection = async (context, user, elementsImpact) => {
         });
       });
       const bodyUpdate = R.flatten(bodyUpdateRaw);
-      await elBulk({ refresh: true, timeout: BULK_TIMEOUT, body: bodyUpdate });
+      if (bodyUpdate.length > 0) {
```
Comment (Kedae) [inline opencti-platform/opencti-graphql/src/database/engine.js:3165]: Shouldn't we investigate why we don't have a body rather ?

Comment (SouadHadjiat) [reply opencti-platform/opencti-graphql/src/database/engine.js:3165]: I didn't have time to investigate in details, I guessed the relationships we try to delete have already been deleted. But if you think we should take more time to fix this issue, let me know.

Comment (Kedae) [reply opencti-platform/opencti-graphql/src/database/engine.js:3165]: It's not about time spent on task it's about knowing what we are fixing.

I'm always afraid of that kind of fix because it might be hidding a real root cause that we will keep having.

Comment (SouadHadjiat) [reply opencti-platform/opencti-graphql/src/database/engine.js:3165]: I understand, but in this code, we have no way of knowing that we will find all the relationships we want to delete in the database. We have the same condition in elIndexElements : 
```
if (bodyUpdate.length > 0) {
  const bulkPromise = elBulk({ refresh: true, timeout: BULK_TIMEOUT, body: bodyUpdate });
  await Promise.all([bulkPromise]);
}
```
What do you think @richard-julien ? did I miss something about this code ?

Comment (richard-julien) [reply opencti-platform/opencti-graphql/src/database/engine.js:3165]: Looks like we have a condition when the list can be empty

```
          if (isEmptyField(fromIndex)) { // No need to clean up the connections if the target is already deleted.
            return updates;
          }
```

If i remember well is a condition to optimize the number of operation to execute, so can be empty in some conditions
Im ok with the fix.

**Review by aHenryJard — APPROVED** [review]
Looks good to me after reading all comments in the PR.
