### PR TITLE
[frontend] fix handling of references enforcment in containers

### LINKED ISSUE #6074: The way to handle external ref is inconsistent
## Description
We had a [bug](https://github.com/OpenCTI-Platform/opencti/issues/5884) to fix the behavior of external references in reports.
As mentioned in [this ](https://github.com/OpenCTI-Platform/opencti/issues/5884#issuecomment-1957280799) comment of the same ticket, the behavior of enforcing reference is bigger. 

## Environment

Demo

## Reproducible Steps

Edit an entity while having external reference 
1. Have external reference enforced for your entity 
2. Click on an entity (ex report) that have an external reference
3. Click on edit 
4. Click on the field external ref
5. You only see the external ref of the report, not the full list of external refs of your platform and cannot select existing ones already created that do not pertains to your entity.

Expected output: 
You should see the list of all the external refs to be able to add another one.

Sharing entity to an org
1. Have external reference enforced for your entity 
2. Click on an entity (ex report) that have an external reference enforced
3. Click on share to org
4. select an org
5. You got an error message because you have not added any external ref 

Expected output: 
It would help if you were prompted the pop up to add an external ref instead of having an error message. 

Remove all external references while enforce external reference is enabled
1. Have external reference enforced for your entity 
2. Click on an entity (ex report) that have an external reference enforced and have some external ref
3. Remove all external ref

Expected output: 
You should not be able to remove all external ref. At least always 1 external ref must remains in the entity.

Adding relations (core ) is sometimes possible without having to add an external ref
1. Have external reference enforced for your entity 
2. Go to your entity and click on add relation 

Expected output: 
You should not be able to add a relation without adding an external ref. The pop up must be pormpted if not in the form.

### PR DESCRIPTION
**Pull request by JeremyCloarec**
### Proposed changes

* [x] fix enable references in containers entity lines popover 
* [x] fix enable references in containers knowledge graph (ask for references when removing from graph)
* [x] fix malware analysis creation and edition when external references are enforced
* [x] fix enable references behavior for organization sharing (skip reference in case of orga?)

### Related issues

* #6074 

### Checklist

- [x] I consider the submitted work as finished
- [x] I tested the code for its functionality
- [ ] I wrote test cases for the relevant uses case (coverage and e2e)
- [ ] I added/update the relevant documentation (either on github or on notion)
- [ ] Where necessary I refactored code to improve the overall quality

### Further comments

If this is a relatively large or complex change, kick off the discussion by explaining why you chose the solution you did and what alternatives you considered, etc...

### CODE REVIEW

**Comment by nino-filigran** [comment]
after a discussion ith @JeremyCloarec we decided to split the fix in 2: the following bug will tackle the rest, since this bug has been opened since a while. Also, the missing cases are a bit bigger to tackle and impact is less important. https://github.com/OpenCTI-Platform/opencti/issues/7023

**Comment by SarahBocognano** [comment]
What is happening with this fix ? Can we review it or it will be split in 2 ?

**Comment by JeremyCloarec** [comment]
> What is happening with this fix ? Can we review it or it will be split in 2 ?

it can be reviewed, the remaining things to fix will be done on a separate PR and will link to this issue https://github.com/OpenCTI-Platform/opencti/issues/7023

File: opencti-platform/opencti-front/src/private/components/analyses/groupings/GroupingKnowledgeGraphBar.jsx [hunk 1]
```diff
@@ -303,6 +306,30 @@ class GroupingKnowledgeGraphBar extends Component {
...
   }
 
+  closeReferencesPopup() {
+    this.setState({ referenceDialogOpened: false });
+  }
+
+  submitReference(values, { setSubmitting, resetForm }) {
+    const { handleDeleteSelected } = this.props;
+    const { deleteObject } = this.state;
+    const commitMessage = values.message;
```
Comment (ValentinBouzinFiligran) [inline opencti-platform/opencti-front/src/private/components/analyses/groupings/GroupingKnowledgeGraphBar.jsx]: this constant can be removed to use value.message directly as params on the function ?

File: opencti-platform/opencti-front/src/private/components/analyses/groupings/GroupingKnowledgeGraphBar.jsx [hunk 2]
```diff
@@ -1100,16 +1128,39 @@ class GroupingKnowledgeGraphBar extends Component {
                           {t('Cancel')}
                         </Button>
                         <Button
-                          onClick={() => {
-                            this.handleCloseRemove();
-                            handleDeleteSelected(deleteObject);
-                          }}
+                          onClick={ this.handleSubmitRemoveElements.bind(this)}
```
Comment (ValentinBouzinFiligran) [inline opencti-platform/opencti-front/src/private/components/analyses/groupings/GroupingKnowledgeGraphBar.jsx]: blank space

File: opencti-platform/opencti-front/src/private/components/analyses/malware_analyses/MalwareAnalysisEditionDetails.tsx [hunk 3]
```diff
@@ -77,25 +79,28 @@ interface MalwareAnalysisEditionDetailsProps {
 
 interface MalwareAnalysisEditionFormValues {
   message?: string
-  references?: Option[]
+  references: ExternalReferencesValues | undefined
```
Comment (ValentinBouzinFiligran) [inline opencti-platform/opencti-front/src/private/components/analyses/malware_analyses/MalwareAnalysisEditionDetails.tsx:82]: references: ExternalReferencesValues | undefined better than references?: ExternalReferencesValues

File: opencti-platform/opencti-front/src/private/components/analyses/groupings/GroupingKnowledgeGraphBar.jsx [hunk 4]
```diff
@@ -303,6 +306,30 @@ class GroupingKnowledgeGraphBar extends Component {
...
 
+  closeReferencesPopup() {
+    this.setState({ referenceDialogOpened: false });
+  }
+
+  submitReference(values, { setSubmitting, resetForm }) {
+    const { handleDeleteSelected } = this.props;
+    const { deleteObject } = this.state;
+    const commitMessage = values.message;
+    const references = R.pluck('value', values.references || []);
```
Comment (lndrtrbn) [inline opencti-platform/opencti-front/src/private/components/analyses/groupings/GroupingKnowledgeGraphBar.jsx]:
```suggestion
    const references = (values.references || []).map(ref => ref.value);
```
Trying to not use ramda

File: opencti-platform/opencti-front/src/private/components/analyses/malware_analyses/MalwareAnalysisEditionOverview.tsx [hunk 5]
```diff
@@ -116,10 +118,11 @@ interface MalwareAnalysisEditionOverviewProps {
 
 interface MalwareAnalysisEditionFormValues {
   message?: string
-  references?: Option[]
+  references: ExternalReferencesValues | undefined
```
Comment (lndrtrbn) [inline opencti-platform/opencti-front/src/private/components/analyses/malware_analyses/MalwareAnalysisEditionOverview.tsx]: Could we fix this interface ? It does not represent the values of the form

File: opencti-platform/opencti-front/src/private/components/analyses/reports/ReportKnowledgeGraphBar.jsx [hunk 6]
```diff
@@ -303,6 +306,30 @@ class ReportKnowledgeGraphBar extends Component {
...
 
+  closeReferencesPopup() {
+    this.setState({ referenceDialogOpened: false });
+  }
+
+  submitReference(values, { setSubmitting, resetForm }) {
+    const { handleDeleteSelected } = this.props;
+    const { deleteObject } = this.state;
+    const commitMessage = values.message;
+    const references = R.pluck('value', values.references || []);
```
Comment (lndrtrbn) [inline opencti-platform/opencti-front/src/private/components/analyses/reports/ReportKnowledgeGraphBar.jsx]:
```suggestion
    const references = (values.references || []).map(ref => ref.value);
```
Trying to not use ramda

File: opencti-platform/opencti-front/src/private/components/cases/case_incidents/IncidentKnowledgeGraphBar.jsx [hunk 7]
```diff
@@ -303,6 +306,30 @@ class IncidentKnowledgeGraphBar extends Component {
...
 
+  closeReferencesPopup() {
+    this.setState({ referenceDialogOpened: false });
+  }
+
+  submitReference(values, { setSubmitting, resetForm }) {
+    const { handleDeleteSelected } = this.props;
+    const { deleteObject } = this.state;
+    const commitMessage = values.message;
+    const references = R.pluck('value', values.references || []);
```
Comment (lndrtrbn) [inline opencti-platform/opencti-front/src/private/components/cases/case_incidents/IncidentKnowledgeGraphBar.jsx]:
```suggestion
    const references = (values.references || []).map(ref => ref.value);
```
Trying to not use ramda

File: opencti-platform/opencti-front/src/private/components/cases/case_rfis/CaseRfiKnowledgeGraphBar.jsx [hunk 8]
```diff
@@ -306,6 +309,30 @@ class CaseRfiKnowledgeGraphBar extends Component {
...
 
+  closeReferencesPopup() {
+    this.setState({ referenceDialogOpened: false });
+  }
+
+  submitReference(values, { setSubmitting, resetForm }) {
+    const { handleDeleteSelected } = this.props;
+    const { deleteObject } = this.state;
+    const commitMessage = values.message;
+    const references = R.pluck('value', values.references || []);
```
Comment (lndrtrbn) [inline opencti-platform/opencti-front/src/private/components/cases/case_rfis/CaseRfiKnowledgeGraphBar.jsx]:
```suggestion
    const references = (values.references || []).map(ref => ref.value);
```
Trying to not use ramda

File: opencti-platform/opencti-front/src/private/components/cases/case_rfts/CaseRftKnowledgeGraphBar.jsx [hunk 9]
```diff
@@ -306,6 +309,30 @@ class CaseRftKnowledgeGraphBar extends Component {
...
 
+  closeReferencesPopup() {
+    this.setState({ referenceDialogOpened: false });
+  }
+
+  submitReference(values, { setSubmitting, resetForm }) {
+    const { handleDeleteSelected } = this.props;
+    const { deleteObject } = this.state;
+    const commitMessage = values.message;
+    const references = R.pluck('value', values.references || []);
```
Comment (lndrtrbn) [inline opencti-platform/opencti-front/src/private/components/cases/case_rfts/CaseRftKnowledgeGraphBar.jsx]:
```suggestion
    const references = (values.references || []).map(ref => ref.value);
```
Trying to not use ramda

File: opencti-platform/opencti-front/src/private/components/common/containers/ContainerStixCoreObjectPopover.jsx [hunk 10]
```diff
@@ -231,8 +263,21 @@ class ContainerStixCoreObjectPopover extends Component {
...
   }
 
+  closeReferencesPopup() {
+    this.setState({ referenceDialogOpened: false });
+  }
+
+  submitReference(values, { setSubmitting, resetForm }) {
+    const { displayRemove, displayDeleteMapping } = this.state;
+    const commitMessage = values.message;
+    const references = R.pluck('value', values.references || []);
```
Comment (lndrtrbn) [inline opencti-platform/opencti-front/src/private/components/common/containers/ContainerStixCoreObjectPopover.jsx]:
```suggestion
    const references = (values.references || []).map(ref => ref.value);
```
Trying to not use ramda

**Review by lndrtrbn — COMMENTED** [review]
You duplicate the references form a lot of times, could you extract this part in its own component?

File: opencti-platform/opencti-front/src/private/components/cases/tasks/Root.tsx [hunk 11]
```diff
@@ -70,6 +72,7 @@ const RootTaskComponent = ({ queryRef, taskId }) => {
     [taskId],
   );
   const location = useLocation();
+  const enableReferences = useIsEnforceReference('Task') && !useGranted([BYPASSREFERENCE]);
```
Comment (SarahBocognano) [inline opencti-platform/opencti-front/src/private/components/cases/tasks/Root.tsx]: Just out of curiosity : Why did you use useIsEnforceReference only on Task and Feedbacks and not on other Root components .

Comment (JeremyCloarec) [reply opencti-platform/opencti-front/src/private/components/cases/tasks/Root.tsx]: I already added useIsEnforceReference in other Root components in a previous PR, I had to add it to Task and Feedbacks also in this PR following the changes to the ContainerStixObjectsOrStixRelationships component

Comment (SarahBocognano) [reply opencti-platform/opencti-front/src/private/components/cases/tasks/Root.tsx]: Thank you ! :) 
Just a question again: I cannot set an enableReference in EntitySettings for Note/Opinion/Task. Can you explain to me why we did the change in frontend then ?

Comment (JeremyCloarec) [reply opencti-platform/opencti-front/src/private/components/cases/tasks/Root.tsx]: Good point, I didn't have that in mind when calling useInEnforceReference in Note/Opinion/Task ! In theory we could just not use it, and always set `enabledReferences` to `false` for these components. But I think that it doesn't hurt to leave it like this, this way if we decide that Note/Opinion/Task can be configured with enableReference it will work without having to change it back to use useIsEnforceReference

**Comment by SarahBocognano** [comment]
Capture d'écran 2024-06-14 120843

When I try to edit a report, I submit an external reference as required, the mutation executes but the form doesn't disappear. It stays blocked like on the screenshot

**Comment by SarahBocognano** [comment]
image

When trying to add a new entity in knowledge graph I have a validation error but the message is empty in snackbar. (Although I have it in the backend "errors":[{"attributes":{"field":"references","genre":"BUSINESS","http_status":500,"message":"You must provide at least one external reference to update"}"

**Comment by JeremyCloarec** [comment]
> image
> 
> When trying to add a new entity in knowledge graph I have a validation error but the message is empty in snackbar. (Although I have it in the backend "errors":[{"attributes":{"field":"references","genre":"BUSINESS","http_status":500,"message":"You must provide at least one external reference to update"}"

I couldn't reproduce, were your backend/frontend completely rebuilt when switching to the branch? This looks like the behavior without the modifications of the branch

**Comment by SarahBocognano** [comment]
Update: Behavior is working well for me, the only thing remaining is that the form doesn't disappear when update is selected. Need to check the updater

**Review by SarahBocognano — APPROVED** [review]
