### PR TITLE
[frontend] fix infinite loader not working within a Drawer (#4792)

### LINKED ISSUE #4792: Infinite loading is broken on create relationships since new drawer
## Description

Infinite loading is broken on create relationships since new drawer.

## Reproducible Steps

1. Go to an Intrusion Set or a Campaign
2. Go to Knowledge
3. Go to Indicator in the right menu
4. Click on "+"
5. Scroll

## Expected Output

Infinite loading is working due to parent div container correctly set.

## Actual Output

No infinite loading.

## Additional requests

When addressing this bug, please also increase a little the left padding of the checkboxes (too close to the border of the drawer):

image

### PR DESCRIPTION
**Pull request by labo-flg**
### Proposed changes

* fix padding of a list inside a drawer
* fix infinite loading inside a drawer

### Related issues

* #4792

### Checklist

- [x] I consider the submitted work as finished
- [x] I tested the code for its functionality
- [ ] I wrote test cases for the relevant uses case
- [ ] I added/update the relevant documentation (either on github or on notion)
- [ ] Where necessary I refactored code to improve the overall quality

### CODE REVIEW

File: opencti-platform/opencti-front/src/private/components/common/stix_core_relationships/StixCoreRelationshipCreationFromEntity.jsx [hunk 1]
```diff
@@ -770,14 +770,19 @@ const StixCoreRelationshipCreationFromEntity = (props) => {
         sx={{ zIndex: 1202 }}
         classes={{ paper: classes.drawerPaper }}
         onClose={handleClose}
+        SlideProps={{
+          // containerRef is forwarded to ListLinesContent so it listens to scroll events and load data with an InfiniteLoader
+          // we must target the element inside the Drawer that holds the scrolling = the Slide
+          ref: containerRef,
+        }}
```
Comment (labo-flg) [inline opencti-platform/opencti-front/src/private/components/common/stix_core_relationships/StixCoreRelationshipCreationFromEntity.jsx:777]: @Kedae this is the proper solution

MUI doc is clumsy but when you read between the lines...

**Review by Kedae — APPROVED** [review]
