### PR TITLE
[backend] fix dashboard entities list filtered by related entity (#3476)

### LINKED ISSUE #3476: Some list are broken on dashboard
## Reproducible Steps

Steps to create the smallest reproducible scenario:
1. Create a Dashboard
2. Add a list based with filters : Entity Type Report and Related Entity: Anything
3. Kaboom

## Screenshots (optional)
image
image

### PR DESCRIPTION
**Pull request by SouadHadjiat**
### Proposed changes

* add missing elementId filter key
* fix stixCoreObject findAll method : handle elementId in filters
* Minor fix : deduplicate filters types

#### To test
* Add a new widget in a dashboard with entities list, a filter on an entity type and a filter on "related entity" (try to find first a report for example with a related entity like an organization)
=> There should be no error, and you should find your report

### Related issues

* https://github.com/OpenCTI-Platform/opencti/issues/3476

### Checklist

- [x] I consider the submitted work as finished
- [x] I tested the code for its functionality
- [ ] I wrote test cases for the relevant uses case
- [ ] I added/update the relevant documentation (either on github or on notion)
- [x] Where necessary I refactored code to improve the overall quality

### CODE REVIEW

File: opencti-platform/opencti-graphql/src/domain/stixCoreObject.js [hunk 1]
```diff
@@ -72,16 +72,23 @@ export const findAll = async (context, user, args) => {
     throw UnsupportedError('Cant find stixCoreObject only based on relationship type, elementId is required');
   }
   let filters = args.filters ?? [];
-  if (isNotEmptyField(args.elementId)) {
+  const elementIds = isNotEmptyField(args.elementId) ? [args.elementId] : [];
```
Comment (Kedae) [inline opencti-platform/opencti-graphql/src/domain/stixCoreObject.js]: Not sure why we have all those changes.
The code in stixDomainObject is much simplier, can you check that either your code is too complex or stixDomainObject doesn't work as expected ?

File: opencti-platform/opencti-graphql/src/database/middleware-loader.ts [hunk 2]
```diff
@@ -368,7 +368,7 @@ export const buildEntityFilters = <T extends BasicStoreCommon>(args: EntityFilte
   }
   // endregion
   // Override some special filters
-  builtFilters.types = [...(types ?? []), ...entityTypes, ...relationshipTypes];
+  builtFilters.types = R.uniq([...(types ?? []), ...entityTypes, ...relationshipTypes]);
```
Comment (SarahBocognano) [inline opencti-platform/opencti-graphql/src/database/middleware-loader.ts:378]: Is there a way to not use Ramda ?

Comment (SarahBocognano) [reply opencti-platform/opencti-graphql/src/database/middleware-loader.ts:378]: Maybe using a new Set object

**Comment by SarahBocognano** [comment]
Tested ✅

File: opencti-platform/opencti-graphql/src/domain/stixCoreObject.js (hunk 1 above)
Comment (SouadHadjiat) [reply opencti-platform/opencti-graphql/src/domain/stixCoreObject.js]: "elementId" is sent in the filters, and it wasn't handled at all, I had to change it and this is one way I found to make it work, did you test it ?

Comment (Kedae) [reply opencti-platform/opencti-graphql/src/domain/stixCoreObject.js]: I think you missed my point. Either:

- Your code works but is too complex
- The code in src/domain/stixDomainObject doesn't work

Because the goal is the same. Can you check ?

Comment (Kedae) [reply opencti-platform/opencti-graphql/src/domain/stixCoreObject.js]: After a discussion with Julien it seems that the correct path to handle the situation is:

- Keep the existing behavior of args.elementId and args.relationship_type
- Add the support of elementId as a Filter in StixCoreObject
- Update the stixCoreObject resolver to resolve the key and provide the relationKey
- Cherry: Add a new params for elementId filter to handle the relationship_type, see with @richard-julien

Comment (SouadHadjiat) [reply opencti-platform/opencti-graphql/src/domain/stixCoreObject.js]: updated and it works with StixCoreObjectsFilter, but I didn't add the new param to handle the relationship_type

**Comment by SouadHadjiat** [comment]
PR status :
- Updated with @Kedae suggestions
- Could you test again @SarahBocognano ?

**Review by SarahBocognano — APPROVED** [review]
Tested ✅
