### PR TITLE
[backend] lazy-loading spec_version when fetching stix Refs

### LINKED ISSUE #3330: Export broken for Data components
## Environment

1. OS (where OpenCTI server runs): { e.g. Mac OS 10, Windows 10, Ubuntu 16.4, etc. }
2. OpenCTI version: 5.7
3. OpenCTI client: frontend
4. Other environment details:

## Reproducible Steps

Export a Data component containing a reference to a data source (json export)

## Expected Output

Be able to download the generated export file

## Actual Output

```
{"timestamp": "2023-05-15T12:37:12.760685Z", "level": "ERROR", "name": "pycti.api", "message": "Cannot return null for non-nullable field StixRefRelationship.spec_version."}
{"timestamp": "2023-05-15T12:37:13.652370Z", "level": "ERROR", "name": "root", "message": "Error in message processing, reporting error to API", "exc_info": "Traceback (most recent call last):\n  File \"C:\\Users\\yassi\\IdeaProjects\\client-python\\pycti\\connector\\opencti_connector_helper.py\", line 167, in _process_message\n    json_data[\"internal\"][\"work_id\"], message_task.result()\n  File \"C:\\Users\\yassi\\scoop\\apps\\python310\\current\\lib\\concurrent\\futures\\thread.py\", line 58, in run\n    result = self.fn(*self.args, **self.kwargs)\n  File \"C:\\Users\\yassi\\IdeaProjects\\connectors\\internal-export-file\\export-file-stix\\src\\export-file-stix.py\", line 103, in _process_message\n    bundle = self.helper.api_impersonate.stix2.export_list(\n  File \"C:\\Users\\yassi\\IdeaProjects\\client-python\\pycti\\utils\\opencti_stix2.py\", line 2111, in export_list\n    entity_bundle = self.prepare_export(\n  File \"C:\\Users\\yassi\\IdeaProjects\\client-python\\pycti\\utils\\opencti_stix2.py\", line 1611, in prepare_export\n    stix_nested_ref_relationships = self.opencti.stix_nested_ref_relationship.list(\n  File \"C:\\Users\\yassi\\IdeaProjects\\client-python\\pycti\\entities\\opencti_stix_nested_ref_relationship.py\", line 132, in list\n    result = self.opencti.query(\n  File \"C:\\Users\\yassi\\IdeaProjects\\client-python\\pycti\\api\\opencti_api_client.py\", line 348, in query\n    raise ValueError(\nValueError: {'name': 'Cannot return null for non-nullable field StixRefRelationship.spec_version.', 'message': 'Cannot return null for non-nullable field StixRefRelationship.spec_version.'}"
```
## Additional information

Stix requires that entites set the spec version field in relations which is not the case for Data components

### PR DESCRIPTION
**Pull request by yassine-ouaamou**
### Proposed changes

* Add a resolver for the spec_version attribute  in the Stix Ref Relationship API
* Return a default value ("2.1") for spec_version if it is not set

### Related issues

* https://github.com/OpenCTI-Platform/opencti/issues/3330
*

### Checklist

- [x] I consider the submitted work as finished
- [x] I tested the code for its functionality
- [ ] I wrote test cases for the relevant uses case
- [ ] I added/update the relevant documentation (either on github or on notion)
- [x] Where necessary I refactored code to improve the overall quality

Test cases will be included the issue of malware analysis and will consist of tests the resolver of stixRefRelationships

### Further comments

If this is a relatively large or complex change, kick off the discussion by explaining why you chose the solution you did and what alternatives you considered, etc...

### CODE REVIEW

File: opencti-platform/opencti-graphql/src/resolvers/stixRefRelationship.js [hunk 1]
```diff
@@ -44,7 +45,8 @@ const stixRefRelationshipResolvers = {
     opinions: (rel, _, context) => opinionsLoader.load(rel.id, context, context.user),
     creators: (rel, _, context) => creatorsLoader.load(rel.creator_id, context, context.user),
     editContext: (rel) => fetchEditContext(rel.id),
-    datable: (rel) => isDatable(rel.fromType, rel.relationship_type)
+    datable: (rel) => isDatable(rel.fromType, rel.relationship_type),
+    spec_version: (rel) => { return rel.spec_version ?? STIX_SPEC_VERSION; }
```
Comment (Kedae) [inline opencti-platform/opencti-graphql/src/resolvers/stixRefRelationship.js]: spec_version: ({ spec_version }) => spec_version ??  STIX_SPEC_VERSION

Comment (RomuDeuxfois) [inline opencti-platform/opencti-graphql/src/resolvers/stixRefRelationship.js]: Should we extend this behavior to SDO and SRO?

**Comment by SarahBocognano** [comment]
Tested 👍🏼

File: opencti-platform/opencti-graphql/src/resolvers/stixRefRelationship.js (hunk 1 above)
Comment (yassine-ouaamou) [reply opencti-platform/opencti-graphql/src/resolvers/stixRefRelationship.js]: We agreed to extend it to SRO (stix core and stix sighting)

File: opencti-platform/opencti-graphql/src/domain/stixSightingRelationship.js [hunk 2]
```diff
@@ -45,6 +46,9 @@ export const findById = (context, user, stixSightingRelationshipId) => {
   return storeLoadById(context, user, stixSightingRelationshipId, STIX_SIGHTING_RELATIONSHIP);
 };
 
+export function lazyLoadSpecVersion({ spec_version }) {
```
Comment (Kedae) [inline opencti-platform/opencti-graphql/src/domain/stixSightingRelationship.js]: This is not a lazyLoad function, a defaultValue one maybe.
And this is definitely not how we define function in our code. 

Finally I'm not sure there is any gain from defining that rather than just inlining it the way you used to do it

Comment (tomibennett) [reply opencti-platform/opencti-graphql/src/domain/stixSightingRelationship.js]: > This is not a lazyLoad function, a defaultValue one maybe.

I agree with you because it better describes the function internal behavior. However *lazyLoad* is the term proposed and used all along in our discussion **to describe the behavior in the system** (i.e. get rid off `spec_version` in stored relations objects and only set it for graphql responses because some our clients need it, starting with `pycti` and probably externals too), hence the *lazy* in the code. 

Do you consider this term misleading? Totally fine to change the name if it makes more sense to you.

>  And this is definitely not how we define function in our code.

It will be changed.

> Finally I'm not sure there is any gain from defining that rather than just inlining it the way you used to do it

I agree it makes little sense for a oneline method, however, I consider it a good practice as it adds lisiblity. With the function definition, I can focus on the *what* is done instead of *how* it is done. The intent is explicit and I can have a better high-level understanding of what is going on, instead of having to make sense of all the details.

Comment (Kedae) [reply opencti-platform/opencti-graphql/src/domain/stixSightingRelationship.js]: As discussed today : It seems that spec_version is missing from StixRelationship type. We need to check with @richard-julien.

In that case we need to update only the resolver/domain of stixRelationship and rename the method.

**Review by richard-julien — APPROVED** [review]
