### PR TITLE
[frontend]CSV Mapper default value for boolean field (#7116)

### LINKED ISSUE #7116: CSV Mapper default value for boolean fields are not working
## Environment
Testing 6.1.4

## Reproducible Steps

* Create a new mapper
* add representation for entity type malware
* _name_ in column A
* add a default value for _is family_

## Expected Output

Valus is set to false or true depending on the selection in the default value popup window

## Actual Output

* if you select "false" with the toggle, it does not take false as the default value
* if you select "true"  with the toggle, it does take something as default value apparently, but display is incorrect

## Screenshots (optional)

image
image
image

### PR DESCRIPTION
**Pull request by CelineSebe**
### Proposed changes
* replace default value toggle by true, false or nothing for is_family attribute configuration (Malware)
* replace "has a default value" message by a badge

### Related issues

* #7116
 
### Checklist

- [ ] I consider the submitted work as finished
- [ ] I tested the code for its functionality
- [ ] I wrote test cases for the relevant uses case (coverage and e2e)
- [ ] I added/update the relevant documentation (either on github or on notion)
- [ ] Where necessary I refactored code to improve the overall quality

### CODE REVIEW

File: opencti-platform/opencti-front/src/private/components/data/csvMapper/representations/attributes/CsvMapperRepresentationDialogOption.tsx [hunk 1]
```diff
@@ -1,23 +1,32 @@
...
   const { t_i18n } = useFormatter();
   const handleClickOpen = () => {
     setOpen(true);
   };
+  const [invisible, setInvisible] = useState(true);
+
+  useEffect(() => {
+    const hasDefaultValues = value?.default_values !== null && value?.default_values !== undefined && JSON.stringify(value.default_values) !== '[]';
+    setInvisible(!hasDefaultValues);
+  }, [value]);
```
Comment (lndrtrbn) [inline opencti-platform/opencti-front/src/private/components/data/csvMapper/representations/attributes/CsvMapperRepresentationDialogOption.tsx]: You can replace this by a useMemo to avoid using a useEffect

**Review by lndrtrbn — COMMENTED** [review]
image

In Settings > Customization, missing a label "Default value" above the buttons to be able to understand what we are setting.
Same for CSV mapper

**Comment by lndrtrbn** [comment]
image
image

On malware representation, the bullet is displayed on the name even if nothing is configure

**Comment by lndrtrbn** [comment]
When the bullet is displayed, there is an extra padding at the bottom

File: opencti-platform/opencti-front/lang/front/fr.json [hunk 2]
```diff
@@ -1036,7 +1036,7 @@
   "EXTERNAL_IMPORT": "Import de données",
   "Eye Color": "Couleur des yeux",
   "Failure": "Échec",
-  "false": "Non",
+  "false": "Faux",
```
Comment (lndrtrbn) [inline opencti-platform/opencti-front/lang/front/fr.json:1043]: The translation is also incorrect in english

File: opencti-platform/opencti-front/lang/front/en.json [hunk 3]
```diff
@@ -1040,7 +1040,7 @@
   "Eye Color": "Eye Color",
   "Failed": "Failed",
   "Failure": "Failure",
-  "false": "No",
+  "false": "false",
```
Comment (labo-flg) [inline opencti-platform/opencti-front/lang/front/en.json:1043]: This change might have more impact. the intl key "false" was maybe used elsewhere with intent on displaying "No".
If so, we should change there to intl key "No" (and same with yes/true)

Comment (lndrtrbn) [reply opencti-platform/opencti-front/lang/front/en.json:1043]: It is not used anywhere else in the app for what I can see

**Review by labo-flg — APPROVED** [review]
