### PR TITLE
[frontend] fix filters representation when filters with regardingOf (4974)

### LINKED ISSUE #5974: Display is broken when having regardingOf filter with label filter or Author
Go to entities.
Choose the "Label" filter and select a value (the label is correctly displayed).
Choose the "Regarding Of" filter and select a value.
=> The "Label" filter is displaying an ID instead.

Environment: Testing

image

### PR DESCRIPTION
**Pull request by Archidoit**
issue: https://github.com/OpenCTI-Platform/opencti/issues/5974

### CODE REVIEW

File: opencti-platform/opencti-graphql/src/utils/filtering/filtering-utils.ts [hunk 1]
```diff
@@ -101,17 +101,19 @@ export const extractFilterGroupValues = (inputFilters: FilterGroup, key: string
   }
 
   const ids = [];
-  // regardingOf key is a composite filter id+type, values are [{ key: 'id', ...}, { key: 'type', ... }]
+  // regardingOf key is a composite filter id+type, values are [{ key: 'id', ...}, { key: 'relationship_type', ... }]
```
Comment (Archidoit) [inline opencti-platform/opencti-graphql/src/utils/filtering/filtering-utils.ts]:
```suggestion
  // regardingOf key is a composite filter id+type, values are [{ key: 'id', ...}, { key: 'type', ... }]
```

**Review by jpkha — APPROVED** [review]
