### PR TITLE
[frontend] In Observable / Indicators composed with this observable view, fix the css(#9279)

### LINKED ISSUE #9279: Bad margin in 'Add indicators to observable' panel
## Reproducible Steps
- Go in an observable overview
- Click on 'indicators composed with this observable' > Add
Image

- The '+' button is too on the left and long description/name are troncated far before the end of the screen
Image

### PR DESCRIPTION
**Pull request by Gwendoline-FAVRE-FELIX**
### Proposed changes

* Correct the position of the + button and the length of the truncate

### Related issues

* https://github.com/OpenCTI-Platform/opencti/issues/9279

### CODE REVIEW

File: opencti-platform/opencti-front/src/private/components/observations/stix_cyber_observables/StixCyberObservableAddIndicators.jsx [hunk 1]
```diff
@@ -15,7 +15,6 @@ import IndicatorCreation from '../indicators/IndicatorCreation';
 const styles = (theme) => ({
   drawerPaper: {
     minHeight: '100vh',
-    width: '50%',
```
Comment (Archidoit) [inline opencti-platform/opencti-front/src/private/components/observations/stix_cyber_observables/StixCyberObservableAddIndicators.jsx]: the opened tab should be half the screen width, why did you remove this?

**Review by Archidoit — DISMISSED** [review]

**Comment by Archidoit** [comment]
the opened panel is less large than other panels (it should be half the screen width)

the panel you modified:
image


other panels: 
image

image

File: opencti-platform/opencti-front/src/private/components/common/stix_core_relationships/StixCoreRelationshipCreationFromEntityList.js [hunk 2]
```diff
@@ -392,7 +392,11 @@ const StixCoreRelationshipCreationFromEntityList = ({
                       </ListItemIcon>
                       <ListItemText
                         primary={node.name}
-                        secondary={defaultDescription(node)}
+                        secondary={
+                          <span style={{ whiteSpace: 'nowrap' }}>
+                            {defaultDescription(node)}
+                          </span>
+                        }
```
Comment (delemaf) [inline opencti-platform/opencti-front/src/private/components/common/stix_core_relationships/StixCoreRelationshipCreationFromEntityList.js]: The name and description are still overflowing:
image

You can do this with CSS easily 😃 
```suggestion
                        secondary={defaultDescription(node)}
                        sx={{
                          '.MuiListItemText-primary, .MuiListItemText-secondary': {
                            overflowX: 'hidden',
                            textOverflow: 'ellipsis',
                            whiteSpace: 'nowrap',
                            marginRight: '20px',
                          },
                        }}
```

File: opencti-platform/opencti-front/src/private/components/common/stix_core_relationships/StixCoreRelationshipCreationFromEntityList.js [hunk 3]
```diff
@@ -338,7 +338,7 @@ const StixCoreRelationshipCreationFromEntityList = ({
     data.parent_types.includes('Stix-Cyber-Observable')
       ? data.x_opencti_description
       : data.description,
-    120,
+    130,
```
Comment (delemaf) [inline opencti-platform/opencti-front/src/private/components/common/stix_core_relationships/StixCoreRelationshipCreationFromEntityList.js]: truncate could be removed if you handle this via CSS

**Review by delemaf — CHANGES_REQUESTED** [review]

**Review by delemaf — APPROVED** [review]

File: opencti-platform/opencti-front/src/private/components/observations/stix_cyber_observables/StixCyberObservableAddIndicators.jsx (hunk 1 above)
Comment (delemaf) [reply opencti-platform/opencti-front/src/private/components/observations/stix_cyber_observables/StixCyberObservableAddIndicators.jsx]: It's done 👍
