### PR TITLE
[backend](fix)Vulnerabilities: support "_" & "-" in CVSS values 

### LINKED ISSUE #11649: Vulnerabilities: support "_" & "-" in CVSS values
## Description

Currently, the implementation of CVSS does not support "_" & "-" (not in the norm), resulting in throwing errors when vulnerabilties are ingested with this values. To be clear, these "_" & "-" are in the context of CVSS data: ex "ADJACENT_NETWORK"

But it seems that some users get data source where data has these values are formated like this. Therefore, we should support this. 

## Environment

6.7.3

## Reproducible Steps

Steps to create the smallest reproducible scenario:
1. Try to ingest a vulnerability with "ADJACENT_NETWORK" OR ADJACENT-NETWORK as attack vector

## Expected Output

Vulnerability is ingested without any issue

## Actual Output

Vulnerability is not ingested an issue araise.

### PR DESCRIPTION
**Pull request by maelv-filigran**
### Proposed changes

* Add support for multiple Attack Vector input formats in CVSS vulnerability mapping
* Handle "ADJACENT_NETWORK", "ADJACENT-NETWORK", and "Adjacent Network" variations using regex pattern matching
* Ensure proper mapping to CVSS version-specific values ("Adjacent Network" for CVSS2, "Adjacent" for CVSS3/4)

### Related issues

* #11649
* Fixes issue where Attack Vector values with underscores or hyphens were not properly recognized
* Improves CVSS data import compatibility with various external sources

### Checklist

- [x] I consider the submitted work as finished
- [x] I tested the code for its functionality
- [ ] I wrote test cases for the relevant uses case (coverage and e2e)
- [ ] I added/update the relevant documentation (either on github or on notion)
- [x] Where necessary I refactored code to improve the overall quality

### Further comments

This change improves the robustness of CVSS Attack Vector parsing by accepting multiple input formats that are commonly found in vulnerability databases and security tools. The implementation uses a regex pattern `/^adjacent[\s_-]?network$/i` to match all variations while maintaining backward compatibility.

The refactoring also addresses ESLint warnings by avoiding parameter reassignment and using proper dot notation for object property access.

### CODE REVIEW

File: opencti-platform/opencti-graphql/src/utils/vulnerabilities.ts [hunk 1]
```diff
@@ -297,22 +297,38 @@ const getCodeValue = (
   const map = config.fullToCode[metric];
   if (!map) return value;
 
+  let processedValue = value;
```
Comment (Archidoit) [inline opencti-platform/opencti-graphql/src/utils/vulnerabilities.ts:300]: can you add tests for the getCodeValue function?

**Review by Archidoit — CHANGES_REQUESTED** [review]

**Review by SarahBocognano — APPROVED** [review]

File: opencti-platform/opencti-graphql/src/utils/vulnerabilities.ts (hunk 1 above)
Comment (maelv-filigran) [reply opencti-platform/opencti-graphql/src/utils/vulnerabilities.ts:300]: done :)

**Review by Archidoit — APPROVED** [review]
