### PR TITLE
[backend] Improve RabbitMQ error handling moving to callback native api (#4648)

### LINKED ISSUE #4648: Platform shutdown / crash on RabbitMQ exception (not catched)
## Description

Seen in Slack but also in our cloud environments.

The following exception:
```
Error: write ECONNRESET
    at afterWriteDispatched (node:internal/stream_base_commons:160:15)
    at writeGeneric (node:internal/stream_base_commons:151:3)
    at Socket._writeGeneric (node:net:952:11)
    at Socket._write (node:net:964:8)
    at writeOrBuffer (node:internal/streams/writable:447:12)
    at _write (node:internal/streams/writable:389:10)
    at Socket.Writable.write (node:internal/streams/writable:393:10)
    at roundrobin (/opt/opencti/build/node_modules/amqplib/lib/mux.js:59:25)
    at Wye._readIncoming (/opt/opencti/build/node_modules/amqplib/lib/mux.js:65:3)
    at Immediate._onImmediate (/opt/opencti/build/node_modules/amqplib/lib/mux.js:95:12)
    at processImmediate (node:internal/timers:478:21)
```

leads to crash completely the NodeJS process without proper catching.

New in 5.11.

### PR DESCRIPTION
**Pull request by richard-julien**

### CODE REVIEW

File: opencti-platform/opencti-graphql/src/connector/importCsv/importCsv-connector.ts [hunk 1]
```diff
@@ -112,14 +109,9 @@ const initImportCsvConnector = () => {
...
-      logApp.info(`[OPENCTI-MODULE] Starting ${connectorConfig.name} manager`);
-
       const context = executionContext(connectorConfig.id.toLowerCase());
-      // Register connector queues if not exists
-      const cbError = async (error: any) => {
-        if (error) await registerConnectorQueues(connector.id, connector.name, connector.connector_type, connector.connector_scope);
-      };
-      await existsConnectorQueues(connector.id, cbError);
+      logApp.info(`[OPENCTI-MODULE] Starting ${connectorConfig.name} manager`);
+      await registerConnectorQueues(connector.id, connector.name, connector.connector_type, connector.connector_scope);
```
Comment (RomuDeuxfois) [inline opencti-platform/opencti-graphql/src/connector/importCsv/importCsv-connector.ts:114]: I didn't understand that you could call this method even if the queue was already present

File: opencti-platform/opencti-graphql/src/database/rabbitmq.js [hunk 2]
```diff
@@ -51,29 +52,51 @@ export const config = () => {
...
+  const connOptions = USE_SSL ? {
+    ...amqpCred(),
+    ...configureCA(RABBITMQ_CA),
+    cert: RABBITMQ_CA_CERT,
+    key: RABBITMQ_CA_KEY,
+    pfx: RABBITMQ_CA_PFX,
+    passphrase: RABBITMQ_CA_PASSPHRASE,
+    rejectUnauthorized: RABBITMQ_REJECT_UNAUTHORIZED,
+  } : amqpCred();
+  return new Promise((resolve, reject) => {
```
Comment (RomuDeuxfois) [inline opencti-platform/opencti-graphql/src/database/rabbitmq.js:64]: it seems to be much safer in terms of error handling

**Comment by RomuDeuxfois** [comment]
Tests on my existing rabbit then on a new rabbit with two connectors: import csv and import-file-stix
Everything works fine on these test cases
