### PR TITLE
[backend] fix taxii cursor number error (#8675)

### LINKED ISSUE #8675: [OPENCTI-MODULE] INGESTION - Error with taxii handler CISA-GOV - Atribute Must be a string
## Description

I am trying to set up a TAXII Ingester for a CISA-AIS Taxii Feed . After I input the necessary information and the taxii ID I am getting a Validation error 

## Environment

1. OS : Ubuntu
2. OpenCTI version: OpenCTI 6.3.5
3. OpenCTI client: frontend

## Reproducible Steps

Steps to create the smallest reproducible scenario:
1. Set up TAXII Feed from CISA-AIS

## Expected Output

Receive threat intel ingestion

## Actual Output

No works registered , no messages in RabbitMQ queues . 

`
```
{
  "category": "APP",
  "level": "error",
  "message": "[OPENCTI-MODULE] INGESTION - Error with taxii handler CISA-GOV",
  "source": "backend",
  "timestamp": "2024-10-15T12:44:04.409Z",
  "version": "6.3.5"
}

{
  "category": "APP",
  "context": "Taxii ingestion execution",
  "errors": [
    {
      "attributes": {
        "field": "current_state_cursor",
        "genre": "BUSINESS",
        "http_status": 500
      },
      "message": "Attribute must be a string",
      "name": "VALIDATION_ERROR",
      "stack": "
    GraphQLError: Attribute must be a string\n    at error (/opt/opencti/build/src/config/errors.js:7:10)\n    at ValidationError (/opt/opencti/build/src/config/errors.js:129:58)\n    at validateAndFormatSchemaAttribute (/opt/opencti/build/src/schema/schema-validator.ts:46:15)\n    at /opt/opencti/build/src/schema/schema-validator.ts:98:7\n    at Array.forEach (<anonymous>)\n    at fn (/opt/opencti/build/src/schema/schema-validator.ts:96:16)\n    at telemetry (/opt/opencti/build/src/config/tracing.ts:109:12)\n    at validateFormatSchemaAttributes (/opt/opencti/build/src/schema/schema-validator.ts:101:10)\n    at fn (/opt/opencti/build/src/schema/schema-validator.ts:230:11)\n    at telemetry (/opt/opencti/build/src/config/tracing.ts:109:12)\n    at validateInputUpdate (/opt/opencti/build/src/schema/schema-validator.ts:245:10)\n    at updateAttribute (/opt/opencti/build/src/database/middleware.js:2225:9)\n    at patchTaxiiIngestion (/opt/opencti/build/src/modules/ingestion/ingestion-taxii-domain.ts:51:19)\n    at processTaxiiResponse (/opt/opencti/build/src/manager/ingestionManager.ts:332:31)\n    at taxiiV21DataHandler (/opt/opencti/build/src/manager/ingestionManager.ts:362:3)\n    at async Promise.all (index 0)\n    at async Promise.all (index 1)\n    at ingestionHandler (/opt/opencti/build/src/manager/ingestionManager.ts:478:5)\n    at /opt/opencti/build/src/manager/ingestionManager.ts:499:9\n    at Ynt.#runHandlerAndScheduleTimeout (/opt/opencti/build/node_modules/set-interval-async/dist/set-interval-async-timer.cjs:36:13)\n    at Timeout._onTimeout (/opt/opencti/build/node_modules/set-interval-async/dist/set-interval-async-timer.cjs:29:13)"
    }
  ],
  "level": "error",
  "message": "Attribute must be a string",
  "name": "CISA-GOV",
  "source": "backend",
  "timestamp": "2024-10-15T12:44:04.409Z",
  "version": "6.3.5"
}
```
`

### PR DESCRIPTION
**Pull request by aHenryJard**
### Proposed changes

* Force taxii cursor to be a string before saving in database.

### Related issues

* closes #8675 

### Checklist

- [x] I consider the submitted work as finished
- [x] I tested the code for its functionality
- [x] I wrote test cases for the relevant uses case (coverage and e2e)
- [x] I added/update the relevant documentation (either on github or on notion)
- [x] Where necessary I refactored code to improve the overall quality

### CODE REVIEW

File: opencti-platform/opencti-graphql/src/modules/ingestion/ingestion-taxii-domain.ts [hunk 1]
```diff
@@ -47,8 +48,18 @@ export const addIngestion = async (context: AuthContext, user: AuthUser, input:
   return element;
 };
 
-export const patchTaxiiIngestion = async (context: AuthContext, user: AuthUser, id: string, patch: object) => {
-  const patched = await patchAttribute(context, user, id, ENTITY_TYPE_INGESTION_TAXII, patch);
+export interface TaxiiIngestionPatch {
+  current_state_cursor?: string | undefined,
+  last_execution_date?: string,
+  added_after_start?: Moment,
```
Comment (aHenryJard) [inline opencti-platform/opencti-graphql/src/modules/ingestion/ingestion-taxii-domain.ts:54]: Not sure why but in ingestionManager it's a Moment.

Comment (SouadHadjiat) [reply opencti-platform/opencti-graphql/src/modules/ingestion/ingestion-taxii-domain.ts:54]: you're right, we use a Moment object when updating the date, but in BasicStoreEntityIngestionTaxii, added_after_start is a Date

Comment (aHenryJard) [reply opencti-platform/opencti-graphql/src/modules/ingestion/ingestion-taxii-domain.ts:54]: @SouadHadjiat so you think it should be a Date here ?

**Review by SouadHadjiat — APPROVED** [review]
