### PR TITLE
[backend] on Artifact creation pass mime_type to upload (#7486)(#7434)

### LINKED ISSUE #7434: Bad .docx file upload at artifact creation
## Description
If you create an artifact with a .docx file, the file name and extensions are changed, leading to errors.

## Reproducible Steps
- Create an artifact by selecting a .docx file : 
image

- The artifact is created but the file name is incorrect and always 'Content_Types.xml'
image

- In the Data tab of the created artifact, the file name and extension are not correct and the import failed
image

### LINKED ISSUE #7486: MIME type in uploaded artifacts is not correct and lead to multiple errors
## Description

1. Take an exe file, rename it without extension:
[calc-exe.zip](https://github.com/user-attachments/files/15986379/calc-exe.zip)

2. Upload it in the artifact section

3. Result:

MIME Type of the artifact is correct:

image

MIME Type of the associated file is always "text/plain":

image

## Other example with the connector

Correct MIME Type here:
image

Incorrect in the associated file:
image

### PR DESCRIPTION
**Pull request by labo-flg**
### Proposed changes

when creating artifact, we have the MIME type. We simply pass it down to the upload function as option ; if defined we use otherwise we try to guess it.

### Related issues

closes #7486
closes [7434](https://github.com/OpenCTI-Platform/opencti/issues/7434)

### CODE REVIEW

File: opencti-platform/opencti-graphql/src/database/file-storage.js [hunk 1]
```diff
@@ -407,7 +407,7 @@ export const upload = async (context, user, filePath, fileUpload, opts) => {
 
   // Upload the data
   const readStream = createReadStream();
-  const fileMime = guessMimeType(key);
+  const fileMime = mime_type ?? guessMimeType(key);
```
Comment (labo-flg) [inline opencti-platform/opencti-graphql/src/database/file-storage.js]: I did not change the behavior of guessMimeType ; it still returns plain/text by defaut.
Do we want to get rid of this too ?
What happens if there is no MIME type given and guess is impossible (maybe that's a dumb too theoretical question)

Comment (SamuelHassine) [reply opencti-platform/opencti-graphql/src/database/file-storage.js]: I think we can still try to guess and fallback but the fallback should be application/octet-stream rather than text/plain, what do you think?

File: opencti-platform/opencti-graphql/src/database/file-storage.js [hunk 2]
```diff
@@ -385,7 +385,7 @@ export const uploadJobImport = async (context, user, fileId, fileMime, entityId,
 
 // Please consider using file-storage-helper#uploadToStorage() instead.
 export const upload = async (context, user, filePath, fileUpload, opts) => {
-  const { entity, meta = {}, noTriggerImport = false, errorOnExisting = false, file_markings = [], importContextEntities = [] } = opts;
+  const { entity, meta = {}, noTriggerImport = false, errorOnExisting = false, file_markings = [], importContextEntities = [], mime_type } = opts;
```
Comment (Kedae) [inline opencti-platform/opencti-graphql/src/database/file-storage.js]: I would have put the mime_type in the metaData personnaly, but that's a detail

File: opencti-platform/opencti-graphql/src/database/file-storage.js (hunk 1 above)
Comment (Kedae) [reply opencti-platform/opencti-graphql/src/database/file-storage.js]: That would make more sens as a plain text generally have a file extension

File: opencti-platform/opencti-graphql/src/database/file-storage.js (hunk 2 above)
Comment (labo-flg) [reply opencti-platform/opencti-graphql/src/database/file-storage.js]: metas are then saved in db, that's a change in model

File: opencti-platform/opencti-graphql/src/database/file-storage.js (hunk 1 above)
Comment (labo-flg) [reply opencti-platform/opencti-graphql/src/database/file-storage.js]: ok !

**Comment by labo-flg** [comment]
@aHenryJard found another issue ; I'm putting back to draft

**Comment by aHenryJard** [comment]
All good for me now, tested locally with connector malwarebaazar

File: opencti-platform/opencti-graphql/src/database/file-storage.js [hunk 3]
```diff
@@ -247,15 +247,16 @@ export const loadFile = async (user, fileS3Path, opts = {}) => {
...
       id: fileS3Path,
-      name: getFileName(fileS3Path),
+      name: onlyFilename,
       size: object.ContentLength,
       information: '',
       lastModified: object.LastModified,
       lastModifiedSinceMin: sinceNowInMinutes(object.LastModified),
       uploadStatus: 'complete',
-      metaData: { mimetype: mimeTypeResolved },
+      metaData: { mimetype: mimeTypeResolved, filename: onlyFilename },
```
Comment (aHenryJard) [inline opencti-platform/opencti-graphql/src/database/file-storage.js]: this `filename` is required at least by the download as encrypted archive feature.

File: opencti-platform/opencti-graphql/src/database/file-storage.js [hunk 4]
```diff
@@ -247,15 +247,16 @@ export const loadFile = async (user, fileS3Path, opts = {}) => {
       Key: fileS3Path
     }));
     const mimeTypeResolved = guessMimeType(fileS3Path);
```
Comment (SouadHadjiat) [inline opencti-platform/opencti-graphql/src/database/file-storage.js]: we still only guess the mimeType here

File: opencti-platform/opencti-graphql/src/database/file-storage.js [hunk 5]
```diff
@@ -237,25 +237,91 @@ export const storeFileConverter = (user, file) => {
...
+      lastModified = fileInformationFromDB.lastModified;
+      lastModifiedSinceMin = lastModified; // ??
+    } else {
+      // Else try to get them from S3 instead
+      const object = await s3Client.send(new s3.HeadObjectCommand({
+        Bucket: bucketName,
+        Key: fileS3Path
+      }));
+      metaData = {
+        version: object.Metadata.version,
```
Comment (SouadHadjiat) [inline opencti-platform/opencti-graphql/src/database/file-storage.js]: not sure this would work, since we don't store Metadata anymore in S3, or is it just a fallback for previously stored files ? I wonder if object.Metadata would be defined for new files.

**Review by Kedae — APPROVED** [review]
