### PR TITLE
[frontend] fix attack patterns details with not "empty" signs "-" (#7869)

### LINKED ISSUE #7869: Attack patterns details not compliant with "empty" signs "-"
## Description

image

=> All empty sections should be with the empty component "-".

### PR DESCRIPTION
**Pull request by CelineSebe**
### Proposed changes

* add ternary 

### Related issues

* #7869 

### Checklist

- [ ] I consider the submitted work as finished
- [ ] I tested the code for its functionality
- [ ] I wrote test cases for the relevant uses case (coverage and e2e)
- [ ] I added/update the relevant documentation (either on github or on notion)
- [ ] Where necessary I refactored code to improve the overall quality

### CODE REVIEW

File: opencti-platform/opencti-front/src/private/components/techniques/attack_patterns/AttackPatternCoursesOfAction.jsx [hunk 1]
```diff
@@ -70,40 +70,43 @@ class AttackPatternCoursesOfActionComponent extends Component {
...
+                      size="large"
+                    >
+                      <LinkOff/>
+                    </IconButton>
+                  </ListItemSecondaryAction>
+                </ListItem>
+              );
+            })}
+          </List>
+          : ('-')
```
Comment (Archidoit) [inline opencti-platform/opencti-front/src/private/components/techniques/attack_patterns/AttackPatternCoursesOfAction.jsx]: use the FieldOrEmpty component instead of a ternary

File: opencti-platform/opencti-front/src/private/components/techniques/attack_patterns/AttackPatternDataComponents.tsx [hunk 2]
```diff
@@ -99,7 +99,8 @@ const AttackPatternDataComponentsComponent: FunctionComponent<{
               );
             })}
         </List>
-      )}
+        : ('-')
```
Comment (Archidoit) [inline opencti-platform/opencti-front/src/private/components/techniques/attack_patterns/AttackPatternDataComponents.tsx]: same

File: opencti-platform/opencti-front/src/private/components/techniques/attack_patterns/AttackPatternDetails.jsx [hunk 3]
```diff
@@ -76,18 +76,21 @@ class AttackPatternDetailsComponent extends Component {
...
-                          <SettingsApplications />
-                        </ListItemIcon>
-                        <ListItemText primary={platform} />
-                      </ListItem>
-                    ),
-                  )}
-                </List>
+                {attackPattern.length > 0
+                  ? <List>
+                    {propOr([], 'x_mitre_platforms', attackPattern).map(
```
Comment (Archidoit) [inline opencti-platform/opencti-front/src/private/components/techniques/attack_patterns/AttackPatternDetails.jsx]:
```suggestion
                    {(attackPattern?.x_mitre_platforms ?? []).map(
```

File: opencti-platform/opencti-front/src/private/components/techniques/attack_patterns/AttackPatternDetails.jsx [hunk 4]
```diff
@@ -76,18 +76,21 @@ class AttackPatternDetailsComponent extends Component {
...
+                        <ListItem key={platform} dense={true} divider={true}>
+                          <ListItemIcon>
+                            <SettingsApplications/>
+                          </ListItemIcon>
+                          <ListItemText primary={platform}/>
+                        </ListItem>
+                      ),
+                    )}
+                  </List>
+                  : ('-')
```
Comment (Archidoit) [inline opencti-platform/opencti-front/src/private/components/techniques/attack_patterns/AttackPatternDetails.jsx]: same

**Comment by Archidoit** [comment]
Too much space before the '-' for Course of Action, Data Components, and Sub attack patterns  (compare with space before '-' of Platforms for instance):
image

**Comment by Archidoit** [comment]
If empty, external ID should be '-', not a blue space 

image

File: opencti-platform/opencti-front/src/private/components/techniques/attack_patterns/AttackPatternDetails.jsx [hunk 5]
```diff
@@ -114,18 +117,21 @@ class AttackPatternDetailsComponent extends Component {
...
+                      <ListItem key={permission} dense={true} divider={true}>
+                        <ListItemIcon>
+                          <PermIdentity/>
+                        </ListItemIcon>
+                        <ListItemText primary={permission}/>
+                      </ListItem>
+                    ),
+                  )}
+                </List>
+                : ('-')
```
Comment (Archidoit) [inline opencti-platform/opencti-front/src/private/components/techniques/attack_patterns/AttackPatternDetails.jsx]: same

**Review by Archidoit — CHANGES_REQUESTED** [review]

**Comment by CelineSebe** [comment]
@Archidoit Every change has been addressed

File: opencti-platform/opencti-front/src/private/components/techniques/attack_patterns/AttackPatternDetails.jsx [hunk 6]
```diff
@@ -76,17 +79,19 @@ class AttackPatternDetailsComponent extends Component {
...
-                      <ListItem key={platform} dense={true} divider={true}>
-                        <ListItemIcon>
-                          <SettingsApplications />
-                        </ListItemIcon>
-                        <ListItemText primary={platform} />
-                      </ListItem>
-                    ),
-                  )}
+                <List style={{ paddingTop: 0 }}>
+                  <FieldOrEmpty source={attackPattern.attackPattern}>
```
Comment (Archidoit) [inline opencti-platform/opencti-front/src/private/components/techniques/attack_patterns/AttackPatternDetails.jsx]:
```suggestion
                  <FieldOrEmpty source={attackPattern.x_mitre_platforms}>
```

File: opencti-platform/opencti-front/src/private/components/techniques/attack_patterns/AttackPatternDetails.jsx [hunk 7]
```diff
@@ -76,17 +79,19 @@ class AttackPatternDetailsComponent extends Component {
...
+                    {(attackPattern?.x_mitre_platforms || []).map(
```
Comment (Archidoit) [inline opencti-platform/opencti-front/src/private/components/techniques/attack_patterns/AttackPatternDetails.jsx]:
```suggestion
                    {attackPattern.x_mitre_platforms.map(
```

File: opencti-platform/opencti-front/src/private/components/techniques/attack_patterns/AttackPatternDetails.jsx [hunk 8]
```diff
@@ -114,17 +119,19 @@ class AttackPatternDetailsComponent extends Component {
...
-                    <ListItem key={permission} dense={true} divider={true}>
-                      <ListItemIcon>
-                        <PermIdentity />
-                      </ListItemIcon>
-                      <ListItemText primary={permission} />
-                    </ListItem>
-                  ),
-                )}
+              <List style={{ paddingTop: 0 }}>
+                <FieldOrEmpty source={attackPattern.attackPattern}>
```
Comment (Archidoit) [inline opencti-platform/opencti-front/src/private/components/techniques/attack_patterns/AttackPatternDetails.jsx]:
```suggestion
                <FieldOrEmpty source={attackPattern.x_mitre_permissions_required}>
```

File: opencti-platform/opencti-front/src/private/components/techniques/attack_patterns/AttackPatternDetails.jsx [hunk 9]
```diff
@@ -114,17 +119,19 @@ class AttackPatternDetailsComponent extends Component {
...
+                  {propOr([], 'x_mitre_permissions_required', attackPattern).map(
```
Comment (Archidoit) [inline opencti-platform/opencti-front/src/private/components/techniques/attack_patterns/AttackPatternDetails.jsx]: remove ramda

**Review by Archidoit — CHANGES_REQUESTED** [review]

File: opencti-platform/opencti-front/src/private/components/techniques/attack_patterns/AttackPatternDetails.jsx [hunk 10]
```diff
@@ -76,17 +79,19 @@ class AttackPatternDetailsComponent extends Component {
...
-                        <ListItemIcon>
-                          <SettingsApplications />
-                        </ListItemIcon>
-                        <ListItemText primary={platform} />
-                      </ListItem>
-                    ),
-                  )}
+                <List style={{ paddingTop: 0 }}>
+                  <FieldOrEmpty source={attackPattern.x_mitre_platforms}>
+                    {(attackPattern.x_mitre_platforms).map(
```
Comment (Archidoit) [inline opencti-platform/opencti-front/src/private/components/techniques/attack_patterns/AttackPatternDetails.jsx]:
```suggestion
                    {attackPattern.x_mitre_platforms?.map(
```

**Review by Archidoit — APPROVED** [review]
