### PR TITLE
[backend] add new capability 'Bypass mandatory fields' (#3304)

### LINKED ISSUE #3304: Create a new capa to byPass mandatory fields
## Problem to Solve

So I found something interesting. If I try to enforce mandatory attributes for the Report entity, it breaks the MITRE Datasets connector. If it breaks MITRE, it likely breaks other connectors handling it.
image

The reason a user may want to enforce mandatory attributes on that, is to prevent users from improperly filling out the details for the Report entity.

The error I started getting from the worker logs was:
`2023-05-09T22:04:58.235430037Z ERROR:pycti.api:Invalid field createdBy`
`2023-05-09T22:04:58.235457637Z ERROR:root:{'name': 'ValidationError', 'message': 'Invalid field createdBy'}`
`2023-05-09T22:04:58.263740311Z ERROR:pycti.api:[SEARCH] Error updating elastic (update)`
`2023-05-09T22:04:58.263763511Z ERROR:pycti.api:Cannot report expectation`

The error pointed to something going wrong with the Author entity or createdBy field.
image

The end result is that reports might still get output but certain entities or relationships getting excluded from the Report container.

I believe this error might be caused when certain fields in the STIX bundles have a null createdBy field, leading to that data getting excluded upon matching the mandatory attributes rules. 

## Current Workaround

To resolve this issue, undoing the enforcement of mandatory attributes on the Report entity causes the problem to go away.

But this means the user becomes unable to make use of the enforce mandatory attributes feature, because it breaks the connectors that handle the Report entity.

## Proposed Solution

I believe a sound, interim solution would be to add a new permission that can be added to the Connector Role, that would allow the connector to bypass mandatory field attributes.
image

A longer term solution I think should be considered is adopting the concept of internal service users (these handle all backend OpenCTI operations) and regular users. This is because often times, what we want to happen for a front end user is different from the service user (connector).

## Final approach
Create a new capa called "Bypass mandatory fields" that would allow admins to enable some custom mandatory attributes so that their connectors for instance will be able to byPass any fields that are marked as required, while analyst will be have to comply with the filling of the needed fields when creating or updating an entity.

### PR DESCRIPTION
**Pull request by frapuks**
### Proposed changes

- add new capa (initialisation + migration)
- bypass schema validation in create and update entity
- migration of schema-validation-test to typescript + add test coverage on bypass.
- Doc : https://github.com/OpenCTI-Platform/docs/pull/189

### Related issues

- close #3304 

### Checklist

- [x] I consider the submitted work as finished
- [x] I tested the code for its functionality
- [x] I wrote test cases for the relevant uses case (coverage and e2e)
- [ ] I added/update the relevant documentation (either on github or on notion)
- [ ] Where necessary I refactored code to improve the overall quality

### CODE REVIEW

File: opencti-platform/opencti-graphql/src/modules/entitySetting/entitySetting-attributeUtils.ts [hunk 1]
```diff
@@ -123,5 +124,8 @@ export const getMandatoryAttributesForSetting = async (
   entitySetting: BasicStoreEntityEntitySetting
 ) => {
   const attributes = await getEntitySettingSchemaAttributes(context, user, entitySetting);
+  if (isUserHasCapability(user, KNOWLEDGE_KNUPDATE_KNBYPASSFIELDS)) {
```
Comment (Kedae) [inline opencti-platform/opencti-graphql/src/modules/entitySetting/entitySetting-attributeUtils.ts:127]: Might be missing something but I don't think this is a good way of handling this as you will "lose" the fact that the attribute is mandatory.

I mean, having the capability the bypass them is interesting, having no clue they indeed should be mandatory is another.

Comment (frapuks) [reply opencti-platform/opencti-graphql/src/modules/entitySetting/entitySetting-attributeUtils.ts:127]: Currently, we simply return a list of attribute names: `[‘name’, ‘description’ ]`. And in the Front end, we try to match these names with the fields in the form.
You can return all the mandatory attributes and filter in the front-end. We didn't opt for this solution when we were brainstorming, because in front-end, you can always do what you want and work around it manually. And if you don't use the front end to create the entity, the validation has to be in the back end.

Comment (lndrtrbn) [reply opencti-platform/opencti-graphql/src/modules/entitySetting/entitySetting-attributeUtils.ts:127]: I have same point of view as @Kedae here. 

We have an API `EntitySetting.mandatoryAttributes` in graphql that is returning which are the required attributes for an entity type. No matter you have the bypass capability or not, those fields stay required. This solution makes the result of this API inconsistent depending of your capabilities and could lead to misunderstanding or issues depending on how the community is using this API.

Moreover, this `getMandatoryAttributesForSetting` function is also used in the middleware to prevent deleting a relationship attached to required stuff. I have the feeling that could lead to issues also here?

---

> in front-end, you can always do what you want and work around it manually

Even with this solution you can still do what you want and inspect code to remove front validation.

> And if you don't use the front end to create the entity, the validation has to be in the back end.

Don't you already done it in `schema-validator.ts`? Because this `getMandatoryAttributesForSetting` function is not about validating inputs so I don't get it. For what I understand you have already done the check on configured required attributes in `schema-validator.ts` so you cannot fake the API no matter what, we good on this point. 

It's just the way to handle those required attributes in UI that, in my opinion, need to be done in frontend based on capabilities and not on the result of this `EntitySetting.mandatoryAttributes` API.

**Comment by ParamConstructor** [comment]
May be some value in looking at the new opencti-platform/opencti-front/src/utils/hooks/useSchemaAttributes.tsx for compatability in https://github.com/OpenCTI-Platform/opencti/pull/6972 that we are proposing for validation of required fields handling and "*"'ing the fields on the forms UI.

File: opencti-platform/opencti-graphql/src/modules/entitySetting/entitySetting-attributeUtils.ts (hunk 1 above)
Comment (frapuks) [reply opencti-platform/opencti-graphql/src/modules/entitySetting/entitySetting-attributeUtils.ts:127]: I can't find any cases where the ‘deleteRelationsByFromAndTo’ method is triggered with customisable mandatory attributes.

Comment (lndrtrbn) [reply opencti-platform/opencti-graphql/src/modules/entitySetting/entitySetting-attributeUtils.ts:127]: Acceptable solution. Will be changed later if necessary

**Review by lndrtrbn — APPROVED** [review]
