### PR TITLE
[frontend/backend] Improve usage of Tasks (#3382)

### LINKED ISSUE #3382: Improve usage of Tasks
- [x] Add a simple page for Tasks (get the same template as Note page with simple information => without external references)
- [x] Add task list in Case menu
- [x] Overview of Incident Response & Request for Takedown: 
    - [x] Add the missing "Share to organization" button
    - [x] Replace the “Incidents & Alerts” list by “Origin of the case” list containing related `Incidents`, `Sightings`, `Report`.
    - [x] “+” button to quickly add a Report too
- [x] Overview of Request for Information: Replace the “Incidents & Alerts” list by “Origin of the case” list containing related `Report`.
    - [x] Add the missing "Share to organization" button
    - [x] +” button to quickly add a Report too
- [x] Overview: Modification of the Tasks’ list:
    - [x] Task list “expanded” on the full width (like Notes below)
    - [x] Be able to sort by “status” and “due date”
    - [x] Be able to click on a Task to view its details
    - [x] ~~Be able to filter or search a Task by “assignee”~~
    - [x] Display “due date” in red if overdue
- [x] Knowledge: set the Timeline view as the default view

--- 
Update of 09/06:
- [x] List when no item of task in case is broken
- [x] Update of task seems broken
- [x] Revoked to be removed from task
- [x] Sort by assignee should sort by name
- [x] Resolver.jsx needs to be removed ?
- [x] Update of Localization
- [x] Align date chip with indicator, see with Samuel
- [x] List CSS to check with Adrien

### PR DESCRIPTION
**Pull request by SarahBocognano**
### Proposed changes

* Add a task container component in cases overview. 
* Be able to access the overview of a case
* Be able to sort by assignee, dueDate and status
* DueDate Red when overdue
* Case Task list page (to see all tasks)

### Related issues

* https://github.com/OpenCTI-Platform/opencti/issues/3382

### Checklist

- [x] I consider the submitted work as finished
- [x] I tested the code for its functionality
- [x] I wrote test cases for the relevant uses case
- [x] I added/update the relevant documentation (either on github or on notion)
- [x] Where necessary I refactored code to improve the overall quality

### Further comments

If this is a relatively large or complex change, kick off the discussion by explaining why you chose the solution you did and what alternatives you considered, etc...

### CODE REVIEW

**Comment by Archidoit** [comment]
- In case tasks list: alignement problem
image

- missing this button in the overview of a case task
image

- toolbar design issue in case tasks list
image

- in case tasks list, there is an 'status' column but we can't modify the status of a case task in its update form
image

- in case tasks overview: empty fields should be '-'
image

_______________________________________________________________________________________________________________________________________


@Archidoit Thanks for your feedback, everything is solved. (the workflow update is working on my side, have you enable the workflows in entity settings config ?)

**Comment by RomuDeuxfois** [comment]
Functionnal questions :
- Is not possible to create a task from a task template ? (in the case task menu) -> No, you can only create a task template in the task template section. 
- We don't have a pencil button to edit a task (in a task detail) ? ✅ (button add)
- The issue say : whithout external references, but we have it in detail panel ✅ (component removed)
image
- We can create a task but not use it in Case incident or others case entities ? -> You can add a task to the container of your choice with the toolbar (add to container) when in Case Tasks Lines
- We don't have an overview of the link between a task and the case entity ? I don't understand that question

Bugs found :
- We can't edit the author field (in task edition) ✅ (done)
- We can't hidde the task menu from the global parameter ✅ (was working already)
- Is possible to link any entity for “Origin of the case” ✅ (need to ask @Jipegien about that behaviour as it's already the case in the demo)
- The sorting in task list (inside incent response for example or direclty in task list) is not taking care of empty field (we do in Report list) ✅ (done)
- We can customize workflow for task but not use it ✅ (was already working)
- When we create a task, the creator is not fill (not sure to understand perfectly this behavior) ✅ (done)

**Comment by SarahBocognano** [comment]
Update: All comments have been responded and/or reworked

**Comment by Jipegien** [comment]
"Replace the “Incidents & Alerts” list by “Origin of the case” list containing related Incidents, Sightings, Report."

---> "origin of the Case" should contain only report, Incident and Sighting, so only Report, Incident and Sighting should be allowed to be added.

File: opencti-platform/opencti-graphql/src/database/engine.js [hunk 1]
```diff
@@ -704,6 +704,32 @@ export const RUNTIME_ATTRIBUTES = {
       return R.mergeAll(identities.map((i) => ({ [i.internal_id]: i.definition })));
     },
   },
+  assigneeTo: {
```
Comment (RomuDeuxfois) [inline opencti-platform/opencti-graphql/src/database/engine.js:717]: Can you explain me the usage of this ?
Thank you :)

File: opencti-platform/opencti-front/src/private/components/cases/case_task/TasksLine.tsx [hunk 2]
```diff
@@ -0,0 +1,310 @@
...
+      <ListItemIcon
+        classes={{ root: classes.itemIconDisabled }}
+        style={{ minWidth: 40 }}
+      >
+        <Checkbox edge="start" disabled={true} disableRipple={true} />
+      </ListItemIcon>
+      <ListItemIcon classes={{ root: classes.itemIcon }}>
+        <Skeleton animation="wave" variant="circular" width={30} height={30} />
+      </ListItemIcon>
+      <ListItemText
```
Comment (RomuDeuxfois) [inline opencti-platform/opencti-front/src/private/components/cases/case_task/TasksLine.tsx]: You can loop on your taskDataColumns
Something like

```
<ListItemText
        primary={
          <div>
            {Object.values(tasksDataColumns).map((value) => (
              <div
                key={value.label}
                className={classes.bodyItem}
                style={{ width: value.width }}
              >
                <Skeleton
                  animation="wave"
                  variant="rectangular"
                  width="90%"
                 height="100%
                />
              </div>
            ))}
          </div>
        }
      />
```

File: opencti-platform/opencti-front/src/private/components/cases/case_task/TasksEditionOverview.tsx [hunk 3]
```diff
@@ -0,0 +1,337 @@
...
+        commitMessage: commitMessage && commitMessage.length > 0 ? commitMessage : null,
+      },
+      onCompleted: () => {
+        setSubmitting(false);
+        handleClose();
+      },
+    });
+  };
+
+  const handleSubmitField = (name: string, value: Option | string | string[] | number | number[] | null) => {
```
Comment (RomuDeuxfois) [inline opencti-platform/opencti-front/src/private/components/cases/case_task/TasksEditionOverview.tsx]: Is not possible to use editor.changeField ?

File: opencti-platform/opencti-front/src/private/components/cases/case_task/TasksEditionContainer.tsx [hunk 4]
```diff
@@ -0,0 +1,100 @@
...
+    backgroundColor: theme.palette.background.nav,
+    padding: '20px 20px 20px 60px',
+  },
+  closeButton: {
+    position: 'absolute',
+    top: 12,
+    left: 5,
+    color: 'inherit',
+  },
+  importButton: {
```
Comment (RomuDeuxfois) [inline opencti-platform/opencti-front/src/private/components/cases/case_task/TasksEditionContainer.tsx]: This class is not used

File: opencti-platform/opencti-front/src/private/components/cases/case_task/TasksEditionContainer.tsx [hunk 5]
```diff
@@ -0,0 +1,100 @@
...
+    position: 'absolute',
+    top: 15,
+    right: 20,
+  },
+  container: {
+    padding: '10px 20px 20px 20px',
+  },
+  appBar: {
```
Comment (RomuDeuxfois) [inline opencti-platform/opencti-front/src/private/components/cases/case_task/TasksEditionContainer.tsx]: This class is not used

File: opencti-platform/opencti-front/src/private/components/cases/case_task/TaskCreation.tsx [hunk 6]
```diff
@@ -0,0 +1,311 @@
...
+    backgroundColor: theme.palette.background.nav,
+    padding: '20px 20px 20px 60px',
+  },
+  closeButton: {
+    position: 'absolute',
+    top: 12,
+    left: 5,
+    color: 'inherit',
+  },
+  importButton: {
```
Comment (RomuDeuxfois) [inline opencti-platform/opencti-front/src/private/components/cases/case_task/TaskCreation.tsx]: Not used

File: opencti-platform/opencti-front/src/private/components/cases/case_task/TaskCreation.tsx [hunk 7]
```diff
@@ -0,0 +1,311 @@
...
+    position: 'absolute',
+    top: 15,
+    right: 20,
+  },
+  container: {
+    padding: '10px 20px 20px 20px',
+  },
+  icon: {
```
Comment (RomuDeuxfois) [inline opencti-platform/opencti-front/src/private/components/cases/case_task/TaskCreation.tsx]: Not used

File: opencti-platform/opencti-front/src/private/components/cases/case_task/TaskCreation.tsx [hunk 8]
```diff
@@ -0,0 +1,311 @@
...
+    paddingTop: 4,
+    display: 'inline-block',
+    color: theme.palette.primary.main,
+  },
+  text: {
```
Comment (RomuDeuxfois) [inline opencti-platform/opencti-front/src/private/components/cases/case_task/TaskCreation.tsx]: Not used

File: opencti-platform/opencti-front/src/private/components/cases/case_task/TaskCreation.tsx [hunk 9]
```diff
@@ -0,0 +1,311 @@
...
+    display: 'inline-block',
+    flexGrow: 1,
+    marginLeft: 10,
+  },
+  autoCompleteIndicator: {
```
Comment (RomuDeuxfois) [inline opencti-platform/opencti-front/src/private/components/cases/case_task/TaskCreation.tsx]: Not used

File: opencti-platform/opencti-front/src/components/list_lines/ListLines.jsx [hunk 10]
```diff
@@ -191,42 +191,44 @@ class ListLines extends Component {
...
-                  <div style={{ float: 'left', marginRight: 20 }}>
-                    <SearchInput
-                      variant={searchVariant || 'small'}
-                      onSubmit={handleSearch.bind(this)}
-                      keyword={keyword}
-                    />
-                  </div>
-                )}
-                {extraFields}
+              {!this.props.inline && (
```
Comment (RomuDeuxfois) [inline opencti-platform/opencti-front/src/components/list_lines/ListLines.jsx:197]: Why we have this changes ?

File: opencti-platform/opencti-graphql/src/database/engine.js (hunk 1 above)
Comment (SarahBocognano) [reply opencti-platform/opencti-graphql/src/database/engine.js:717]: We were not able to order by assignee until now, so it's for the ordering :)

File: opencti-platform/opencti-front/src/components/list_lines/ListLines.jsx (hunk 10 above)
Comment (SarahBocognano) [reply opencti-platform/opencti-front/src/components/list_lines/ListLines.jsx:197]: Because it's the first time we use ListLines nested in an other component (ex: task in incident response) and we were having the bottom horizontal scrollbar appearing, and it was awfull. It's a way to counter that original behavior

File: opencti-platform/opencti-front/src/private/components/cases/case_task/TasksEditionOverview.tsx (hunk 3 above)
Comment (SarahBocognano) [reply opencti-platform/opencti-front/src/private/components/cases/case_task/TasksEditionOverview.tsx]: ✅ done

**Comment by SarahBocognano** [comment]
Update: All comments have been responded/reworked.

I link a bug issue with this one : https://github.com/OpenCTI-Platform/opencti/issues/3515

**Comment by RomuDeuxfois** [comment]
Tests :
- The bug on duplicate entity still appears ✅ 
- This behavior is cross-platform, we can create an issue to handle it ?
image
- Still possible to link any entity on "ORIGIN OF THE CASE"

Questions :
- ~~will it be possible to pivot from a task to a case ?~~

---
@Kedae : The issue of add button is well known and we have choosen to do nothing for now (Cathia saw it several months ago).
It's normal that you can link any entity, we don't want to enforce filters on that panel : If user want to do crazy stuff, let him do it. But, the list is correctly filtered and the item will be added in the correct list in the screen "Other Entities" after reload

**Comment by helene-nguyen** [comment]
Functionnal part:

- Task is not sorted immediately and we need to click the button again to sort it, is it possible to do it? -> @Kedae actually not, it's a limitation we have currently. We can discuss it if you want.

task_pr-1

- When sorting by "Due Date", tasks disappear if a due date is missing -> @Kedae Same, it's a behavior we have a LOT in the app, we need to be consistent about it everywhere.

task_pr-2

- When update a task (on task page), lost all changes made because clicking on the cross not update the task. Is it because it acts like "cancel" and not "updating task done" ? -> @Kedae Actually it's because by clicking on the cross you have not triggered the "onChange" event of the field as the event has been catch by the button.

task_pr-7

- On all case tasks page, we cannot search for a matching single character (example with a number) and searching with searchbar acting weird -> @SarahBocognano If you go to the overview of the filtered task, you will see your keyword in the description slot. It's "approximative" search for now, it's not done by name of the task.

task_pr-5

- On all case tasks page or a single task details page, we don't know that the task belongs to a specific incident response -> @Kedae : as seen with @Jipegien we don't care for now 

task_pr-6

- We cannot change the status nor update it and when sort by status, all tasks disappear (on all case tasks page) -> @Kedae You need to allow status in settings > customization. We can discuss it if you want.

task_pr-9

**Comment by yassine-ouaamou** [comment]
I don't think it is part of the PR but when I try to create an incident response, the title of the creation view is "Create a case incident"

Edit: This will fixed by Sam in another branch

**Comment by yassine-ouaamou** [comment]
When adding tasks to a case template, I have some issues:
- Once the first task added, the others are not taken into account when added
- The update (case template) screen is not synchronized with the content of the list of the tasks


https://github.com/OpenCTI-Platform/opencti/assets/7083405/bbbada21-fd11-42b7-a823-5d63216a1bdd


https://github.com/OpenCTI-Platform/opencti/assets/7083405/01a6ba98-4c5d-42c5-bdc5-dec1a715da13

Also, when applying a case template on an incident response, the task list is not updated until I refresh the page
