### PR TITLE
[backend] Fix the file change right

### LINKED ISSUE #5435: Impossible to see a file uploaded if we are not part of the platform organization
## Description

When I upload a file in the platform (from the global import panel or from a "Data" tab of an entity), the file isn't appear if I am not part of the platform organization.

## Environment

OCTI 5.12.15

## Reproducible Steps

Steps to create the smallest reproducible scenario:
1. Set up user A admin and part of Org A
2. Set up user B normal user and part of Org B
3. Set up Org A as platform organization
4. Create a Report with User B and upload a file from the "Data" tab of the Report
5. Try to see this file from User B (you can't), then from User A (you can)

The screenshot below illustrates this

## Expected Output

I should see the file with User B

## Screenshots

- On the left, my view from User A part of the platform organization and admin
- On the right, my view from User B (not admin), who create the report and upload the file

Screenshot 2024-01-09 092509

### PR DESCRIPTION
**Pull request by Kedae**
Closes #5435

### CODE REVIEW

File: opencti-platform/opencti-graphql/src/modules/internal/document/document-domain.ts [hunk 1]
```diff
@@ -119,12 +121,36 @@ export const allRemainingFilesCount = async (context: AuthContext, user: AuthUse
...
+    throw ForbiddenAccess('Access to this file is restricted', { id: entity_id, file: id });
+  }
+  return true;
+};
+
 // Get Files paginated with auto enrichment
 // Images metadata for users
 // In progress virtual files from export
-export const paginatedForPathsWithEnrichment = async (context: AuthContext, user: AuthUser, paths: string[], opts?: FilesOptions<BasicStoreEntityDocument>) => {
+export const paginatedForPathsWithEnrichment = async (context: AuthContext, user: AuthUser, path: string, entity_id: string, opts?: FilesOptions<BasicStoreEntityDocument>) => {
```
Comment (SouadHadjiat) [inline opencti-platform/opencti-graphql/src/modules/internal/document/document-domain.ts]: if it's now singular "path" instead of "paths", maybe we can rename the method too ? **paginatedForPathWithEnrichment** or **paginatedFilesWithEnrichment** so it's not dependent on the parameters

File: opencti-platform/opencti-graphql/src/modules/internal/document/document-domain.ts [hunk 2]
```diff
@@ -133,15 +159,14 @@ export const paginatedForPathsWithEnrichment = async (context: AuthContext, user
     orderOptions.orderMode = OrderingMode.Desc;
   }
   const listOptions = { ...opts, ...findOpts, ...orderOptions };
-  const pagination = await listEntitiesPaginated<BasicStoreEntityDocument>(context, user, [ENTITY_TYPE_INTERNAL_FILE], listOptions);
+
+  await checkFileAccess(context, user, entity_id, { entity_id, id: path, filename: '' });
```
Comment (SouadHadjiat) [inline opencti-platform/opencti-graphql/src/modules/internal/document/document-domain.ts]: the third parameter of `checkFileAccess` is `scope` and here it's set with `entity_id`, doesn't seem right, no ?

Comment (Kedae) [reply opencti-platform/opencti-graphql/src/modules/internal/document/document-domain.ts]: Well, it's the scope for the "UserAction" log, so I think it's a good call to have the entity_id to tell "User A tried to access files of this specific entity and cannot". But I'm open to other thoughts

Comment (SouadHadjiat) [reply opencti-platform/opencti-graphql/src/modules/internal/document/document-domain.ts]: scopes should be a limited list of operations I think, but I don't know well the activity logging part. I can see this graph in a user activity analytics which is a distribution based on scope : 

image

It might not help to have ids in scope

Comment (Kedae) [reply opencti-platform/opencti-graphql/src/modules/internal/document/document-domain.ts]: You're completely right, my bad I'll change that :)

Comment (SouadHadjiat) [reply opencti-platform/opencti-graphql/src/modules/internal/document/document-domain.ts]: it's even defined in UserActionListener, all `event_scope` are typed with specific values

**Comment by SouadHadjiat** [comment]
There is an issue here : I can see all analyst workbenches in a report (I should see only the report analyst workbenches, none here)
I can't reproduce the issue on testing platform.

image

File: opencti-platform/opencti-graphql/src/resolvers/stixCoreObject.js [hunk 3]
```diff
@@ -120,13 +120,13 @@ const stixCoreObjectResolvers = {
     connectors: (stixCoreObject, { onlyAlive = false }, context) => connectorsForEnrichment(context, context.user, stixCoreObject.entity_type, onlyAlive),
     importFiles: (stixCoreObject, { first, prefixMimeType }, context) => {
       const opts = { first, prefixMimeTypes: prefixMimeType ? [prefixMimeType] : null, entity_id: stixCoreObject.id };
-      return paginatedForPathsWithEnrichment(context, context.user, [`import/${stixCoreObject.entity_type}/${stixCoreObject.id}`], opts);
+      return paginatedForPathWithEnrichment(context, context.user, `import/${stixCoreObject.entity_type}/${stixCoreObject.id}`, stixCoreObject.id, opts);
     },
     pendingFiles: (stixCoreObject, { first }, context) => {
-      return paginatedForPathsWithEnrichment(context, context.user, ['import/pending'], { first, entity_id: stixCoreObject.id });
+      return paginatedForPathWithEnrichment(context, context.user, 'import/pending', stixCoreObject.id, { first });
```
Comment (SouadHadjiat) [inline opencti-platform/opencti-graphql/src/resolvers/stixCoreObject.js:126]: if the entity_id is not part of the options, it won't be used as a filter to list only files linked to this entity_id

**Review by SouadHadjiat — CHANGES_REQUESTED** [review]
Fix analyst workbench list displayed in an entity data tab (should be filtered by entity, it displays all analyst workbenches)

File: opencti-platform/opencti-graphql/src/modules/internal/document/document-domain.ts [hunk 4]
```diff
@@ -119,29 +121,52 @@ export const allRemainingFilesCount = async (context: AuthContext, user: AuthUse
...
+    throw ForbiddenAccess('Access to this file is restricted', { id: entity_id, file: id });
+  }
+  return true;
+};
+
 // Get Files paginated with auto enrichment
 // Images metadata for users
 // In progress virtual files from export
-export const paginatedForPathsWithEnrichment = async (context: AuthContext, user: AuthUser, paths: string[], opts?: FilesOptions<BasicStoreEntityDocument>) => {
+export const paginatedForPathWithEnrichment = async (context: AuthContext, user: AuthUser, path: string, entity_id: string, opts?: FilesOptions<BasicStoreEntityDocument>) => {
```
Comment (SouadHadjiat) [inline opencti-platform/opencti-graphql/src/modules/internal/document/document-domain.ts:151]: I don't really understand why `entity_id` has been extracted from opts as a separate parameter knowing that `FilesOptions` type still has `entity_id`. Why not keep entity_id inside opts and extract in the method ?

Comment (Kedae) [reply opencti-platform/opencti-graphql/src/modules/internal/document/document-domain.ts:151]: It's a bit of semantic actually. We want to enforce that entity_id is a *important* prop from this function to get files and not just some stuff you can add in opts.
I understand your concern, we've discussed that with Julien and thougth it would be more explicit that way

**Review by SouadHadjiat — APPROVED** [review]
Tested locally and it seem to work well ✅
