### PR TITLE
[backend/frontend] Fix playbook organization sharing schema (#8767)

### LINKED ISSUE #8767: Having a large number of Organizations slows down the playbooks
## Description

When the platform ingests many many organizations, for instance through a feed like ransomware.live, it slows down the platform performances.

It might be due to the way we handle organizations in the platform, according to organization sharing (caching, playbooks on orga sharing).

## Environment

OCTI 6.3.6

### PR DESCRIPTION
**Pull request by SouadHadjiat**
### Proposed changes

* don't return anymore all organizations list and use ObjectOrganizationField component
* implement a resolver to parse organizations that have been already saved with only the id (we need the label)
* query organizations by id instead of using the cache

### Related issues

* #8767 

### Checklist

- [x] I consider the submitted work as finished
- [x] I tested the code for its functionality
- [ ] I wrote test cases for the relevant uses case (coverage and e2e)
- [ ] I added/update the relevant documentation (either on github or on notion)
- [ ] Where necessary I refactored code to improve the overall quality

### CODE REVIEW

File: opencti-platform/opencti-front/src/private/components/data/playbooks/PlaybookAddComponents.jsx [hunk 1]
```diff
@@ -458,6 +459,18 @@ const PlaybookAddComponentsContent = ({
                       />
                     );
                   }
+                  if (k === 'organizations') {
+                    return (
+                      <ObjectOrganizationField
+                        key={k}
+                        name="organizations"
+                        style={{ marginTop: 20, width: '100%' }}
+                        label={'Target organizations'}
```
Comment (aHenryJard) [inline opencti-platform/opencti-front/src/private/components/data/playbooks/PlaybookAddComponents.jsx:468]: There is no i18n needed here ?

Comment (SouadHadjiat) [reply opencti-platform/opencti-front/src/private/components/data/playbooks/PlaybookAddComponents.jsx:468]: nothing is translated in playbook components for now, so I didn't work on it in this fix. you can see just above the same thing for authorized members field with label "Targets"

**Review by aHenryJard — APPROVED** [review]
Tested playbook with orga sharing locally, everything works as expected.
