### PR TITLE
[backend] Fix relations types mapping(#4177)

### LINKED ISSUE #4177: Relation between Infrastructure and STIX Cyber Observable is broken in frontend
## Description

Observations => Infrastructure => Knowledge => Observables

The relation "consists-of" should be available for all observables:

```
  [`${ENTITY_TYPE_INFRASTRUCTURE}_${ABSTRACT_STIX_CYBER_OBSERVABLE}`]: [
    { name: RELATION_CONSISTS_OF, type: REL_BUILT_IN }
  ],
```

### PR DESCRIPTION
**Pull request by marieflorescontact**
### Proposed changes

* Fix relations types mapping in `schemaRelationsTypesMapping` => relations were created for entity-type to` stix-cyber-observables` but not for ` stix-cyber-observables children` . Some relationship types where missing.
* Add a method to check if a type hasChildren
* Add a test to check if the mapping is ok (no dupplicates and merged attributes)

### Related issues

* [issue/4177](https://github.com/OpenCTI-Platform/opencti/issues/4177)

### Checklist

- [x] I consider the submitted work as finished
- [x] I tested the code for its functionality
- [x] I wrote test cases for the relevant uses case
- [ ] I added/update the relevant documentation (either on github or on notion)
- [x] Where necessary I refactored code to improve the overall quality

### Further comments

If this is a relatively large or complex change, kick off the discussion by explaining why you chose the solution you did and what alternatives you considered, etc...

### CODE REVIEW

File: opencti-platform/opencti-graphql/tests/01-unit/database/modelConsistency-test.js [hunk 1]
```diff
@@ -466,3 +467,15 @@ describe('Testing stix ref extractor', () => {
     expect(refs.includes('marking-definition--34098fce-860f-48ae-8e50-ebd3cc5e41da')).toBe(true);
   });
 });
+
+describe('Test if needed', () => {
```
Comment (Archidoit) [inline opencti-platform/opencti-graphql/tests/01-unit/database/modelConsistency-test.js]: it's not really a clear name for a describe

File: opencti-platform/opencti-graphql/tests/01-unit/database/modelConsistency-test.js [hunk 2]
```diff
@@ -466,3 +467,15 @@ describe('Testing stix ref extractor', () => {
...
+  it('Mapping', () => {
```
Comment (Archidoit) [inline opencti-platform/opencti-graphql/tests/01-unit/database/modelConsistency-test.js]: maybe rather : it('Relations mapping') or it('Relations should map')

**Comment by Archidoit** [comment]
Behavior working well 👍

File: opencti-platform/opencti-graphql/tests/01-unit/database/modelConsistency-test.js (hunk 1 above)
Comment (marieflorescontact) [reply opencti-platform/opencti-graphql/tests/01-unit/database/modelConsistency-test.js]: oups ...totally forgot 😇

File: opencti-platform/opencti-graphql/tests/01-unit/database/modelConsistency-test.js (hunk 2 above)
Comment (marieflorescontact) [reply opencti-platform/opencti-graphql/tests/01-unit/database/modelConsistency-test.js]: same 😇

**Comment by marieflorescontact** [comment]
All previous comment have been taken in account. PR ready for more review.

**Review by yassine-ouaamou — APPROVED** [review]
