### PR TITLE
[frontend] Fix filtering on indicator types and observable types

### LINKED ISSUE #3219: Filtering on indicator types is not working anymore
## Description

Filtering on indicator types is not working anymore.

1. Observation => Indicators
2. Click on a checkbox on right like "YARA"

Output : filter is not applied.

### PR DESCRIPTION
**Pull request by RomuDeuxfois**
### Related issues

* [issues 3219](https://github.com/OpenCTI-Platform/opencti/issues/3219)

### CODE REVIEW

File: opencti-platform/opencti-front/src/private/components/observations/Indicators.tsx [hunk 1]
```diff
@@ -89,28 +64,27 @@ const Indicators = () => {
...
   const handleToggleObservableType = (type: string) => {
-    if (observableTypes.includes(type)) {
-      setObservableTypes(observableTypes.filter(
-        (t) => t !== type,
-      ));
+    if (observableType.map((t) => t.id)?.includes(type)) {
+      storageHelpers.handleRemoveFilter('x_opencti_main_observable_type', type);
     } else {
-      setObservableTypes(R.append(type, observableTypes));
+      storageHelpers.handleAddFilter('x_opencti_main_observable_type', type, type);
```
Comment (SarahBocognano) [inline opencti-platform/opencti-front/src/private/components/observations/Indicators.tsx:82]: " ('x_openci_main_observable_type, type, type) " -> It's a lot of type ^^

**Review by SarahBocognano — APPROVED** [review]
