### PR TITLE
[front] Report/Entities inside creation is not consistent and can lead to several problems

### LINKED ISSUE #2902: Report/Entities inside creation is not consistent and can lead to several problems
## Description

Whenever we add a case from a report entities, it doesn't create the case and it does crash if you try to click it.

## Environment

2. OpenCTI version: 5.5.4

## Reproducible Steps

Steps to create the smallest reproducible scenario:
1. Go to a Report/Entities
2. **Create a new case from here** and add the Case to the report.
3. Select the case that has been created (Error: An unknown error occurred. Please contact your administrator or the OpenCTI maintainers.)
4. Go Cases, Incident response, the case won't show either.  
## Screenshots (optional)
From the Demo instance: 
image

### PR DESCRIPTION
**Pull request by richard-julien**
Global refactoring to use the real form screen for the choosen entity.

### CODE REVIEW

File: opencti-platform/opencti-front/src/private/components/analysis/groupings/GroupingCreation.js [hunk 1]
```diff
@@ -86,6 +86,10 @@ const useStyles = makeStyles((theme) => ({
 const groupingMutation = graphql`
   mutation GroupingCreationMutation($input: GroupingAddInput!) {
     groupingAdd(input: $input) {
+      id
```
Comment (RomuDeuxfois) [inline opencti-platform/opencti-front/src/private/components/analysis/groupings/GroupingCreation.js:90]: Why we need to add this lines on fragment creation ?

File: opencti-platform/opencti-front/src/private/components/common/stix_domain_objects/StixDomainObjectCreation.js [hunk 2]
```diff
@@ -269,379 +115,278 @@ const sharedUpdater = (
...
 
-  handleOpen() {
-    this.setState({ open: true });
-  }
+const StixDomainPanel = ({ queryRef, stixDomainObjectTypes, onClose, creationUpdater,
+  confidence, defaultCreatedBy, defaultMarkingDefinitions }) => {
+  const { t } = useFormatter();
+  const queryData = usePreloadedQuery(stixDomainObjectCreationAllTypesQuery, queryRef);
+  const availableEntityTypes = buildEntityTypes(t, queryData, stixDomainObjectTypes);
+  const [status, setStatus] = useState(availableEntityTypes.at(0).value);
```
Comment (RomuDeuxfois) [inline opencti-platform/opencti-front/src/private/components/common/stix_domain_objects/StixDomainObjectCreation.js]: Why this property is status ? It could be clearer to name it entity no ?

File: opencti-platform/opencti-front/src/private/components/common/stix_domain_objects/StixDomainObjectCreation.js [hunk 3]
```diff
@@ -269,379 +115,278 @@ const sharedUpdater = (
...
+      return <ToolCreationForm defaultConfidence={confidence}
+          defaultCreatedBy={baseCreatedBy} defaultMarkingDefinitions={baseMarkingDefinitions}
+          onReset={onClose} updater={creationUpdater}/>;
+    }
+    if (status === 'Vulnerability') { // Vulnerability
+      return <VulnerabilityCreationForm defaultConfidence={confidence}
+          defaultCreatedBy={baseCreatedBy} defaultMarkingDefinitions={baseMarkingDefinitions}
+          onReset={onClose} updater={creationUpdater}/>;
+    }
+    return <div>{t('Unsupported')}</div>;
```
Comment (RomuDeuxfois) [inline opencti-platform/opencti-front/src/private/components/common/stix_domain_objects/StixDomainObjectCreation.js:551]: Miss I18n

File: opencti-platform/opencti-front/src/private/components/common/stix_domain_objects/StixDomainObjectCreation.js [hunk 4]
```diff
@@ -1,45 +1,48 @@
-import React, { Component } from 'react';
-import * as PropTypes from 'prop-types';
-import { Field, Form, Formik } from 'formik';
-import { ConnectionHandler } from 'relay-runtime';
+import React, { useState } from 'react';
```
Comment (RomuDeuxfois) [inline opencti-platform/opencti-front/src/private/components/common/stix_domain_objects/StixDomainObjectCreation.js:1]: This mechanism are really great !

File: opencti-platform/opencti-front/src/private/components/common/stix_domain_objects/StixDomainObjectCreation.js [hunk 5]
```diff
@@ -54,7 +57,11 @@ export const stixDomainObjectCreationAllTypesQuery = graphql`
   }
 `;
 
-const styles = (theme) => ({
+const UNSUPPORTED_TYPES = ['Language', 'Note', 'Opinion']; // Language as no ui, note and opinion are not useful
+const IDENTITY_ENTITIES = ['Sector', 'Organization', 'Individual', 'System', 'Event'];
+const LOCATION_ENTITIES = ['Region', 'Country', 'City', 'Location'];
```
Comment (marieflorescontact) [inline opencti-platform/opencti-front/src/private/components/common/stix_domain_objects/StixDomainObjectCreation.js]: 'Area' is missing

**Comment by marieflorescontact** [comment]
Bugs found : 

-  Can't creat a grouping, got this error for a confidence set to none:
Capture d'écran_20230222_152146

-  When creating a report from the graph ('Reports' > 'Knowledge' > graph view >  '+' > 'create an entity' > select 'report' > fill the form > 'create' ) the panel doesn't close when clicking on 'Create' button, but the report is yet created.

File: opencti-platform/opencti-front/src/private/components/analysis/groupings/GroupingCreation.js (hunk 1 above)
Comment (SamuelHassine) [reply opencti-platform/opencti-front/src/private/components/analysis/groupings/GroupingCreation.js:90]: We need this because then node is added in the list, id is required for checkboxes / selection management.

File: opencti-platform/opencti-front/src/private/components/common/stix_domain_objects/StixDomainObjectCreation.js (hunk 2 above)
Comment (SamuelHassine) [reply opencti-platform/opencti-front/src/private/components/common/stix_domain_objects/StixDomainObjectCreation.js]: Fixed

File: opencti-platform/opencti-front/src/private/components/common/stix_domain_objects/StixDomainObjectCreation.js (hunk 3 above)
Comment (SamuelHassine) [reply opencti-platform/opencti-front/src/private/components/common/stix_domain_objects/StixDomainObjectCreation.js:551]: Fixed

File: opencti-platform/opencti-front/src/private/components/common/stix_domain_objects/StixDomainObjectCreation.js (hunk 5 above)
Comment (SamuelHassine) [reply opencti-platform/opencti-front/src/private/components/common/stix_domain_objects/StixDomainObjectCreation.js]: Fixed

**Comment by SamuelHassine** [comment]
> Bugs found :
> 
> * Can't creat a grouping, got this error for a confidence set to none:
>   Capture d'écran_20230222_152146
> * When creating a report from the graph ('Reports' > 'Knowledge' > graph view >  '+' > 'create an entity' > select 'report' > fill the form > 'create' ) the panel doesn't close when clicking on 'Create' button, but the report is yet created.

Fixed

**Review by SamuelHassine — APPROVED** [review]
