### PR TITLE
[frontend] fix relationship_type filter list (#5995)

### LINKED ISSUE #5995: remove not stix core relationship types in Data>Relationship filter
## Description

Filtering on Sighted in/at is broken, it returns nothing. Dashboards and API are broken as well

```
/dashboard/data/relationships?filters={"filterGroups":[],"filters":[{"id":"a2d8ed3f-c917-4a07-a8fd-dadaa6da9697","key":"relationship_type","values":["stix-sighting-relationship"],"operator":"eq","mode":"or"}],"mode":"or"}&sortBy=created_at&orderAsc=false
```

## Environment

1. OS (where OpenCTI server runs): CentOS Stream 9
2. OpenCTI version: 5.12.29
3. OpenCTI client: Frontend
4. Other environment details: Clustered

## Reproducible Steps

Steps to create the smallest reproducible scenario:
1. Visit /dashboard/data/relationships?filters={"filterGroups":[],"filters":[{"id":"a2d8ed3f-c917-4a07-a8fd-dadaa6da9697","key":"relationship_type","values":["stix-sighting-relationship"],"operator":"eq","mode":"or"}],"mode":"or"}&sortBy=created_at&orderAsc=false
2. get an empty `edges`

## Expected Output

The Sighted in/at SROs being returned reliably 

## Actual Output

```
{
    "data": {
        "stixCoreRelationships": {
            "edges": [],
            "pageInfo": {
                "endCursor": "",
                "hasNextPage": false,
                "globalCount": 0
            }
        }
    }
}
```

## Additional information

N/A - Was working on 5.12.25 - @SamuelHassine @richard-julien this is a long running trend, any way y'all can implement testing this is a headache to keep hitting these filter bugs every-other release

### PR DESCRIPTION
**Pull request by Archidoit**
issue: https://github.com/OpenCTI-Platform/opencti/issues/5995

### CODE REVIEW

File: opencti-platform/opencti-front/src/utils/filters/useSearchEntities.tsx [hunk 1]
```diff
@@ -960,6 +960,14 @@ const useSearchEntities = ({
             }))
             .sort((a, b) => a.label.localeCompare(b.label));
           unionSetEntities(filterKey, relationshipsTypes);
+        } else if (searchContext.entityTypes.length === 1 && searchContext.entityTypes[0] === 'stix-core-relationship') {
+          const relationshipsTypes = (schema.scrs ?? [])
+            .map((n) => ({
+              label: t_i18n(`relationship_${n.label}`),
+              value: n.label,
+              type: n.label,
+            }));
```
Comment (labo-flg) [inline opencti-platform/opencti-front/src/utils/filters/useSearchEntities.tsx]: missing the `.sort((a, b) => a.label.localeCompare(b.label));` as in other if clauses ?

Comment (Archidoit) [reply opencti-platform/opencti-front/src/utils/filters/useSearchEntities.tsx]: fix

**Review by labo-flg — APPROVED** [review]
