### PR TITLE
[backend] fix entities without internal_id (#10172)

### LINKED ISSUE #10172: Platform crashes when accessing a report
## Description

Platform crashes when accessing a report

https://testing.octi.staging.filigran.io/dashboard/analyses/reports/1bcdabe3-1aa7-402b-9285-c95ed8a71d1a

Cannot read properties of undefined (reading 'toString')

```
{"category":"APP","cause":{"attributes":{},"message":"Cannot read properties of undefined (reading 'toString')","name":"GraphQLError","stack":"TypeError: Cannot read properties of undefined (reading 'toString')\n    at buildLocalMustFilter (/opt/opencti/build/back.js:1866:16695)\n    at buildSubQueryForFilterGroup (/opt/opencti/build/back.js:1866:19300)\n    at buildSubQueryForFilterGroup (/opt/opencti/build/back.js:1866:18991)\n    at elQueryBodyBuilder (/opt/opencti/build/back.js:1866:33603)\n    at processTicksAndRejections (node:internal/process/task_queues:105:5)\n    at elPaginate (/opt/opencti/build/back.js:1866:43819)"},"level":"error","message":"Cannot read properties of undefined (reading 'toString')","operation":"Unspecified","operation_query":"query RootReportQuery($id:String!){report(id:$id){id standard_id entity_type name currentUserAccessRight ...Report_report ...ReportDetails_report ...ReportKnowledge_report ...ContainerHeader_container ...ContainerStixDomainObjects_container ...ContainerStixCyberObservables_container ...StixCoreObjectContent_stixCoreObject ...FileImportViewer_entity ...FileExportViewer_entity ...FileExternalReferencesViewer_entity ...WorkbenchFileViewer_entity}connectorsForExport{...StixCoreObjectFilesAndHistory_connectorsExport id}connectorsForImport{...StixCoreObjectFilesAndHistory_connectorsImport id}}fragment ContainerHeader_container on Container{__isContainer:__typename id draftVersion{draft_id draft_operation}entity_type standard_id confidence created creators{id name entity_type}filesFromTemplate(first:500){edges{node{id name objectMarking{id representative{main}}}}}fintelTemplates{id name}currentUserAccessRight authorized_members{id name entity_type access_right}...on Report{name}...on Grouping{name}...on Case{__isCase:__typename name}...on Feedback{name}...on Task{name}...on CaseIncident{name}...on CaseRfi{name}...on CaseRft{name}...on Note{attribute_abstract content}...on Opinion{opinion}...on ObservedData{name first_observed last_observed}createdBy{__typename id}objectMarking{id definition_type definition x_opencti_order x_opencti_color}}fragment ContainerStixCyberObservables_container on Container{__isContainer:__typename id ...on Report{name}...on Grouping{name}...on Note{attribute_abstract content}...on Opinion{opinion}...on ObservedData{name first_observed last_observed}...ContainerHeader_container objects{edges{types node{__typename ...on BasicObject{__isBasicObject:__typename id}...on AdministrativeArea{id}...on Artifact{id}...on AttackPattern{id}...on AutonomousSystem{id}...on BankAccount{id}...on Campaign{id}...on CaseIncident{id}...on CaseRfi{id}...on CaseRft{id}...on CaseTemplate{id}...on Channel{id}...on City{id}...on Country{id}...on CourseOfAction{id}...on Credential{id}...on CryptocurrencyWallet{id}...on CryptographicKey{id}...on CsvMapper{id}...on DataComponent{id}...on DataSource{id}...on Directory{id}...on DomainName{id}...on EmailAddr{id}...on EmailMessage{id}...on EmailMimePartType{id}...on EntitySetting{id}...on Event{id}...on ExternalReference{id}...on Feedback{id}...on Grouping{id}...on Hostname{id}...on IPv4Addr{id}...on IPv6Addr{id}...on Incident{id}...on Indicator{id}...on Individual{id}...on Infrastructure{id}...on IntrusionSet{id}...on KillChainPhase{id}...on Label{id}...on Language{id}...on MacAddr{id}...on Malware{id}...on MalwareAnalysis{id}...on ManagerConfiguration{id}...on MarkingDefinition{id}...on MediaContent{id}...on Mutex{id}...on Narrative{id}...on NetworkTraffic{id}...on Note{id}...on ObservedData{id}...on Opinion{id}...on Organization{id}...on PaymentCard{id}...on Persona{id}...on PhoneNumber{id}...on Position{id}...on Process{id}...on PublicDashboard{id}...on Region{id}...on Report{id}...on Sector{id}...on Software{id}...on StixCoreRelationship{id}...on StixFile{id}...on StixRefRelationship{id}...on StixSightingRelationship{id}...on System{id}...on Task{id}...on Text{id}...on ThreatActorGroup{id}...on ThreatActorIndividual{id}...on Tool{id}...on TrackingNumber{id}...on Url{id}...on UserAccount{id}...on UserAgent{id}...on Vulnerability{id}...on WindowsRegistryKey{id}...on WindowsRegistryValueType{id}...on Workspace{id}...on X509Certificate{id}}}}}fragment ContainerStixDomainObjectLine_node on StixDomainObject{__isStixDomainObject:__typename id draftVersion{draft_id draft_operation}standard_id entity_type parent_types created_at ...on AttackPattern{name x_mitre_id}...on Campaign{name}...on CourseOfAction{name}...on ObservedData{name}...on Report{name}...on Grouping{name}...on Note{attribute_abstract content}...on Opinion{opinion}...on Individual{name}...on Organization{name}...on Sector{name}...on System{name}...on Indicator{name}...on Infrastructure{name}...on IntrusionSet{name}...on Position{name}...on City{name}...on AdministrativeArea{name}...on Country{name}...on Region{name}...on Malware{name}...on MalwareAnalysis{result_name}...on ThreatActor{__isThreatActor:__typename name}...on Tool{name}...on Vulnerability{name}...on Incident{name}...on Event{name}...on Channel{name}...on Narrative{name}...on Language{name}...on DataComponent{name}...on DataSource{name}...on Case{__isCase:__typename name}...on Task{name}objectLabel{id value color}createdBy{__typename __isIdentity:__typename id name entity_type}objectMarking{id definition_type definition x_opencti_order x_opencti_color}containersNumber{total}}fragment ContainerStixDomainObjects_container on Container{__isContainer:__typename id ...on Report{name}...on Grouping{name}...on Note{attribute_abstract content}...on Opinion{opinion}...on ObservedData{name first_observed last_observed}...ContainerHeader_container objects{edges{types node{__typename ...on BasicObject{__isBasicObject:__typename id}...ContainerStixDomainObj...","size":45,"source":"backend","time":201,"timestamp":"2025-03-07T10:23:00.527Z","type":"READ_ERROR","user":{"group_ids":["ebc96a69-b81e-431a-98ca-6b961ae5415f","a073e696-f9b8-4846-afa2-02c55fb33854","7fea5f00-ac94-451e-a1ae-e01a79f851e1","49546dc0-0800-4979-87c7-93b8c369612e","3cfa2849-828b-4f4e-89b5-27659cc9f1a6","3f27e206-d4f1-4507-9149-abfb59270c30"],"ip":"149.88.28.168","organization_ids":[],"referer":"https://testing.octi.staging.filigran.io/dashboard/analyses/reports/1bcdabe3-1aa7-402b-9285-c95ed8a71d1a","socket":"query","user_id":"967d8ce3-a4a4-4d0f-a9c5-7461ede4cb70","user_metadata":{}},"variables":{"id":"1bcdabe3-1aa7-402b-9285-c95ed8a71d1a"},"version":"6.5.5"}
```

```
{"category":"APP","codeStack":"Error\n    at Object.render (https://testing.octi.staging.filigran.io/static/js/front-ITCCMVTO.js:221:991)\n    at a.render (https://testing.octi.staging.filigran.io/static/js/front-ITCCMVTO.js:20:38480)\n    at waa (https://testing.octi.staging.filigran.io/static/js/front-ITCCMVTO.js:8:6305)\n    at NUi (https://testing.octi.staging.filigran.io/static/js/front-ITCCMVTO.js:8:6096)\n    at VHi (https://testing.octi.staging.filigran.io/static/js/front-ITCCMVTO.js:8:46121)\n    at BHi (https://testing.octi.staging.filigran.io/static/js/front-ITCCMVTO.js:8:40772)\n    at xYc (https://testing.octi.staging.filigran.io/static/js/front-ITCCMVTO.js:8:40695)\n    at MWn (https://testing.octi.staging.filigran.io/static/js/front-ITCCMVTO.js:8:40542)\n    at Baa (https://testing.octi.staging.filigran.io/static/js/front-ITCCMVTO.js:8:36774)\n    at PHi (https://testing.octi.staging.filigran.io/static/js/front-ITCCMVTO.js:8:35684)","componentStack":"\n    at n (https://testing.octi.staging.filigran.io/static/js/front-ITCCMVTO.js:20:36332)\n    at ct (https://testing.octi.staging.filigran.io/static/js/front-ITCCMVTO.js:221:800)\n    at t2f (https://testing.octi.staging.filigran.io/static/js/front-ITCCMVTO.js:122751:4455)\n    at rJn (https://testing.octi.staging.filigran.io/static/js/front-ITCCMVTO.js:347:799731)\n    at https://testing.octi.staging.filigran.io/static/js/front-ITCCMVTO.js:347:798711\n    at k31 (https://testing.octi.staging.filigran.io/static/js/front-ITCCMVTO.js:18:142594)\n    at ci (https://testing.octi.staging.filigran.io/static/js/front-ITCCMVTO.js:18:147428)\n    at Suspense\n    at c6f (https://testing.octi.staging.filigran.io/static/js/front-ITCCMVTO.js:151894:13816)\n    at rJn (https://testing.octi.staging.filigran.io/static/js/front-ITCCMVTO.js:347:799731)\n    at https://testing.octi.staging.filigran.io/static/js/front-ITCCMVTO.js:347:798711\n    at k31 (https://testing.octi.staging.filigran.io/static/js/front-ITCCMVTO.js:18:142594)\n    at ci (https://testing.octi.staging.filigran.io/static/js/front-ITCCMVTO.js:18:147428)\n    at Suspense\n    at main\n    at https://testing.octi.staging.filigran.io/static/js/front-ITCCMVTO.js:228:46785\n    at https://testing.octi.staging.filigran.io/static/js/front-ITCCMVTO.js:228:96311\n    at div\n    at https://testing.octi.staging.filigran.io/static/js/front-ITCCMVTO.js:228:46785\n    at https://testing.octi.staging.filigran.io/static/js/front-ITCCMVTO.js:228:96311\n    at d02 (https://testing.octi.staging.filigran.io/static/js/front-ITCCMVTO.js:321393:14114)\n    at hYl (https://testing.octi.staging.filigran.io/static/js/front-ITCCMVTO.js:32873:250)\n    at ewe (https://testing.octi.staging.filigran.io/static/js/front-ITCCMVTO.js:407:8078)\n    at n (https://testing.octi.staging.filigran.io/static/js/front-ITCCMVTO.js:344:5723)\n    at n0p (https://testing.octi.staging.filigran.io/static/js/front-ITCCMVTO.js:489:144875)\n    at o (https://testing.octi.staging.filigran.io/static/js/front-ITCCMVTO.js:20:19858)\n    at s (https://testing.octi.staging.filigran.io/static/js/front-ITCCMVTO.js:20:18570)\n    at eM1 (https://testing.octi.staging.filigran.io/static/js/front-ITCCMVTO.js:228:83927)\n    at ow1 (https://testing.octi.staging.filigran.io/static/js/front-ITCCMVTO.js:228:103135)\n    at Ka1 (https://testing.octi.staging.filigran.io/static/js/front-ITCCMVTO.js:14:60030)\n    at fw1 (https://testing.octi.staging.filigran.io/static/js/front-ITCCMVTO.js:228:104462)\n    at _z1 (https://testing.octi.staging.filigran.io/static/js/front-ITCCMVTO.js:405:2966)\n    at Rq1 (https://testing.octi.staging.filigran.io/static/js/front-ITCCMVTO.js:406:56942)\n    at o (https://testing.octi.staging.filigran.io/static/js/front-ITCCMVTO.js:20:19858)\n    at s (https://testing.octi.staging.filigran.io/static/js/front-ITCCMVTO.js:20:18570)\n    at zF1 (https://testing.octi.staging.filigran.io/static/js/front-ITCCMVTO.js:228:59430)\n    at b02 (https://testing.octi.staging.filigran.io/static/js/front-ITCCMVTO.js:321393:21297)\n    at Suspense\n    at v02 (https://testing.octi.staging.filigran.io/static/js/front-ITCCMVTO.js:321393:22434)\n    at k31 (https://testing.octi.staging.filigran.io/static/js/front-ITCCMVTO.js:18:142594)\n    at ci (https://testing.octi.staging.filigran.io/static/js/front-ITCCMVTO.js:18:147428)\n    at Suspense\n    at Amr (https://testing.octi.staging.filigran.io/static/js/front-ITCCMVTO.js:321393:22997)\n    at N0t (https://testing.octi.staging.filigran.io/static/js/front-ITCCMVTO.js:321393:23219)\n    at https://testing.octi.staging.filigran.io/static/js/front-ITCCMVTO.js:347:798711\n    at Oda (https://testing.octi.staging.filigran.io/static/js/front-ITCCMVTO.js:18:146801)\n    at Gor (https://testing.octi.staging.filigran.io/static/js/front-ITCCMVTO.js:18:150778)\n    at S02\n    at Suspense\n    at W21 (https://testing.octi.staging.filigran.io/static/js/front-ITCCMVTO.js:18:95129)","level":"error","message":"Error","source":"frontend","timestamp":"2025-03-07T10:23:00.555Z","version":"6.5.5"}
```

### PR DESCRIPTION
**Pull request by Archidoit**
### Proposed changes
Add internal_id for entities having no internal_id
(Removing an entity internal_id is not possible anymore after a former fix: https://statics.teams.cdn.office.net/evergreen-assets/safelinks/1/atp-safelinks.html)

### Related issues
https://github.com/OpenCTI-Platform/opencti/issues/10172

### CODE REVIEW

File: opencti-platform/opencti-graphql/src/migrations/1745323742397-fix-missing-internal-ids.js [hunk 1]
```diff
@@ -0,0 +1,26 @@
...
+import { elUpdateByQueryForMigration } from '../database/engine';
+import { READ_DATA_INDICES } from '../database/utils';
+
+const message = '[MIGRATION] add internal_id for entities that have not this field';
+
+export const up = async (next) => {
+  logApp.info(`${message} > started`);
+  const updateQuery = {
+    script: {
+      source: 'ctx._source.internal_id = ctx._source.id; ',
```
Comment (SouadHadjiat) [inline opencti-platform/opencti-graphql/src/migrations/1745323742397-fix-missing-internal-ids.js]: I think we can access the id with ctx._id

File: opencti-platform/opencti-graphql/src/migrations/1745323742397-fix-missing-internal-ids.js [hunk 2]
```diff
@@ -0,0 +1,26 @@
+import { logApp } from '../config/conf';
```
Comment (SouadHadjiat) [inline opencti-platform/opencti-graphql/src/migrations/1745323742397-fix-missing-internal-ids.js]: The migration should have a timestamp +1 of the latest migration on master. So that when we'll merge release/current with possible migrations they will run after this one.

Comment (Archidoit) [reply opencti-platform/opencti-graphql/src/migrations/1745323742397-fix-missing-internal-ids.js]: done

File: opencti-platform/opencti-graphql/src/migrations/1745323742397-fix-missing-internal-ids.js (hunk 1 above)
Comment (Archidoit) [reply opencti-platform/opencti-graphql/src/migrations/1745323742397-fix-missing-internal-ids.js]: done

**Review by SouadHadjiat — APPROVED** [review]
