### PR TITLE
[backend] Fix rule inferred relations updates to save only supported attributes (#3011)

### LINKED ISSUE #3011: Multiple errors in logs: This attribute key first_seen is not allowed on the type targets
## Description
Multiple errors in logs: This attribute key first_seen is not allowed on the type targets 

## Environment

1. Ubuntu 22.04
2. 5.6.1
3. Both clients

## Reproducible Steps
Mesages as shown below keep appearing in error log

## Expected Output

No errors

## Actual Output

{
  "category": "APP",
  "error": {
    "context": {
      "category": "business",
      "http_status": 400,
      "reason": "This attribute key first_seen is not allowed on the type targets"
    },
    "message": "Business validation",
    "name": "FunctionalError",
    "stack": "FunctionalError: Business validation\n    at error (/opt/opencti/build/src/config/errors.js:8:10)\n    at FunctionalError (/opt/opencti/build/src/config/errors.js:83:50)\n    at checkAttributeConsistency (/opt/opencti/build/src/database/middleware.js:1332:11)\n    at innerUpdateAttribute (/opt/opencti/build/src/database/middleware.js:1338:3)\n    at updateAttributeRaw (/opt/opencti/build/src/database/middleware.js:1594:17)\n    at updateAttribute (/opt/opencti/build/src/database/middleware.js:1806:24)\n    at upsertRelationRule (/opt/opencti/build/src/database/middleware.js:2061:10)\n    at createRelationRaw (/opt/opencti/build/src/database/middleware.js:2753:16)\n    at listFromCallback (/opt/opencti/build/src/rules/indicate-sighted/IndicateSightedRule.ts:101:9)\n    at publish (/opt/opencti/build/src/database/middleware-loader.ts:77:30)\n    at elList (/opt/opencti/build/src/database/middleware-loader.ts:89:9)\n    at applyFromStixSighting (/opt/opencti/build/src/rules/indicate-sighted/IndicateSightedRule.ts:109:5)\n    at rulesApplyHandler (/opt/opencti/build/src/manager/ruleManager.ts:245:13)\n    at ruleStreamHandler (/opt/opencti/build/src/manager/ruleManager.ts:308:5)"
  },
  "event": {
    "context": {
      "patch": [
        {
          "op": "replace",
          "path": "/confidence",
          "value": 52
        },
        {
          "op": "replace",
          "path": "/modified",
          "value": "2023-03-13T10:44:40.188Z"
        },
        {
          "op": "replace",
          "path": "/extensions/extension-definition--ea279b3e-5c71-4632-ac08-831c66a786ba/updated_at",
          "value": "2023-03-13T10:44:40.188Z"
        }
      ],
      "reverse_patch": [
        {
          "op": "replace",
          "path": "/confidence",
          "value": 56
        },
        {
          "op": "replace",
          "path": "/modified",
          "value": "2023-03-13T10:44:24.007Z"
        },
        {
          "op": "replace",
          "path": "/extensions/extension-definition--ea279b3e-5c71-4632-ac08-831c66a786ba/updated_at",
          "value": "2023-03-13T10:44:24.007Z"
        }
      ]
    },
    "data": {
      "confidence": 52,
      "count": 1,
      "created": "2023-03-13T09:46:01.119Z",
      "extensions": {
        "extension-definition--ea279b3e-5c71-4632-ac08-831c66a786ba": {
          "created_at": "2023-03-13T09:46:01.119Z",
          "creator_ids": [ "xxxxxx-xxx-xxxx-xxx-xxxxx" ], //REDACTED
          "extension_type": "property-extension",
          "id": "xxxxx8b-xxx-4ed0-xxx-xxxx",  //REDACTED
          "is_inferred": true,
          "negative": false,
          "sighting_of_ref": "3455f9e5-a1e1-44c2-a426-a1b20fbf72f2",
          "sighting_of_ref_object_marking_refs": [ "129df3ce-89cc-409f-952d-b11043654fd3" ],
          "sighting_of_type": "Indicator",
          "sighting_of_value": "138.204.71.60",
          "type": "stix-sighting-relationship",
          "updated_at": "2023-03-13T10:44:40.188Z",
          "where_sighted_refs": [ "hjkgjhk-ghjk-hgjk-hk-ghjk" ], //REDACTED
          "where_sighted_refs_object_marking_refs": [ "129df3ce-89cc-409f-952d-b11043654fd3" ],
          "where_sighted_types": [ "System" ],
          "where_sighted_values": [ "Sistema Correlador" ]
        }
      },
      "first_seen": "2023-03-13T09:04:41.815Z",
      "id": "sighting--d48f74a1-5d4e-49d1-942f-81e819ea39f2",
      "lang": "en",
      "last_seen": "2023-03-13T09:04:41.815Z",
      "modified": "2023-03-13T10:44:40.188Z",
      "object_marking_refs": [ "marking-definition--613f2e26-407d-48c7-9eca-b8e91df99dc9" ],
      "revoked": false,
      "sighting_of_ref": "indicator--4cd80e43-d66d-5947-8c1c-6c191e467d2b",
      "spec_version": "2.1",
      "type": "sighting",
      "where_sighted_refs": [ "identity--fghjfghj-gjhfgh-fghjfghj-ghgh-gfjffgjhfghj" ]  //REDACTED
    },
    "message": "replaces `52` in `confidence`",
    "origin": { "user_id": "gjhgfhj-fghjfgf-fghjfg-fghjfgh-gjfghjfghjfghj" }, //REDACTED
    "scope": "external",
    "type": "update",
    "version": "4"
  },
  "level": "error",
  "message": "[OPENCTI-MODULE] Rule error applying update event",
  "timestamp": "2023-03-13T12:18:52.009Z",
  "version": "5.6.1"
}

## Additional information

Found this about the error in closed issues: https://github.com/OpenCTI-Platform/opencti/issues/2744

### PR DESCRIPTION
**Pull request by SouadHadjiat**
### Proposed changes

* Keep only schema attributes definition when updating an inferred relationship from rule (entity type "targets")

### Related issues

* https://github.com/OpenCTI-Platform/opencti/issues/3011

The issue is due to existing saved relationships with unsuported attributes such as "first_seen" and when a rule is applied on these entities and tries to update them, it will check the entity attributes and throws an error.
I'm not completely sure about how these entities were saved with "first_seen" attributes, but the fix should work (I reproduced the case)

How I reproduced the bug : 
- Enable "INFERENCE OF TARGETING VIA A SIGHTING" rule (under Victimology")
- The rule was applied on my existing test data (intrusion_sets/fe16663c-6b94-4857-9640-e53573560f02)
- I changed the code in IndicateSightedRule.applyFromStixSighting to add first_seen to ruleContent data. (commit 373ff7bc 1/20/2023)
- When changing the relationship confidence, the rule is applied and tries to upsert the entity

### Checklist

- [x] I consider the submitted work as finished
- [x] I tested the code for its functionality
- [ ] I wrote test cases for the relevant uses case
- [ ] I added/update the relevant documentation (either on github or on notion)
- [x] Where necessary I refactored code to improve the overall quality

### Further comments

If this is a relatively large or complex change, kick off the discussion by explaining why you chose the solution you did and what alternatives you considered, etc...

### CODE REVIEW

File: opencti-platform/opencti-graphql/src/database/middleware.js [hunk 1]
```diff
@@ -1989,7 +1989,11 @@ const createRuleDataPatch = (instance) => {
   if (isBasicRelationship(instance.entity_type)) {
     patch.i_inference_weight = weight;
   }
-  const attributes = RULES_ATTRIBUTES_BEHAVIOR.supportedAttributes();
+  let attributes = RULES_ATTRIBUTES_BEHAVIOR.supportedAttributes();
+  if (instance.entity_type) { // keep only supported attributes
```
Comment (richard-julien) [inline opencti-platform/opencti-graphql/src/database/middleware.js]: entity_type should be always available

File: opencti-platform/opencti-graphql/src/database/middleware.js [hunk 2]
```diff
@@ -1989,7 +1989,11 @@ const createRuleDataPatch = (instance) => {
...
+    const entityAttributes = schemaAttributesDefinition.getAttributeNames(instance.entity_type);
+    attributes = attributes.filter((attr) => entityAttributes.includes(attr));
```
Comment (richard-julien) [inline opencti-platform/opencti-graphql/src/database/middleware.js]: I think entityAttributes doesnt contains refs, so objectMarkings will be excluded and your tests will fail :)

Comment (SouadHadjiat) [reply opencti-platform/opencti-graphql/src/database/middleware.js]: I changed  RULES_ATTRIBUTES_BEHAVIOR to get supported attributes by entity type based on all existing rules and which entities they create.

File: opencti-platform/opencti-graphql/src/types/rules.d.ts [hunk 3]
```diff
@@ -55,7 +55,7 @@ interface RuleDefinition {
   display: DisplayDefinition;
   scan: RuleFilters;
   scopes: Array<RuleScope>;
-  behaviors: Array<RuleBehavior>;
+  behaviors: Array<RuleBehavior>; // TODO remove ?
```
Comment (richard-julien) [inline opencti-platform/opencti-graphql/src/types/rules.d.ts]: I would say yes

File: opencti-platform/opencti-graphql/src/rules/sighting-indicator/SightingIndicatorRule.ts [hunk 4]
```diff
@@ -92,7 +92,7 @@ const sightingIndicatorRuleBuilder = (): RuleRuntime => {
         const input = { fromId: toObservable, toId: toSightingIdentityOrLocation, relationship_type: STIX_SIGHTING_RELATIONSHIP };
         const ruleContent = createRuleContent(def.id, dependencies, explanation, {
           confidence: computedConfidence,
-          start_time: range.start,
+          start_time: range.start, // TODO should be first_seen and last_seen
```
Comment (richard-julien) [inline opencti-platform/opencti-graphql/src/rules/sighting-indicator/SightingIndicatorRule.ts]: Nice catch ! Yes definitely

File: opencti-platform/opencti-graphql/src/rules/rules.js [hunk 5]
```diff
@@ -2,37 +2,45 @@ import * as R from 'ramda';
...
+      ];
     }
-    this._attributes[attribute] = operation;
-  },
-  getOperation(name) {
-    return this._attributes[name];
-  },
-  supportedAttributes() {
-    return Object.keys(this._attributes);
+    if (entityType === ENTITY_TYPE_INCIDENT) { // RuleSightingIncident
```
Comment (richard-julien) [inline opencti-platform/opencti-graphql/src/rules/rules.js:32]: Not sure to understand this special case on Incident, to discuss

**Review by richard-julien — CHANGES_REQUESTED** [review]

File: opencti-platform/opencti-graphql/src/rules/rules.js (hunk 5 above)
Comment (SouadHadjiat) [reply opencti-platform/opencti-graphql/src/rules/rules.js:32]: Incident entity has attributes first_seen and last_seen in its schema definition, and RuleSightingIncident creates an Incident along with two relationships

File: opencti-platform/opencti-graphql/src/rules/observed-sighting/ObserveSightingDefinition.ts [hunk 6]
```diff
@@ -1,13 +1,11 @@
 import { RELATION_BASED_ON } from '../../schema/stixCoreRelationship';
 import { ABSTRACT_STIX_CYBER_OBSERVABLE } from '../../schema/general';
 import { ENTITY_TYPE_CONTAINER_OBSERVED_DATA, ENTITY_TYPE_INDICATOR } from '../../schema/stixDomainObject';
-import { RULES_ATTRIBUTES_BEHAVIOR } from '../rules';
 import type { RuleDefinition, RuleFilters, RuleScope } from '../../types/rules';
 
 const id = 'observe_sighting';
 const name = 'Sightings of observables via observed data';
 const description = 'Infer sightings based on observed data and indicators.';
-const behaviors = [{ ruleId: id, attribute: 'attribute_count', operation: RULES_ATTRIBUTES_BEHAVIOR.OPERATIONS.SUM }];
```
Comment (RomuDeuxfois) [inline opencti-platform/opencti-graphql/src/rules/observed-sighting/ObserveSightingDefinition.ts:10]: It's not used ?
Do we have the reason ?

File: opencti-platform/opencti-graphql/src/rules/rules.js [hunk 7]
```diff
@@ -2,37 +2,45 @@ import * as R from 'ramda';
...
+        { name: 'attribute_count', operation: 'SUM' },
+        { name: 'objectMarking', operation: 'AGG' },
+      ];
     }
-    const declaredOperation = this._attributes[attribute];
-    if (isNotEmptyField(declaredOperation) && declaredOperation !== operation) {
-      logApp.warn('Overriding attribute rule operation', meta);
+    if (isBasicRelationship(entityType)) {
+      return [
+        { name: 'start_time', operation: 'MIN' },
```
Comment (RomuDeuxfois) [inline opencti-platform/opencti-graphql/src/rules/rules.js:26]: This attributes are not in the basic relationship right now but in subclasses : stix-core-relationship, stix-SCO-relationship & stix-internal-relationship.
Except in stix-sighting-relationship after all, so its works thanks to the first If.

Can we just add a comment to explain that ?

File: opencti-platform/opencti-graphql/src/rules/rules.js (hunk 5 above)
Comment (RomuDeuxfois) [reply opencti-platform/opencti-graphql/src/rules/rules.js:32]: So, it's direclty related to a rule ?
Can we add-it in the config of the rule ?

Comment (SouadHadjiat) [reply opencti-platform/opencti-graphql/src/rules/rules.js:32]: For now, only RuleSightingIncident creates Incidents entities, I added the comment to explain the case, because Incidents are the only stix core object entities that have first_seen and last_seen attributes, but we should probably discuss this with @richard-julien

File: opencti-platform/opencti-graphql/src/rules/observed-sighting/ObserveSightingDefinition.ts (hunk 6 above)
Comment (SouadHadjiat) [reply opencti-platform/opencti-graphql/src/rules/observed-sighting/ObserveSightingDefinition.ts:10]: Because `attribute_count` is directly set in supportedAttributes when the entity created or updated by the rule is a sighting relationship

**Comment by RomuDeuxfois** [comment]
Tested 👌
