### PR TITLE
[frontend] Fix Empty TAXII Ingester User Reverts to Previous User instead of System (#4813)

### LINKED ISSUE #4813: Empty TAXII Ingester User Reverts to Previous User instead of System
## Description

The "User responsible for data creation (empty = System)" reverts to the previously set user when changing the field blank. There doesn't appear to be a way to set the User back to "System".

## Environment

1. OS (where OpenCTI server runs): Ubuntu 22.04
2. OpenCTI version: 5.11.12
3. OpenCTI client: frontend
4. Other environment details:

## Reproducible Steps

Steps to create the smallest reproducible scenario:
1. Create a TAXII Ingester. Set the user to an existing user. 
2. Click Update
3. Set the user field to blank and hit the "X" to close the UI element
4. Hit Update again to view the User field and notice that the value is no longer blank or set to System. It is the previous user.

## Expected Output

When the User field is blank, the value becomes System.

## Actual Output

The User field becomes the previous user value.

## Screenshots (optional)
Changing value to empty:
image

Value after change (reverted to previous user "admin"):
image

### PR DESCRIPTION
**Pull request by helene-nguyen**
### Proposed changes

* Handle empty value

### Related issues

* https://github.com/OpenCTI-Platform/opencti/issues/4813

### Checklist

- [x] I consider the submitted work as finished
- [x] I tested the code for its functionality
- [ ] I wrote test cases for the relevant uses case
- [ ] I added/update the relevant documentation (either on github or on notion)
- [x] Where necessary I refactored code to improve the overall quality

### Further comments

If this is a relatively large or complex change, kick off the discussion by explaining why you chose the solution you did and what alternatives you considered, etc...

### CODE REVIEW

**Comment by SouadHadjiat** [comment]
When I empty the input, I can now see an empty user in the list, and if I just empty the input and close the update panel, when I reopen it it still displays my old user.

The only way I can set back to System user, is to select in the list the empty user.

Capture d'écran 2023-11-03 094700

Also, When I create a new ingester, and try to set a user, I will always see this empty user in the list first

File: opencti-platform/opencti-front/src/private/components/common/form/CreatorField.tsx [hunk 1]
```diff
@@ -73,7 +73,11 @@ const CreatorField: FunctionComponent<CreatorFieldProps> = ({
           label: n?.node.name,
           value: n?.node.id,
         }));
-        const templateValues = [...creators, ...NewCreators];
+        const emptyValue = {
+          label: '',
+          value: '',
+        };
+        const templateValues = [emptyValue, ...creators, ...NewCreators];
```
Comment (SarahBocognano) [inline opencti-platform/opencti-front/src/private/components/common/form/CreatorField.tsx]: Exact same comments as @SouadHadjiat. I also have that empty field in the autocomplete drawer and if I put an empty field, when I reopen the update, my old user is still here.
Maybe add a "null" in your onInputChange={searchCreators || null} ?

Comment (helene-nguyen) [reply opencti-platform/opencti-front/src/private/components/common/form/CreatorField.tsx]: @SarahBocognano @SouadHadjiat, after more investigations on that, the issue comes from validation schema for the creator only.

It's ready for another review :)

File: opencti-platform/opencti-front/src/private/components/data/ingestionTaxii/IngestionTaxiiEdition.jsx [hunk 2]
```diff
@@ -39,7 +39,16 @@ const ingestionTaxiiValidation = (t) => Yup.object().shape({
...
+  user_id: Yup.lazy((value) => {
+    switch (typeof value) {
+      case 'object':
+        return Yup.object().nullable(); // schema for object
+      case 'string':
+        return Yup.string().nullable();
+      default:
+        return Yup.mixed();
+    }
+  }),
```
Comment (SouadHadjiat) [inline opencti-platform/opencti-front/src/private/components/data/ingestionTaxii/IngestionTaxiiEdition.jsx]: I'm wondering if we could use Yup.mixed().nullable() :

`user_id: Yup.mixed().nullable(),`

I tested it and it works, I can see it used in other components, but I'm not sure of the best practice in this case. What do you think @Kedae ?

Also, we have the same issue for RSS and sync (SyncEdition, IngestionRSSEdition)

Comment (Kedae) [reply opencti-platform/opencti-front/src/private/components/data/ingestionTaxii/IngestionTaxiiEdition.jsx]: I think the interest of lazy with a switch is to have a list of constrained possibilities.

In that case, since we have a default as mixed, a global mixed should be enough

Comment (helene-nguyen) [reply opencti-platform/opencti-front/src/private/components/data/ingestionTaxii/IngestionTaxiiEdition.jsx]: Done :)

**Review by SouadHadjiat — APPROVED** [review]
