### PR TITLE
[frontend] fix the labels after workbench creation

### LINKED ISSUE #7987: Workbench creation: labels not taken into account
## Description
When you create a workbench with a label in Data/Import, the label is not added

## Reproducible Steps
- Go to Data/Import
- Create a workbench with a label
- The workbench is created but without the label

### PR DESCRIPTION
**Pull request by CelineSebe**
### Proposed changes

* add labels_text
* hangling several label in WorkbencheFileLine

### Related issues

* #7987 

### Checklist

- [x] I consider the submitted work as finished
- [x] I tested the code for its functionality
- [ ] I wrote test cases for the relevant uses case (coverage and e2e)
- [ ] I added/update the relevant documentation (either on github or on notion)
- [x] Where necessary I refactored code to improve the overall quality

### CODE REVIEW

File: opencti-platform/opencti-front/src/private/components/data/import/ImportWorkbenchesContent.tsx [hunk 1]
```diff
@@ -42,6 +42,7 @@ export const workbenchLineFragment = graphql`
     metaData {
       mimetype
       list_filters
+        labels_text
```
Comment (JeremyCloarec) [inline opencti-platform/opencti-front/src/private/components/data/import/ImportWorkbenchesContent.tsx]: Small indentation error here

**Review by JeremyCloarec — APPROVED** [review]
