### PR TITLE
[backend/frontend] Fix available relationships for Administrative-Area

### LINKED ISSUE #4092: No relationship type available when creating a relationship from an Area
No relationship type available when creating a relationship from an Area

## Steps to reproduce
Go to an Area. Go to the Knowledge tab.
Select 'Incidents' in the right tab.
Select an incident.
You can't create the relationship because there is no relationship type available.

image

It is the same from relationship from Area to other entity types (Threat actor, campaigns etc)

### PR DESCRIPTION
**Pull request by RomuDeuxfois**
### Proposed changes

* Fix pain point : https://www.notion.so/filigran/Technical-Process-pains-65d4613846a7499392f748bd73087a30?pvs=4#601d33abdab9451dbaa9ea7860f32981

### Related issues

* https://github.com/OpenCTI-Platform/opencti/issues/4092

### Checklist

- [ ] I consider the submitted work as finished
- [ ] I tested the code for its functionality
- [ ] I wrote test cases for the relevant uses case
- [ ] I added/update the relevant documentation (either on github or on notion)
- [ ] Where necessary I refactored code to improve the overall quality

### Further comments

If this is a relatively large or complex change, kick off the discussion by explaining why you chose the solution you did and what alternatives you considered, etc...

### CODE REVIEW

**Review by SarahBocognano — COMMENTED** [review]
Tested ✅  Everything works fine. It's good to remodel the relation.js file like that !

File: opencti-platform/opencti-front/src/private/Root.tsx [hunk 1]
```diff
@@ -97,6 +97,10 @@ const rootPrivateQuery = graphql`
         }
       }
     }
+    schemaRelationsTypesMapping: schemaRelationsTypesMapping {
```
Comment (SouadHadjiat) [inline opencti-platform/opencti-front/src/private/Root.tsx]: Since it's the same name, could we just have `schemaRelationsTypesMapping {` ?

File: opencti-platform/opencti-front/src/private/Root.tsx [hunk 2]
```diff
@@ -128,11 +132,12 @@ interface RootComponentProps {
 
 const RootComponent: FunctionComponent<RootComponentProps> = ({ queryRef }) => {
   const queryData = usePreloadedQuery(rootPrivateQuery, queryRef);
-  const { me, settings, entitySettings, schemaSCOs, schemaSDOs, schemaSROs } = queryData;
+  const { me, settings, entitySettings, schemaSCOs, schemaSDOs, schemaSROs, schemaRelationsTypesMapping } = queryData;
   const schema = {
     scos: schemaSCOs.edges.map((sco) => sco.node),
     sdos: schemaSDOs.edges.map((sco) => sco.node),
     sros: schemaSROs.edges.map((sco) => sco.node),
+    schemaRelationsTypesMapping,
```
Comment (SouadHadjiat) [inline opencti-platform/opencti-front/src/private/Root.tsx]: Could it be a map instead of a list ? like this :  
`new Map(schemaRelationsTypesMapping.map((n) => [n.key, n.values]));`
So that in `resolveRelationsTypes`, we could direcly get the values by key

File: opencti-platform/opencti-graphql/src/domain/stixRelationship.js [hunk 3]
```diff
@@ -18,3 +18,22 @@ export const stixRelationshipDelete = async (context, user, stixRelationshipId)
 };
 
 export const getSpecVersionOrDefault = ({ spec_version }) => spec_version ?? STIX_SPEC_VERSION;
+
+export const schemaRelationsTypesMapping = (entityTypes = []) => {
+  const entries = Object.entries(stixCoreRelationshipsMapping);
+  let filterEntries;
+  if (entityTypes.length > 0) {
```
Comment (SouadHadjiat) [inline opencti-platform/opencti-graphql/src/domain/stixRelationship.js]: where do we call this method with entityTypes argument ?

File: opencti-platform/opencti-front/src/private/Root.tsx (hunk 1 above)
Comment (RomuDeuxfois) [reply opencti-platform/opencti-front/src/private/Root.tsx]: well seen

File: opencti-platform/opencti-graphql/src/domain/stixRelationship.js (hunk 3 above)
Comment (RomuDeuxfois) [reply opencti-platform/opencti-graphql/src/domain/stixRelationship.js]: Never, it's just to prepare the next if we need it
But, it's maybe overkill

**Comment by RomuDeuxfois** [comment]
PR comments fixed

File: opencti-platform/opencti-front/src/private/components/common/stix_core_relationships/StixCoreRelationshipCreation.jsx [hunk 4]
```diff
@@ -351,37 +352,44 @@ class StixCoreRelationshipCreation extends Component {
...
+                      defaultConfidence={confidence}
+                      defaultStartTime={startTime}
+                      defaultStopTime={stopTime}
+                      defaultCreatedBy={defaultCreatedBy}
+                      defaultMarkingDefinitions={defaultMarkingDefinitions}
+                  />
+                </>
+            );
+          }}
+        </UserContext.Consumer>
```
Comment (tomibennett) [inline opencti-platform/opencti-front/src/private/components/common/stix_core_relationships/StixCoreRelationshipCreation.jsx:392]: For curiosity, can you tell me what is `UserContext.Consumer` tag, and why embedding the rest of the code in it?

**Comment by tomibennett** [comment]
I don't know if there is a strong indent rule but some of your modifications have 4 spaces instead of 2. That may be something to take care of.

File: opencti-platform/opencti-front/src/private/components/common/stix_core_relationships/StixCoreRelationshipCreation.jsx (hunk 4 above)
Comment (RomuDeuxfois) [reply opencti-platform/opencti-front/src/private/components/common/stix_core_relationships/StixCoreRelationshipCreation.jsx:392]: This allows the application context to be used in React classes. It's the old way before hooks.

https://legacy.reactjs.org/docs/context.html
