### PR TITLE
[Front] FIlter "relatedTo" not take into account the entity types palette (#2842)

### LINKED ISSUE #2842: FIlter "relatedTo" not take into account the entity types palette
## Description

FIlter "relatedTo" not take into account the entity types palette.
And the selection of entity type SCO is not working.

This filter is available in custom dashboard.
image

### PR DESCRIPTION
**Pull request by RomuDeuxfois**
### Proposed changes

*
*

### Related issues

* [issues 2842](https://github.com/OpenCTI-Platform/opencti/issues/2842)
*

### Checklist

- [x] I consider the submitted work as finished
- [x] I tested the code for its functionality
- [ ] I wrote test cases for the relevant uses case
- [ ] I added/update the relevant documentation (either on github or on notion)
- [ ] Where necessary I refactored code to improve the overall quality

### Further comments

If this is a relatively large or complex change, kick off the discussion by explaining why you chose the solution you did and what alternatives you considered, etc...

### CODE REVIEW

**Review by Archidoit — APPROVED** [review]

File: opencti-platform/opencti-front/src/utils/filters/useSearchEntities.js [hunk 1]
```diff
@@ -372,6 +373,7 @@ const useSearchEntities = ({
                 label: defaultValue(n.node),
                 value: n.node.id,
                 type: n.node.entity_type,
+                parentTypes: n.node.parent_types,
```
Comment (Kedae) [inline opencti-platform/opencti-front/src/utils/filters/useSearchEntities.js:376]: Why is this different from the Contains filter ?

Comment (RomuDeuxfois) [reply opencti-platform/opencti-front/src/utils/filters/useSearchEntities.js:376]: I missed this one, it's fixed

Comment (Kedae) [reply opencti-platform/opencti-front/src/utils/filters/useSearchEntities.js:376]: Parent_types is the proper way of doing this, we need to align the other filters to this way
