### PR TITLE
[Frontend] Fix labels list (#6494)

### LINKED ISSUE #6494: Labels display doesn't work
## Description

The window that should allow us to see all the labels is stuck on the 25 first labels, i.e. scrolling down doesn't load any other labels.

## Environment

OCTI 6.0.8 (testing and demo)

Firefox 124.0.1 (64-bit)

## Reproducible Steps

Steps to create the smallest reproducible scenario:
1. Go to the window "Settings > Taxonomies > Labels"
2. Scroll down
-> Impossible to see more than 25 labels

### PR DESCRIPTION
**Pull request by Kedae**
Closes #6494

### CODE REVIEW

File: opencti-platform/opencti-front/src/private/components/data/ToolBar.jsx [hunk 1]
```diff
@@ -1346,13 +1346,17 @@ class ToolBar extends Component {
...
-        || (entityTypeFilterValues.length === 1
-            && notEnrichableTypes.includes(entityTypeFilterValues[0]))
-        || (!isManualEnrichSelect && !isAllEnrichSelect);
+      || (entityTypeFilterValues.length === 1
+        && notEnrichableTypes.includes(entityTypeFilterValues[0]))
+      || (!isManualEnrichSelect && !isAllEnrichSelect);
+    // endregion
+    // region orgaSharing
+    const notShareableTypes = ['Label', 'Vocabulary', 'Case-Template', 'DeleteOperation'];
+    const isShareableType = !notShareableTypes.includes(selectedTypes[0]);
```
Comment (labo-flg) [inline opencti-platform/opencti-front/src/private/components/data/ToolBar.jsx:1359]: shall we put this in a utility function somewhere?

**Comment by labo-flg** [comment]
tested OK ✅

**Review by labo-flg — APPROVED** [review]

File: opencti-platform/opencti-front/src/private/components/data/ToolBar.jsx (hunk 1 above)
Comment (Kedae) [reply opencti-platform/opencti-front/src/private/components/data/ToolBar.jsx:1359]: Yep, we will have to rework Toolbar someday
