### PR TITLE
[frontend] fix UI in exclusion lists (#9971)

### LINKED ISSUE #9971: No space in Exclusion lists screen
## Description
Design of Exclusion list screen

## Reproducible Steps
Go under Settings > Customization > Exclusion list.
There are no space between the different parts of the screen (no space before the search bar etc)

Image

### PR DESCRIPTION
**Pull request by labo-flg**
closes #9971

missing `withGap` after refactoring of `PageContainer`

### CODE REVIEW

File: opencti-platform/opencti-front/src/components/PageContainer.tsx [hunk 1]
```diff
@@ -4,7 +4,7 @@ import type { Theme } from './Theme';
 
 export const PageContainerContext = React.createContext({ inPageContainer: false });
 
-const PageContainer: FunctionComponent<{ children: React.ReactNode, withRightMenu: boolean, withGap?: boolean }> = ({ children, withRightMenu = false, withGap = false }) => {
+const PageContainer: FunctionComponent<{ children: React.ReactNode, withRightMenu?: boolean, withGap?: boolean }> = ({ children, withRightMenu = false, withGap = false }) => {
```
Comment (labo-flg) [inline opencti-platform/opencti-front/src/components/PageContainer.tsx:7]: fix react warn

File: opencti-platform/opencti-front/src/private/components/settings/exclusion_lists/ExclusionLists.tsx [hunk 2]
```diff
@@ -1,18 +1,15 @@
-import CustomizationMenu from '@components/settings/CustomizationMenu';
```
Comment (labo-flg) [inline opencti-platform/opencti-front/src/private/components/settings/exclusion_lists/ExclusionLists.tsx:1]: cleaning up imports

**Review by Kedae — APPROVED** [review]
