### PR TITLE
[backend] Fix activity manager indexing error (#7986)

### LINKED ISSUE #7986: Activity manager error "Numeric value out of range"
## Description

```
{"category":"APP","errors":[{"attributes":{"errors":[{"caused_by":{"caused_by":{"reason":"Numeric value (1722530083665) out of range of int (-2147483648 - 2147483647)\n at [Source: (byte[])\"\"[truncated 1210 bytes]; line: 1, column: 617]","type":"illegal_argument_exception"},"reason":"[1:604] failed to parse field [context_data.input.sort] of type [integer] in document with id '1722531033289-0'. Preview of field's value: '1722530083665'","type":"document_parsing_exception"}],"genre":"TECHNICAL","http_status":500},"message":"Bulk indexing fail","name":"DATABASE_ERROR","stack":"DATABASE_ERROR: Bulk indexing fail\n    at error (/opt/opencti/build/src/config/errors.js:8:10)\n    at DatabaseError (/opt/opencti/build/src/config/errors.js:58:48)\n    at /opt/opencti/build/src/database/engine.js:3079:13\n    at processTicksAndRejections (node:internal/process/task_queues:95:5)\n    at elIndexElementsFn (/opt/opencti/build/src/database/engine.js:3487:7)\n    at async Promise.all (index 1)\n    at eventsApplyHandler (/opt/opencti/build/src/manager/activityManager.ts:124:5)\n    at activityStreamHandler (/opt/opencti/build/src/manager/activityManager.ts:131:5)\n    at processStreamResult (/opt/opencti/build/src/database/redis.ts:646:3)\n    at processStep (/opt/opencti/build/src/database/redis.ts:700:31)\n    at processingLoop (/opt/opencti/build/src/database/redis.ts:717:13)"}],"level":"error","manager":"ACTIVITY_MANAGER","message":"Bulk indexing fail","source":"backend","timestamp":"2024-08-01T16:50:33.306Z","version":"6.2.9"}

```

## Environment

1. OS (where OpenCTI server runs): { e.g. Mac OS 10, Windows 10, Ubuntu 16.4, etc. }
2. OpenCTI version: 6.1.11
3. OpenCTI client: { e.g. frontend or python }
4. Other environment details:

### PR DESCRIPTION
**Pull request by SouadHadjiat**
### Proposed changes

* Remove input props such as sort that was causing the error of the issue
* Add missing fields to redacted inputs

### Related issues

* #7986

### Checklist

- [x] I consider the submitted work as finished
- [x] I tested the code for its functionality
- [ ] I wrote test cases for the relevant uses case (coverage and e2e)
- [ ] I added/update the relevant documentation (either on github or on notion)
- [ ] Where necessary I refactored code to improve the overall quality

### Further comments

This issue happens only on old database that were not on strict mapping and which had context_data.input mapping set to object instead of flat. These databases may experience other issues that cannot be fixed here (like authorized members renaming)

### CODE REVIEW

File: opencti-platform/opencti-graphql/src/manager/activityListener.ts [hunk 1]
```diff
@@ -29,6 +29,8 @@ import { REDACTED_INFORMATION } from '../database/utils';
 
 const INTERNAL_READ_ENTITIES = [ENTITY_TYPE_WORKSPACE];
 const LOGS_SENSITIVE_FIELDS = conf.get('app:app_logs:logs_redacted_inputs') ?? [];
+const REDACTED_SENSITIVE_FIELDS = [...LOGS_SENSITIVE_FIELDS, 'authentication_value'];
```
Comment (JeremyCloarec) [inline opencti-platform/opencti-graphql/src/manager/activityListener.ts]: I don't understand why authentication_value is added here and not in config? Is it because we want to include it no matter the config?

Comment (SouadHadjiat) [reply opencti-platform/opencti-graphql/src/manager/activityListener.ts]: I added it here because it's saved in the activity history, and I didn't see it in the logs. but you're right I should add it there directly.

**Review by JeremyCloarec — APPROVED** [review]
