### PR TITLE
[backend/frontend]  User overview modification (#2849)

### LINKED ISSUE #2849: User overview modification
## Use case

In an overview of a user:

1. Fix the user operations history chart which does not work (line is always 0)
2. Change the layout of the bottom with a 50/50 grid:
  a. Left = Operations chart
  b. Right = History

### PR DESCRIPTION
**Pull request by Archidoit**
### Related issue
https://github.com/OpenCTI-Platform/opencti/issues/2849

### CODE REVIEW

File: opencti-platform/opencti-graphql/src/database/middleware.js [hunk 1]
```diff
@@ -498,7 +499,9 @@ const convertAggregateDistributions = async (context, user, limit, orderingFunct
 export const timeSeriesEntities = async (context, user, types, args) => {
   const timeSeriesArgs = buildEntityFilters({ types, ...args });
   const { startDate, endDate, interval } = args;
-  const histogramData = await elHistogramCount(context, user, args.onlyInferred ? READ_DATA_INDICES_INFERRED : READ_DATA_INDICES, timeSeriesArgs);
+  const dataIndices = args.onlyInferred ? READ_DATA_INDICES_INFERRED : READ_DATA_INDICES;
+  const indexName = types.includes(ENTITY_TYPE_HISTORY) ? INDEX_HISTORY : dataIndices;
```
Comment (Kedae) [inline opencti-platform/opencti-graphql/src/database/middleware.js]: Shouldn't the check be that the types only contains History ? I'm not sur to understand the choice that has been made of getting only History (after reading the brainstorm). 

Additionnaly, why INDEX_HISTORY and not READ_INDEX_HISTORY ?

I thought we could do something like types.includes(HISTORY) ? dataIndices : READ_PLATFORM_INDICES ?

Comment (Archidoit) [reply opencti-platform/opencti-graphql/src/database/middleware.js]: right for READ_INDEX_HISTORY instead of INDEX_HISTORY

not sure to understand the rest, we can have a quick talk

Comment (Archidoit) [reply opencti-platform/opencti-graphql/src/database/middleware.js]: understood, fixed

File: opencti-platform/opencti-front/src/private/components/settings/users/User.js [hunk 2]
```diff
@@ -460,9 +460,9 @@ class UserComponent extends Component {
           container={true}
           spacing={3}
           classes={{ container: classes.gridContainer }}
-          style={{ marginTop: 20 }}
+          style={{ marginTop: 30 }}
         >
-          <Grid item={true} xs={12}>
+          <Grid item={true} xs={6} style={{ marginBottom: 25 }}>
```
Comment (RomuDeuxfois) [inline opencti-platform/opencti-front/src/private/components/settings/users/User.js:465]: Why do we have this margin bottom?

File: opencti-platform/opencti-front/src/private/components/settings/users/User.js [hunk 3]
```diff
@@ -513,8 +513,10 @@ class UserComponent extends Component {
               />
             </Paper>
           </Grid>
+          <Grid item={true} xs={6} style={{ paddingTop: 8 }}>
```
Comment (RomuDeuxfois) [inline opencti-platform/opencti-front/src/private/components/settings/users/User.js:516]: Proposition: Isn't it more readable with more space ?

paddingTop: 40 px on the left grid

image

File: opencti-platform/opencti-front/src/private/components/settings/users/UserHistory.js [hunk 4]
```diff
@@ -31,29 +21,29 @@ class UserHistory extends Component {
     const { t, userId } = this.props;
     const { entitySearchTerm } = this.state;
     return (
-      <div style={{ marginTop: 50 }}>
+      <div>
         <Typography
           variant="h4"
           gutterBottom={true}
-          style={{ float: 'left', marginTop: 12 }}
+          style={{ float: 'left', margin: '16px 0 0 0' }}
```
Comment (RomuDeuxfois) [inline opencti-platform/opencti-front/src/private/components/settings/users/UserHistory.js:28]: you can use marginTop directly

File: opencti-platform/opencti-front/src/private/components/settings/users/User.js (hunk 2 above)
Comment (Archidoit) [reply opencti-platform/opencti-front/src/private/components/settings/users/User.js:465]: when passing History and Operations in the same line, there was a difference at the bottom (Operations didn't respect the margin bottom)

File: opencti-platform/opencti-front/src/private/components/settings/users/UserHistory.js (hunk 4 above)
Comment (Archidoit) [reply opencti-platform/opencti-front/src/private/components/settings/users/UserHistory.js:28]: no I can't, if I do this, there is a gap between History title and the History box (see screenshot below)

image

File: opencti-platform/opencti-front/src/private/components/settings/users/User.js (hunk 3 above)
Comment (Archidoit) [reply opencti-platform/opencti-front/src/private/components/settings/users/User.js:516]: you're right! maybe not that much, but I will increase it :)

**Review by RomuDeuxfois — APPROVED** [review]
