### PR TITLE
[migration] Fix for missing user/role in RBAC migration

### LINKED ISSUE #4208: Fix RBAC migration for missing user/role

### PR DESCRIPTION
**Pull request by Kedae**

### CODE REVIEW

File: opencti-platform/opencti-graphql/src/migrations/1681899432316-roles_groups_missing.js [hunk 1]
```diff
@@ -39,10 +39,15 @@ export const up = async (next) => {
...
-      // Delete the old relation
-      await deleteElementById(context, context.user, id, entity_type);
+      const user = await storeLoadById(context, context.user, userId, ENTITY_TYPE_USER);
+      const role = await storeLoadById(context, context.user, roleId, ENTITY_TYPE_ROLE);
+      if (user && role) {
+        // ignore because some stuff has been deleted from elastic
+        const groupRelationInput = { relationship_type: RELATION_MEMBER_OF, toId: roleGroupAssociations[roleId] };
+        await userAddRelation(context, context.user, userId, groupRelationInput);
+        // Delete the old relation
+        await deleteElementById(context, context.user, id, entity_type);
```
Comment (richard-julien) [inline opencti-platform/opencti-graphql/src/migrations/1681899432316-roles_groups_missing.js]: I think relation deletion must be still be done as corrupt
