### PR TITLE
[frontend] Linked entities view is broken (#5515)(#5518)

### LINKED ISSUE #5515: Linked entities view is broken
## Description

When I go in an entity contained in Threat/Arsenal/techniques/entities/Location, go in knowledge, select linked entities, the view is broken
## Environment

Public demo

## Reproducible Steps

Steps to create the smallest reproducible scenario:
1. Go to one of the entities of the above tabs
2. Go in knowledge
3. Tap on related entities
4. The view is broken

## Expected Output

View the "related to" entities
## Actual Output

Error
## Screenshots (optional)
image

### LINKED ISSUE #5518: "Related entities" section in Knowledge tab crash
## Description

When I go to the "Related entities" section of a Knowledge tab, I get an error. I tried for :

- Intrusion set, Malware, Threat actor, Tool, Organization -> same behavior (error occurs)
- Attack patterns -> No error here
- Other not tested

## Environment

OCTI 5.12.17 (filigran and demo)

Firefox 121.0.1 (64-bit)

## Reproducible Steps

Steps to create the smallest reproducible scenario:
1. Go on an Intrusion set
2. Go on the knowledge tab
3. Go on "Related entities"
-> Error 

## Screenshots

Screenshot 2024-01-16 130439

### PR DESCRIPTION
**Pull request by jpkha**
closed #5515 #5518

### CODE REVIEW

File: opencti-platform/opencti-graphql/src/database/engine.js [hunk 1]
```diff
@@ -1687,6 +1687,13 @@ const buildSubQueryForFilterGroup = async (context, user, inputFilters) => {
 // Example: filter = {mode: 'or', operator: 'eq', key: ['entity_type'], values: ['Report', 'Stix-Cyber-Observable']}
 // we check parent_types because otherwise we would never match Stix-Cyber-Observable which is an abstract parent type
 const adaptFilterToEntityTypeFilterKey = (filter) => {
+  // In case where filter values is an empty array
+  if (filter.values.length === 0) {
```
Comment (Archidoit) [inline opencti-platform/opencti-graphql/src/database/engine.js]: if operator=nil, we can have filter.values=[]

**Review by Archidoit — APPROVED** [review]
