### PR TITLE
[front] - Fix on Observable types filtering

### LINKED ISSUE #2976: In Observations => Observables, filters do not impact the URL
## Description

In Observations => Observables, filters do not impact the URL:

Repro case:

1. Go in observables
2. Select a type of observable in the right menu
3. URL remains unchanged

### PR DESCRIPTION
**Pull request by Kedae**

### CODE REVIEW

File: opencti-platform/opencti-front/src/utils/hooks/useLocalStorage.ts [hunk 1]
```diff
@@ -128,6 +130,7 @@ const setStoredValueToHistory = (
   const searchParams = new URLSearchParams(window.location.search);
   const finalParams = searchParamsToStorage(searchParams);
   const urlParams = buildParamsFromHistory(valueToStore);
+  console.log('Params ?', finalParams, urlParams);
```
Comment (SamuelHassine) [inline opencti-platform/opencti-front/src/utils/hooks/useLocalStorage.ts]: Concole.log

Comment (Kedae) [reply opencti-platform/opencti-front/src/utils/hooks/useLocalStorage.ts]: Oops.

**Review by yassine-ouaamou — APPROVED** [review]
