### PR TITLE
[frontend] fix update note

### LINKED ISSUE #10327: Trying to update a specific Note raises an error
## Description

When I try to update a specific note, I get an error. The Note is this one : https://testing.octi.staging.filigran.io/dashboard/analyses/notes/05dbac7b-4632-4781-81e0-5d3a82b9a66d

This doesn't happen with other notes.

NB: I'm a platform admin and I created this Note through the API

## Environment

OCTI 6.5.8

## Reproducible Steps

Steps to create the smallest reproducible scenario:
1. Go on this Note : https://testing.octi.staging.filigran.io/dashboard/analyses/notes/05dbac7b-4632-4781-81e0-5d3a82b9a66d
2. Click on the button with the three dots (i.e. the burger icon) on top right corner, then "update"
-> Error 

Image

Image

In the front-end platform logs I get this log: `TypeError: e is null`

### PR DESCRIPTION
**Pull request by marieflorescontact**
### Proposed changes
* Note with no abstract raised an error

### Related issues

* closes: https://github.com/OpenCTI-Platform/opencti/issues/10327

### Checklist

- [x] I consider the submitted work as finished
- [x] I tested the code for its functionality
- [ ] I wrote test cases for the relevant uses case (coverage and e2e)
- [ ] I added/update the relevant documentation (either on github or on notion)
- [ ] Where necessary I refactored code to improve the overall quality

### CODE REVIEW

**Review by JeremyCloarec — DISMISSED** [review]

File: opencti-platform/opencti-front/src/private/components/common/form/TextFieldAskAI.tsx [hunk 1]
```diff
@@ -239,7 +239,7 @@ const TextFieldAskAI: FunctionComponent<TextFieldAskAiProps> = ({
           <IconButton
             size="small"
             onClick={(event) => ((isEnterpriseEdition && enabled && configured) ? handleOpenMenu(event) : null)}
-            disabled={disabled || currentValue.length < 10}
+            disabled={disabled || currentValue?.length < 10}
```
Comment (lndrtrbn) [inline opencti-platform/opencti-front/src/private/components/common/form/TextFieldAskAI.tsx]: Not sure of the fix. `currentValue` is defined as a string that cannot be null in props type. So probably that the fix is more to be sure `currentValue` is defined when given to the component.

For most of component called it is already done (for example `ResponseDialog.tsx` l.190) but there are still some calls without this check. Can you try to make this check for all calls and verify that there is no crash?

**Review by lndrtrbn — APPROVED** [review]
