### PR TITLE
[frontend] fix EE button in organization edition is not clickable (#6378)

### LINKED ISSUE #6378: EE button in organization edition is not clickable
## Reproductible steps

Disable EE.
Go to Parameters > Settings > Organization.
Go to an organization overview.
Edit it.
The EE button next to the 'granable groups' field is not clikable whereas other EE button in the platform are.
image

When we click on the EE button, a pop-up should open, enabling to activate EE.

### PR DESCRIPTION
**Pull request by SarahBocognano**
### Related issues

* https://github.com/OpenCTI-Platform/opencti/issues/6378

### Checklist

- [ ] I consider the submitted work as finished
- [ ] I tested the code for its functionality
- [ ] I wrote test cases for the relevant uses case
- [ ] I added/update the relevant documentation (either on github or on notion)
- [ ] Where necessary I refactored code to improve the overall quality

### Further comments

If this is a relatively large or complex change, kick off the discussion by explaining why you chose the solution you did and what alternatives you considered, etc...

### CODE REVIEW

File: opencti-platform/opencti-front/src/private/components/common/entreprise_edition/EnterpriseEditionAgreement.tsx [hunk 1]
```diff
@@ -91,6 +91,7 @@ EnterpriseEditionAgreementProps
             control={
               <Checkbox
                 checked={enterpriseEditionConsent}
+                disabled={false}
```
Comment (Kedae) [inline opencti-platform/opencti-front/src/private/components/common/entreprise_edition/EnterpriseEditionAgreement.tsx:94]: What is it for ?

**Comment by SamuelHassine** [comment]
@SarahBocognano any news on this one?
