### PR TITLE
[backend] Improve alias generation and resolution to improve data ingestion (#7020)

### LINKED ISSUE #6716: Worker missing reference errors / Inconsistencies / Slow ingestion rate
## Description
I added a new pulse in Alienvault that resulted in about 1.5M Bundles to ingest.
The Ingestion rate was normal at the beginning but then dropped significantly (from about 20 - 30/s to < 1/s). At this time I used 6 Workers.
Currently the only thing I can do is to increase the no of workers significantly to 120 to process these entities as fast as possible (it is slow because of the retry mechanism, not because of data ingestion).

## Environment

1. OS (where OpenCTI server runs): debian (k8s)
2. OpenCTI version: 6.0.9
3. OpenCTI client: python

# LOGS
```json
{"timestamp": "2024-04-17T04:47:30.656736Z", "level": "INFO", "name": "worker", "message": "Message processed, thread terminated", "taskName": null}
{"timestamp": "2024-04-17T04:47:30.657027Z", "level": "INFO", "name": "worker", "message": "Message acknowledged", "taskName": null, "attributes": {"tag": 89}}
{"timestamp": "2024-04-17T04:47:30.658363Z", "level": "INFO", "name": "worker", "message": "Processing a new message, launching a thread...", "taskName": null, "attributes": {"tag": 90}}
{"timestamp": "2024-04-17T04:47:30.659131Z", "level": "INFO", "name": "api", "message": "Creating stix_core_relationship", "taskName": null, "attributes": {"relationship_type": "indicates", "from_id": "indicator--abcf801d-742a-528e-bdfe-c70d9bfda6f3", "to_id": "attack-pattern--6bd77f85-7bda-5181-89ad-daf92069486d"}}
{"timestamp": "2024-04-17T04:47:33.128696Z", "level": "INFO", "name": "worker", "message": "Message reprocess", "taskName": null, "attributes": {"tag": 90, "count": 1}}
{"timestamp": "2024-04-17T04:47:33.128987Z", "level": "INFO", "name": "api", "message": "Creating stix_core_relationship", "taskName": null, "attributes": {"relationship_type": "indicates", "from_id": "indicator--abcf801d-742a-528e-bdfe-c70d9bfda6f3", "to_id": "attack-pattern--6bd77f85-7bda-5181-89ad-daf92069486d"}}
{"timestamp": "2024-04-17T04:47:34.556683Z", "level": "INFO", "name": "worker", "message": "Message reprocess", "taskName": null, "attributes": {"tag": 90, "count": 2}}
{"timestamp": "2024-04-17T04:47:34.557130Z", "level": "INFO", "name": "api", "message": "Creating stix_core_relationship", "taskName": null, "attributes": {"relationship_type": "indicates", "from_id": "indicator--abcf801d-742a-528e-bdfe-c70d9bfda6f3", "to_id": "attack-pattern--6bd77f85-7bda-5181-89ad-daf92069486d"}}
{"timestamp": "2024-04-17T04:47:36.538655Z", "level": "INFO", "name": "worker", "message": "Message reprocess", "taskName": null, "attributes": {"tag": 90, "count": 3}}
{"timestamp": "2024-04-17T04:47:36.539147Z", "level": "INFO", "name": "api", "message": "Creating stix_core_relationship", "taskName": null, "attributes": {"relationship_type": "indicates", "from_id": "indicator--abcf801d-742a-528e-bdfe-c70d9bfda6f3", "to_id": "attack-pattern--6bd77f85-7bda-5181-89ad-daf92069486d"}}
{"timestamp": "2024-04-17T04:47:36.586137Z", "level": "WARNING", "name": "worker", "message": "Traceback (most recent call last):\n  File \"/opt/opencti-worker/worker.py\", line 268, in data_handler\n    self.api.stix2.import_bundle_from_json(\n  File \"/usr/local/lib/python3.12/site-packages/pycti/utils/opencti_stix2.py\", line 215, in import_bundle_from_json\n    return self.import_bundle(\n           ^^^^^^^^^^^^^^^^^^^\n  File \"/usr/local/lib/python3.12/site-packages/pycti/utils/opencti_stix2.py\", line 2373, in import_bundle\n    self.import_relationship(item, update, types)\n  File \"/usr/local/lib/python3.12/site-packages/pycti/utils/opencti_stix2.py\", line 1237, in import_relationship\n    stix_relation_result = self.opencti.stix_core_relationship.import_from_stix2(\n                           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"/usr/local/lib/python3.12/site-packages/pycti/entities/opencti_stix_core_relationship.py\", line 1132, in import_from_stix2\n    return self.create(\n           ^^^^^^^^^^^^\n  File \"/usr/local/lib/python3.12/site-packages/pycti/entities/opencti_stix_core_relationship.py\", line 611, in create\n    result = self.opencti.query(\n             ^^^^^^^^^^^^^^^^^^^\n  File \"/usr/local/lib/python3.12/site-packages/pycti/api/opencti_api_client.py\", line 351, in query\n    raise ValueError(\nValueError: {'name': 'MISSING_REFERENCE_ERROR', 'message': 'Element(s) not found'}\n\nDuring handling of the above exception, another exception occurred:\n\nTraceback (most recent call last):\n  File \"/opt/opencti-worker/worker.py\", line 268, in data_handler\n    self.api.stix2.import_bundle_from_json(\n  File \"/usr/local/lib/python3.12/site-packages/pycti/utils/opencti_stix2.py\", line 215, in import_bundle_from_json\n    return self.import_bundle(\n           ^^^^^^^^^^^^^^^^^^^\n  File \"/usr/local/lib/python3.12/site-packages/pycti/utils/opencti_stix2.py\", line 2373, in import_bundle\n    self.import_relationship(item, update, types)\n  File \"/usr/local/lib/python3.12/site-packages/pycti/utils/opencti_stix2.py\", line 1237, in import_relationship\n    stix_relation_result = self.opencti.stix_core_relationship.import_from_stix2(\n                           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"/usr/local/lib/python3.12/site-packages/pycti/entities/opencti_stix_core_relationship.py\", line 1132, in import_from_stix2\n    return self.create(\n           ^^^^^^^^^^^^\n  File \"/usr/local/lib/python3.12/site-packages/pycti/entities/opencti_stix_core_relationship.py\", line 611, in create\n    result = self.opencti.query(\n             ^^^^^^^^^^^^^^^^^^^\n  File \"/usr/local/lib/python3.12/site-packages/pycti/api/opencti_api_client.py\", line 351, in query\n    raise ValueError(\nValueError: {'name': 'MISSING_REFERENCE_ERROR', 'message': 'Element(s) not found'}\n\nDuring handling of the above exception, another exception occurred:\n\nTraceback (most recent call last):\n  File \"/opt/opencti-worker/worker.py\", line 268, in data_handler\n    self.api.stix2.import_bundle_from_json(\n  File \"/usr/local/lib/python3.12/site-packages/pycti/utils/opencti_stix2.py\", line 215, in import_bundle_from_json\n    return self.import_bundle(\n           ^^^^^^^^^^^^^^^^^^^\n  File \"/usr/local/lib/python3.12/site-packages/pycti/utils/opencti_stix2.py\", line 2373, in import_bundle\n    self.import_relationship(item, update, types)\n  File \"/usr/local/lib/python3.12/site-packages/pycti/utils/opencti_stix2.py\", line 1237, in import_relationship\n    stix_relation_result = self.opencti.stix_core_relationship.import_from_stix2(\n                           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"/usr/local/lib/python3.12/site-packages/pycti/entities/opencti_stix_core_relationship.py\", line 1132, in import_from_stix2\n    return self.create(\n           ^^^^^^^^^^^^\n  File \"/usr/local/lib/python3.12/site-packages/pycti/entities/opencti_stix_core_relationship.py\", line 611, in create\n    result = self.opencti.query(\n             ^^^^^^^^^^^^^^^^^^^\n  File \"/usr/local/lib/python3.12/site-packages/pycti/api/opencti_api_client.py\", line 351, in query\n    raise ValueError(\nValueError: {'name': 'MISSING_REFERENCE_ERROR', 'message': 'Element(s) not found'}\n\nDuring handling of the above exception, another exception occurred:\n\nTraceback (most recent call last):\n  File \"/opt/opencti-worker/worker.py\", line 268, in data_handler\n    self.api.stix2.import_bundle_from_json(\n  File \"/usr/local/lib/python3.12/site-packages/pycti/utils/opencti_stix2.py\", line 215, in import_bundle_from_json\n    return self.import_bundle(\n           ^^^^^^^^^^^^^^^^^^^\n  File \"/usr/local/lib/python3.12/site-packages/pycti/utils/opencti_stix2.py\", line 2373, in import_bundle\n    self.import_relationship(item, update, types)\n  File \"/usr/local/lib/python3.12/site-packages/pycti/utils/opencti_stix2.py\", line 1237, in import_relationship\n    stix_relation_result = self.opencti.stix_core_relationship.import_from_stix2(\n                           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"/usr/local/lib/python3.12/site-packages/pycti/entities/opencti_stix_core_relationship.py\", line 1132, in import_from_stix2\n    return self.create(\n           ^^^^^^^^^^^^\n  File \"/usr/local/lib/python3.12/site-packages/pycti/entities/opencti_stix_core_relationship.py\", line 611, in create\n    result = self.opencti.query(\n             ^^^^^^^^^^^^^^^^^^^\n  File \"/usr/local/lib/python3.12/site-packages/pycti/api/opencti_api_client.py\", line 351, in query\n    raise ValueError(\nValueError: {'name': 'MISSING_REFERENCE_ERROR', 'message': 'Element(s) not found'}\n", "taskName": null}
{"timestamp": "2024-04-17T04:47:36.586576Z", "level": "INFO", "name": "api", "message": "Report expectation", "taskName": null, "attributes": {"work_id": "work_aabadcd1-3359-4113-bcc5-252c4071c527_2024-04-14T22:55:27.557Z"}}
{"timestamp": "2024-04-17T04:47:36.611395Z", "level": "ERROR", "name": "api", "message": "Cannot report expectation", "exc_info": "Traceback (most recent call last):\n  File \"/opt/opencti-worker/worker.py\", line 268, in data_handler\n    self.api.stix2.import_bundle_from_json(\n  File \"/usr/local/lib/python3.12/site-packages/pycti/utils/opencti_stix2.py\", line 215, in import_bundle_from_json\n    return self.import_bundle(\n           ^^^^^^^^^^^^^^^^^^^\n  File \"/usr/local/lib/python3.12/site-packages/pycti/utils/opencti_stix2.py\", line 2373, in import_bundle\n    self.import_relationship(item, update, types)\n  File \"/usr/local/lib/python3.12/site-packages/pycti/utils/opencti_stix2.py\", line 1237, in import_relationship\n    stix_relation_result = self.opencti.stix_core_relationship.import_from_stix2(\n                           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"/usr/local/lib/python3.12/site-packages/pycti/entities/opencti_stix_core_relationship.py\", line 1132, in import_from_stix2\n    return self.create(\n           ^^^^^^^^^^^^\n  File \"/usr/local/lib/python3.12/site-packages/pycti/entities/opencti_stix_core_relationship.py\", line 611, in create\n    result = self.opencti.query(\n             ^^^^^^^^^^^^^^^^^^^\n  File \"/usr/local/lib/python3.12/site-packages/pycti/api/opencti_api_client.py\", line 351, in query\n    raise ValueError(\nValueError: {'name': 'MISSING_REFERENCE_ERROR', 'message': 'Element(s) not found'}\n\nDuring handling of the above exception, another exception occurred:\n\nTraceback (most recent call last):\n  File \"/opt/opencti-worker/worker.py\", line 268, in data_handler\n    self.api.stix2.import_bundle_from_json(\n  File \"/usr/local/lib/python3.12/site-packages/pycti/utils/opencti_stix2.py\", line 215, in import_bundle_from_json\n    return self.import_bundle(\n           ^^^^^^^^^^^^^^^^^^^\n  File \"/usr/local/lib/python3.12/site-packages/pycti/utils/opencti_stix2.py\", line 2373, in import_bundle\n    self.import_relationship(item, update, types)\n  File \"/usr/local/lib/python3.12/site-packages/pycti/utils/opencti_stix2.py\", line 1237, in import_relationship\n    stix_relation_result = self.opencti.stix_core_relationship.import_from_stix2(\n                           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"/usr/local/lib/python3.12/site-packages/pycti/entities/opencti_stix_core_relationship.py\", line 1132, in import_from_stix2\n    return self.create(\n           ^^^^^^^^^^^^\n  File \"/usr/local/lib/python3.12/site-packages/pycti/entities/opencti_stix_core_relationship.py\", line 611, in create\n    result = self.opencti.query(\n             ^^^^^^^^^^^^^^^^^^^\n  File \"/usr/local/lib/python3.12/site-packages/pycti/api/opencti_api_client.py\", line 351, in query\n    raise ValueError(\nValueError: {'name': 'MISSING_REFERENCE_ERROR', 'message': 'Element(s) not found'}\n\nDuring handling of the above exception, another exception occurred:\n\nTraceback (most recent call last):\n  File \"/opt/opencti-worker/worker.py\", line 268, in data_handler\n    self.api.stix2.import_bundle_from_json(\n  File \"/usr/local/lib/python3.12/site-packages/pycti/utils/opencti_stix2.py\", line 215, in import_bundle_from_json\n    return self.import_bundle(\n           ^^^^^^^^^^^^^^^^^^^\n  File \"/usr/local/lib/python3.12/site-packages/pycti/utils/opencti_stix2.py\", line 2373, in import_bundle\n    self.import_relationship(item, update, types)\n  File \"/usr/local/lib/python3.12/site-packages/pycti/utils/opencti_stix2.py\", line 1237, in import_relationship\n    stix_relation_result = self.opencti.stix_core_relationship.import_from_stix2(\n                           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"/usr/local/lib/python3.12/site-packages/pycti/entities/opencti_stix_core_relationship.py\", line 1132, in import_from_stix2\n    return self.create(\n           ^^^^^^^^^^^^\n  File \"/usr/local/lib/python3.12/site-packages/pycti/entities/opencti_stix_core_relationship.py\", line 611, in create\n    result = self.opencti.query(\n             ^^^^^^^^^^^^^^^^^^^\n  File \"/usr/local/lib/python3.12/site-packages/pycti/api/opencti_api_client.py\", line 351, in query\n    raise ValueError(\nValueError: {'name': 'MISSING_REFERENCE_ERROR', 'message': 'Element(s) not found'}\n\nDuring handling of the above exception, another exception occurred:\n\nTraceback (most recent call last):\n  File \"/opt/opencti-worker/worker.py\", line 268, in data_handler\n    self.api.stix2.import_bundle_from_json(\n  File \"/usr/local/lib/python3.12/site-packages/pycti/utils/opencti_stix2.py\", line 215, in import_bundle_from_json\n    return self.import_bundle(\n           ^^^^^^^^^^^^^^^^^^^\n  File \"/usr/local/lib/python3.12/site-packages/pycti/utils/opencti_stix2.py\", line 2373, in import_bundle\n    self.import_relationship(item, update, types)\n  File \"/usr/local/lib/python3.12/site-packages/pycti/utils/opencti_stix2.py\", line 1237, in import_relationship\n    stix_relation_result = self.opencti.stix_core_relationship.import_from_stix2(\n                           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"/usr/local/lib/python3.12/site-packages/pycti/entities/opencti_stix_core_relationship.py\", line 1132, in import_from_stix2\n    return self.create(\n           ^^^^^^^^^^^^\n  File \"/usr/local/lib/python3.12/site-packages/pycti/entities/opencti_stix_core_relationship.py\", line 611, in create\n    result = self.opencti.query(\n             ^^^^^^^^^^^^^^^^^^^\n  File \"/usr/local/lib/python3.12/site-packages/pycti/api/opencti_api_client.py\", line 351, in query\n    raise ValueError(\nValueError: {'name': 'MISSING_REFERENCE_ERROR', 'message': 'Element(s) not found'}\n\nDuring handling of the above exception, another exception occurred:\n\nTraceback (most recent call last):\n  File \"/usr/local/lib/python3.12/site-packages/pycti/api/opencti_api_work.py\", line 56, in report_expectation\n    self.api.query(query, {\"id\": work_id, \"error\": error})\n  File \"/usr/local/lib/python3.12/site-packages/pycti/api/opencti_api_client.py\", line 351, in query\n    raise ValueError(\nValueError: {'name': 'DATABASE_ERROR', 'message': 'Update indexing fail'}", "taskName": null}
{"timestamp": "2024-04-17T04:47:36.645999Z", "level": "INFO", "name": "worker", "message": "Message processed, thread terminated", "taskName": null}
{"timestamp": "2024-04-17T04:47:36.646270Z", "level": "INFO", "name": "worker", "message": "Message acknowledged", "taskName": null, "attributes": {"tag": 90}}
{"timestamp": "2024-04-17T04:47:36.647599Z", "level": "INFO", "name": "worker", "message": "Processing a new message, launching a thread...", "taskName": null, "attributes": {"tag": 91}}
{"timestamp": "2024-04-17T04:47:36.648342Z", "level": "INFO", "name": "api", "message": "Creating stix_core_relationship", "taskName": null, "attributes": {"relationship_type": "indicates", "from_id": "indicator--abcf801d-742a-528e-bdfe-c70d9bfda6f3", "to_id": "attack-pattern--35afd009-4f86-5c29-a246-ccae9eb90a66"}}
{"timestamp": "2024-04-17T04:47:38.249366Z", "level": "INFO", "name": "worker", "message": "Message reprocess", "taskName": null, "attributes": {"tag": 91, "count": 1}}
{"timestamp": "2024-04-17T04:47:38.249828Z", "level": "INFO", "name": "api", "message": "Creating stix_core_relationship", "taskName": null, "attributes": {"relationship_type": "indicates", "from_id": "indicator--abcf801d-742a-528e-bdfe-c70d9bfda6f3", "to_id": "attack-pattern--35afd009-4f86-5c29-a246-ccae9eb90a66"}}
{"timestamp": "2024-04-17T04:47:39.571175Z", "level": "INFO", "name": "worker", "message": "Message reprocess", "taskName": null, "attributes": {"tag": 91, "count": 2}}
{"timestamp": "2024-04-17T04:47:39.571494Z", "level": "INFO", "name": "api", "message": "Creating stix_core_relationship", "taskName": null, "attributes": {"relationship_type": "indicates", "from_id": "indicator--abcf801d-742a-528e-bdfe-c70d9bfda6f3", "to_id": "attack-pattern--35afd009-4f86-5c29-a246-ccae9eb90a66"}}
```

### LINKED ISSUE #6818: [CSV Mapper] MISSING REFERENCE ERROR when importing file with CSV mapper
## Description

I ran the test on two different platforms with exactly **the same file and the same CSV mapper configuration**:
- On one platform, import works
- On the other, I get a “MISSING REFERENCE ERROR”.

Since the CSV does not contain an entity ID, but the platform create all object, I don't understand how we can get a “MISSING REFERENCE ERROR”. What's more, why only on one platform and not the other?

## Environment

OCTI 6.0.10

## Reproducible Steps

- On the "demo" platform, you can find the CSV mapper "Test bug missing ref error" with the configuration.
- The file used for the test is this one : 

[Test.csv](https://github.com/OpenCTI-Platform/opencti/files/15119419/Test.csv)

The demo platform is the that's the one it works on. So that I can show you the second platform on which it doesn't work, please ping me.

nb: 
- I know, it's not a repro case sorry. I've been working on this bug for 2 hours and I've tried everything... I can't get any logic out of this problem
- I also tried to find more data on the error logs but nothing (neither through the browser network nor in the platform logs).

## Screenshots

Screenshot 2024-04-25 204417

### LINKED ISSUE #7020: [backend] Improve alias generation and resolution to improve data ingestion
## Use case

 Improve alias generation and resolution to improve data ingestion.

## Current situation
Aliases ids are generated with a specific algorithm.
Its generated something like alias-UUID
Using this lead to resolution problem when elements are merged and only the alias remains.

## Solution
Aliases ids must be generated as classis standard_id,
This way the resolution will always succeed

### PR DESCRIPTION
**Pull request by richard-julien**
See #7020

### CODE REVIEW

File: opencti-platform/opencti-graphql/src/database/middleware.js [hunk 1]
```diff
@@ -657,10 +658,9 @@ const inputResolveRefs = async (context, user, input, type, entitySetting) => {
         } else if (hasOpenVocab) {
           const ids = isListing ? id : [id];
           const category = getVocabularyCategoryForField(destKey, type);
-          const elements = ids.map((i) => ({ id: generateStandardId(ENTITY_TYPE_VOCABULARY, { name: i, category }), destKey, multiple: isListing }));
-          elements.push(...ids.map((i) => ({ id: idNormalizeDataEntity(i, { category, entity_type: ENTITY_TYPE_VOCABULARY }), destKey, multiple: isListing })));
+          const elements = ids.map((i) => idVocabulary(i, category))
+            .map((lid) => ({ id: lid, destKey, multiple: isListing }));
```
Comment (SouadHadjiat) [inline opencti-platform/opencti-graphql/src/database/middleware.js]: maybe we could do a single map here ? 
```
ids.map((i) => ({ id: idVocabulary(i, category), destKey, multiple: isListing }))
```

File: opencti-platform/opencti-graphql/src/database/middleware.js [hunk 2]
```diff
@@ -1619,7 +1619,7 @@ const updateAttributeRaw = async (context, user, instance, inputs, opts = {}) =>
           }
         }
         // Regenerated the internal ids with the instance target aliases
-        const aliasesId = generateAliasesId(R.uniq([askedModificationName, ...aliases]), instance);
+        const aliasesId = generateAliasesId(aliases, instance);
```
Comment (SouadHadjiat) [inline opencti-platform/opencti-graphql/src/database/middleware.js:1621]: why remove askedModificationName ?

File: opencti-platform/opencti-graphql/src/database/middleware.js [hunk 3]
```diff
@@ -1629,7 +1629,7 @@ const updateAttributeRaw = async (context, user, instance, inputs, opts = {}) =>
           aliasesInput.value = R.uniqBy((e) => normalizeName(e), [...aliasesInput.value, ...(instance[aliasField] || [])]);
         }
         // Internal ids alias must be generated again
-        const aliasesId = generateAliasesId(R.uniq([instance.name, ...aliasesInput.value]), instance);
+        const aliasesId = generateAliasesId(aliasesInput.value, instance);
```
Comment (SouadHadjiat) [inline opencti-platform/opencti-graphql/src/database/middleware.js:1631]: why remove instance.name ?

File: opencti-platform/opencti-graphql/src/migrations/1716392968110-alias_migration.js [hunk 4]
```diff
@@ -0,0 +1,41 @@
...
+      return [
+        { update: { _index: entity._index, _id: entity.id } },
+        { doc: { [iAliasedIds.name]: aliasIds } },
+      ];
+    }).flat();
+    await elBulk({ refresh: true, timeout: BULK_TIMEOUT, body: bulkOperations });
+    logApp.info(`${message} > progress, ${totalIndex}/${total}`);
+  };
+
+  await elList(context, SYSTEM_USER, READ_DATA_INDICES, { filters, noFiltersChecking: true, callback });
```
Comment (SouadHadjiat) [inline opencti-platform/opencti-graphql/src/migrations/1716392968110-alias_migration.js]: can't we filter on indices and/or entity types to only query objects that can have aliases ? to not have to query all indices ?

File: opencti-platform/opencti-graphql/src/database/middleware.js (hunk 2 above)
Comment (richard-julien) [reply opencti-platform/opencti-graphql/src/database/middleware.js:1621]: As alias are now normal id, it will be a duplicate between standard_id and the alias_id generated

File: opencti-platform/opencti-graphql/src/database/middleware.js (hunk 3 above)
Comment (richard-julien) [reply opencti-platform/opencti-graphql/src/database/middleware.js:1631]: As alias are now normal id, it will be a duplicate between standard_id and the alias_id generated

File: opencti-platform/opencti-graphql/src/migrations/1716392968110-alias_migration.js (hunk 4 above)
Comment (richard-julien) [reply opencti-platform/opencti-graphql/src/migrations/1716392968110-alias_migration.js]: Good remark, i will take a look

**Review by aHenryJard — APPROVED** [review]
Tested locally with CSV import, all good for me.
