### PR TITLE
[backend/frontend] Fix Kill all session button in the user overview (#7837)

### LINKED ISSUE #7837: Kill "all" session button is not working anymore in the user overview
## Description

Kill "all" session button is not working anymore in the user overview

1. Go to a user with multiple sessions
2. Click on "Kill all sessions"

=> Nothing happens.

### PR DESCRIPTION
**Pull request by CelineSebe**
### Proposed changes

* remove :sess of sessionId in killUserSessions()
* refetch user after kill sessions

### Related issues

* #7837 

### Checklist

- [x] I consider the submitted work as finished
- [x] I tested the code for its functionality
- [ ] I wrote test cases for the relevant uses case (coverage and e2e)
- [ ] I added/update the relevant documentation (either on github or on notion)
- [ ] Where necessary I refactored code to improve the overall quality

### CODE REVIEW

File: opencti-platform/opencti-front/src/private/components/settings/users/User.tsx [hunk 1]
```diff
@@ -35,7 +35,7 @@ import Transition from '../../../../components/Transition';
 import { User_user$key } from './__generated__/User_user.graphql';
 import Chart from '../../common/charts/Chart';
 import { UserSessionKillMutation } from './__generated__/UserSessionKillMutation.graphql';
-import { UserUserSessionsKillMutation } from './__generated__/UserUserSessionsKillMutation.graphql';
+import { UserSessionsKillMutation } from './__generated__/UserUserSessionsKillMutation.graphql';
```
Comment (SouadHadjiat) [inline opencti-platform/opencti-front/src/private/components/settings/users/User.tsx]: build is on error : 

`src/private/components/settings/users/User.tsx(38,42): error TS2307: Cannot find module './__generated__/UserUserSessionsKillMutation.graphql' or its corresponding type declarations.`

**Review by SouadHadjiat — COMMENTED** [review]
Sessions are indeed killed but the frontend is not refreshed, same issue with one session kill. I had to refresh the user to see the sessions disapear. Could we refresh the sessions ?

**Review by aHenryJard — APPROVED** [review]
