### PR TITLE
[frontend] Bug fix for the overflowing User Session area

### LINKED ISSUE #10890: Having many sessions in User session history is not handled in the UI
The user session history is not a scrollable area.
It keeps expanding forever and UI gets messy.

We need to make it scrollable.

### PR DESCRIPTION
**Pull request by daimyo007**
Ticket: [1085](https://jira.324cate.com/browse/TIM-1085)

Decompose - https://github.com/OpenCTI-Platform/opencti/pull/10763
Part #1 - modify https://github.com/OpenCTI-Platform/opencti/pull/10763 to just contain the bug fix/scroll are for the User Session Widget area.
 
The capability is currently managed in master-TIM and needs to be merged into Open Source Github version.

### CODE REVIEW

File: opencti-platform/opencti-front/src/private/components/settings/users/User.tsx [hunk 1]
```diff
@@ -670,7 +670,7 @@ const User: FunctionComponent<UserProps> = ({ data, refetch }) => {
         </Grid>
         <Triggers recipientId={user.id} filterKey="authorized_members.id" />
         <Grid item xs={6} style={{ marginTop: 10 }}>
-          <Typography variant="h4" gutterBottom={true}>
+          <Typography variant="h4" gutterBottom={true} style={{ paddingBottom: '22px' }}>
```
Comment (labo-flg) [inline opencti-platform/opencti-front/src/private/components/settings/users/User.tsx]: Looking closely, 21px seems the right value :)

```suggestion
          <Typography variant="h4" gutterBottom={true} style={{ paddingBottom: '21px' }}>
```

**Review by labo-flg — CHANGES_REQUESTED** [review]
A very small change to have the right alignment, and we're good to merge for me.

**Review by labo-flg — APPROVED** [review]

**Comment by labo-flg** [comment]
@daimyo007 you have unverified commits. Could you sign your commits please ?

**Review by labo-flg — APPROVED** [review]
