### PR TITLE
[backend] Bulk deleted external reference is not working when using a filter(#7210)

### LINKED ISSUE #7210: Cannot bulk delete External References when using a filter
## Description

There appears to be a bug with bulk deleting external references when using a filter, the task displays "Targeted entities (0)", even though 100+ are marked.
However, bulk deleting when not using a filter works as expected.

## Environment

1. OS: Ubuntu 22.04 LTS
2. OpenCTI version: 6.1.8
3. OpenCTI client: Frontend/Web
4. Other environment details:

## Reproducible Steps

Steps to create the smallest reproducible scenario:
1. Open the External References view
2. Apply a filter
3. Run a bulk deletion of all entities shown by filter by clicking the top checkbox
4. Look in tasks, it should display "Targeted entities (0)"

## Expected Output

The entities should be deleted

## Actual Output

The entities are not deleted

## Additional information

N/A

## Screenshots (optional)

N/A

### PR DESCRIPTION
**Pull request by aHenryJard**
### Proposed changes

* Add external reference as allowed entity for background tasks.

### Related issues

* https://github.com/OpenCTI-Platform/opencti/issues/7210

### Checklist

- [x] I consider the submitted work as finished
- [x] I tested the code for its functionality
- [x] I wrote test cases for the relevant uses case (coverage and e2e)
- [x] I added/update the relevant documentation (either on github or on notion)
- [x] Where necessary I refactored code to improve the overall quality

### CODE REVIEW

File: opencti-platform/opencti-graphql/src/manager/taskManager.js [hunk 1]
```diff
@@ -98,7 +98,9 @@ const findTaskToExecute = async (context) => {
     },
     noFiltersChecking: true
   });
+  logApp.info('tasks found:', { tasks });
```
Comment (aHenryJard) [inline opencti-platform/opencti-graphql/src/manager/taskManager.js]:
```suggestion
```

File: opencti-platform/opencti-graphql/src/domain/backgroundTask.js [hunk 2]
```diff
@@ -87,6 +88,7 @@ export const createQueryTask = async (context, user, input) => {
   const { actions, filters, excluded_ids = [], search = null, scope } = input;
   await checkActionValidity(context, user, input, scope, TASK_TYPE_QUERY);
   const queryData = await executeTaskQuery(context, user, filters, search);
+
```
Comment (aHenryJard) [inline opencti-platform/opencti-graphql/src/domain/backgroundTask.js]:
```suggestion
```

File: opencti-platform/opencti-graphql/src/manager/taskManager.js [hunk 3]
```diff
@@ -98,7 +98,9 @@ const findTaskToExecute = async (context) => {
...
   if (tasks.length === 0) {
+    logApp.info('No tasks found:');
```
Comment (aHenryJard) [inline opencti-platform/opencti-graphql/src/manager/taskManager.js]:
```suggestion
```

File: opencti-platform/opencti-graphql/src/manager/taskManager.js [hunk 4]
```diff
@@ -479,6 +481,7 @@ const taskHandler = async () => {
     const isQueryTask = task.type === TASK_TYPE_QUERY;
     const isListTask = task.type === TASK_TYPE_LIST;
     const isRuleTask = task.type === TASK_TYPE_RULE;
+
```
Comment (aHenryJard) [inline opencti-platform/opencti-graphql/src/manager/taskManager.js]:
```suggestion
```

File: opencti-platform/opencti-graphql/src/manager/taskManager.js [hunk 5]
```diff
@@ -501,6 +504,7 @@ const taskHandler = async () => {
     }
     // Process the elements (empty = end of execution)
     const processingElements = jobToExecute.elements;
+    logApp.info(`Element count:${processingElements.length}`);
```
Comment (aHenryJard) [inline opencti-platform/opencti-graphql/src/manager/taskManager.js]:
```suggestion
```

**Review by Archidoit — APPROVED** [review]
