### PR TITLE
[backend] Add log on intialization to better understand failures (#7038)

### LINKED ISSUE #7038: Upgrade Failure to 6.1.2 | Engine Unhandled Rejection
## Description

I upgraded from 6.0.7 to 6.1.2. After updating OpenCTI never launched. Tried to isolate troubleshooting this with just Elasticsearch, Redis, RabbitMQ, Minio, and main OpenCTI app running. The OpenCTI logs look to point to a few things "System dependencies check failed", "Search engine seems down", and "Engine unhandled rejection". I am unable to revert back to any older version of OpenCTI when attempting to.

I am able to wget http://elasticsearch:9200/_cluster/health and see the health status so it looks like OpenCTI should be able to connect to elasticsearch still and from Elasticsearch logs it looks to be running still.
```
{"cluster_name":"docker-cluster","status":"yellow","timed_out":false,"number_of_nodes":1,"number_of_data_nodes":1,"active_primary_shards":20,"active_shards":20,"relocating_shards":0,"initializing_shards":0,"unassigned_shards":14,"delayed_unassigned_shards":0,"number_of_pending_tasks":0,"number_of_in_flight_fetch":0,"task_max_waiting_in_queue_millis":0,"active_shards_percent_as_number":58.82352941176471
```

## Environment

1. OS (where OpenCTI server runs): Docker
2. OpenCTI version: 6.1.2
3. OpenCTI client: NA
4. Other environment details: NA

## Reproducible Steps

Steps to create the smallest reproducible scenario:
1. Run 6.0.7
2. Upgrade to 6.1.2

## Expected Output

OpenCTI to boot successfully.

## Actual Output
[opencti-opencti-1_logs.txt](https://github.com/OpenCTI-Platform/opencti/files/15381818/opencti-opencti-1_logs.txt)
[opencti-elasticsearch-1_logs.txt](https://github.com/OpenCTI-Platform/opencti/files/15381822/opencti-elasticsearch-1_logs.txt)

## Additional information
Docker compose of the main services.

```
version: '3'
services:
  redis:
    image: redis:7.2.4
    restart: always
    volumes:
      - redisdata:/data
  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:8.13.4
    volumes:
      - esdata:/usr/share/elasticsearch/data
    environment:
      # Comment out the line below for single-node
      - discovery.type=single-node
      # Uncomment line below below for a cluster of multiple nodes
      # - cluster.name=docker-cluster
      - xpack.ml.enabled=false
      - xpack.security.enabled=false
      - thread_pool.search.queue_size=10000  # add queue_size (default 1000)
      - thread_pool.search.size=30  # add size (default 13)
      - logger.org.elasticsearch.discovery="ERROR"
      - "ES_JAVA_OPTS=-Xms${ELASTIC_MEMORY_SIZE} -Xmx${ELASTIC_MEMORY_SIZE}"
    restart: always
    ulimits:
      memlock:
        soft: -1
        hard: -1
      nofile:
        soft: 65536
        hard: 65536
  minio:
    image: minio/minio:RELEASE.2024-01-16T16-07-38Z
    volumes:
      - s3data:/data
    ports:
      - "9000:9000"
    environment:
      MINIO_ROOT_USER: ${MINIO_ROOT_USER}
      MINIO_ROOT_PASSWORD: ${MINIO_ROOT_PASSWORD}    
    command: server /data
    restart: always
  rabbitmq:
    image: rabbitmq:3.13-management
    environment:
      - RABBITMQ_DEFAULT_USER=${RABBITMQ_DEFAULT_USER}
      - RABBITMQ_DEFAULT_PASS=${RABBITMQ_DEFAULT_PASS}
      - RABBITMQ_NODENAME=rabbit01@localhost
    volumes:
      - amqpdata:/var/lib/rabbitmq
    restart: always
  opencti:
    image: opencti/platform:6.1.2
    environment:
      - NODE_OPTIONS=--max-old-space-size=8096
      - APP__PORT=8080
      - APP__BASE_URL=${OPENCTI_BASE_URL}
      - APP__ADMIN__EMAIL=${OPENCTI_ADMIN_EMAIL}
      - APP__ADMIN__PASSWORD=${OPENCTI_ADMIN_PASSWORD}
      - APP__ADMIN__TOKEN=${OPENCTI_ADMIN_TOKEN}
      - APP__APP_LOGS__LOGS_LEVEL=error
      - APP__SESSION_TIMEOUT=28800000
      - APP__SESSION_IDLE_TIMEOUT=3600000
      - REDIS__HOSTNAME=redis
      - REDIS__PORT=6379
      - REDIS__TRIMMING=500000
      - ELASTICSEARCH__URL=http://elasticsearch:9200
      - MINIO__ENDPOINT=minio
      - MINIO__PORT=9000
      - MINIO__USE_SSL=false
      - MINIO__ACCESS_KEY=${MINIO_ROOT_USER}
      - MINIO__SECRET_KEY=${MINIO_ROOT_PASSWORD}
      - RABBITMQ__HOSTNAME=rabbitmq
      - RABBITMQ__PORT=5672
      - RABBITMQ__PORT_MANAGEMENT=15672
      - RABBITMQ__MANAGEMENT_SSL=false
      - RABBITMQ__USERNAME=${RABBITMQ_DEFAULT_USER}
      - RABBITMQ__PASSWORD=${RABBITMQ_DEFAULT_PASS}
      - SMTP__HOSTNAME=${SMTP_HOSTNAME}
      - SMTP__PORT=25
      - PROVIDERS__LOCAL__STRATEGY=LocalStrategy
    ports:
      - "443:8080"
    depends_on:
      - redis
      - elasticsearch
      - minio
      - rabbitmq
    restart: always
```

### PR DESCRIPTION
**Pull request by aHenryJard**
### Proposed changes

* When the SSL part of opencti is badly configured, add an explicit error message instead of just "Engine Unhandled Rejection".
* Add log before checks to know what is about to be checked at initialization.

Before change when SSL is badly configured:
```
{"category":"APP","level":"info","message":"[INIT] Platform initialization done","source":"backend","timestamp":"2024-07-16T07:28:17.695Z","version":"6.2.4"}
{"category":"APP","errors":[{"attributes":{"genre":"TECHNICAL","http_status":500,"promise":{},"reason":{"code":"ENOENT","errno":-4058,"path":"C:\\Users\\AngeliqueJard\\IdeaProjects\\test-cert\\openct.local.key","syscall":"open"}},"message":"Engine unhandled rejection","name":"UNKNOWN_ERROR","stack":"UNKNOWN
_ERROR: Engine unhandled rejection\n    at error (C:\\Users\\AngeliqueJard\\IdeaProjects\\opencti\\opencti-platform\\opencti-graphql\\src\\config\\errors.js:8:10)\n    at UnknownError (C:\\Users\\AngeliqueJard\\IdeaProjects\\opencti\\opencti-platform\\opencti-graphql\\src\\config\\errors.js:82:47)\n    at p
rocess.<anonymous> (C:\\Users\\AngeliqueJard\\IdeaProjects\\opencti\\opencti-platform\\opencti-graphql\\src\\boot.js:60:16)\n    at process.emit (node:events:519:28)\n    at process.emit (C:\\Users\\AngeliqueJard\\IdeaProjects\\opencti\\opencti-platform\\opencti-graphql\\node_modules\\source-map-support\\so
urce-map-support.js:516:21)\n    at emit (node:internal/process/promises:150:20)\n    at processPromiseRejections (node:internal/process/promises:284:27)\n    at processTicksAndRejections (node:internal/process/task_queues:96:32)"}],"level":"error","message":"Engine unhandled rejection","source":"backend","timestamp":"2024-07-16T07:28:18.283Z","version":"6.2.4"}
```
After change when SSL is badly configured:
```
{"category":"APP","level":"info","message":"[INIT] Platform initialization done","source":"backend","timestamp":"2024-07-16T07:28:17.695Z","version":"6.2.4"}
{"category":"APP","level":"info","message":"[INIT] Configuring HTTP/HTTPS server","source":"backend","timestamp":"2024-07-16T07:25:13.555Z","version":"6.2.4"}
{"category":"APP","level":"info","message":"[INIT] Configuring SSL for HTTPS server.","source":"backend","timestamp":"2024-07-16T07:25:14.090Z","version":"6.2.4"}
{"category":"APP","code":"ENOENT","errno":-4058,"level":"error","message":"[INIT] HTTPS server cannot start, please verify app.https_cert and other configurations","path":"C:\\Users\\AngeliqueJard\\IdeaProjects\\test-cert\\openct.local.key","source":"backend","syscall":"open","timestamp":"2024-07-16T07:25:14.091Z","version":"6.2.4"}
{"category":"APP","errors":[{"attributes":{"genre":"TECHNICAL","http_status":500,"promise":{},"reason":{}},"message":"Engine unhandled rejection","name":"UNKNOWN_ERROR","stack":"UNKNOWN_ERROR: Engine unhandled rejection\n    at error (C:\\Users\\AngeliqueJard\\IdeaProjects\\opencti\\opencti-platform\\openct
i-graphql\\src\\config\\errors.js:8:10)\n    at UnknownError (C:\\Users\\AngeliqueJard\\IdeaProjects\\opencti\\opencti-platform\\opencti-graphql\\src\\config\\errors.js:82:47)\n    at process.<anonymous> (C:\\Users\\AngeliqueJard\\IdeaProjects\\opencti\\opencti-platform\\opencti-graphql\\src\\boot.js:60:16)
\n    at process.emit (node:events:519:28)\n    at process.emit (C:\\Users\\AngeliqueJard\\IdeaProjects\\opencti\\opencti-platform\\opencti-graphql\\node_modules\\source-map-support\\source-map-support.js:516:21)\n    at emit (node:internal/process/promises:150:20)\n    at processPromiseRejections (node:internal/process/promises:284:27)\n    at processTicksAndRejections (node:internal/process/task_queues:96:32)"}],"level":"error","message":"Engine unhandled rejection","source":"backend","timestamp":"2024-07-16T07:25:14.093Z","version":"6.2.4"}
```

### Related issues

* closes #7038 

### Checklist

- [x] I consider the submitted work as finished
- [x] I tested the code for its functionality
- [ ] I wrote test cases for the relevant uses case (coverage and e2e)
- [ ] I added/update the relevant documentation (either on github or on notion)
- [ ] Where necessary I refactored code to improve the overall quality

### CODE REVIEW

File: opencti-platform/opencti-graphql/src/config/conf.js [hunk 1]
```diff
@@ -298,6 +298,7 @@ export const getBaseUrl = (req) => {
 };
 
 export const configureCA = (certificates) => {
+  logApp.info('Configure CA');
```
Comment (aHenryJard) [inline opencti-platform/opencti-graphql/src/config/conf.js]:
```suggestion
```

**Review by lndrtrbn — APPROVED** [review]
