### PR TITLE
[frontend] Fix Text Overflowing Paper in LINKED OBJECTS

### LINKED ISSUE #4778: Text Overflowing Paper in LINKED OBJECTS
## Description

Text is overflowing the Paper element in LINKED OBJECTS section:

image

### PR DESCRIPTION
**Pull request by helene-nguyen**
### Proposed changes

*  Add props to avoid text overflowing 

### Related issues

* https://github.com/OpenCTI-Platform/opencti/issues/4778

### Checklist

- [x] I consider the submitted work as finished
- [x] I tested the code for its functionality
- [ ] I wrote test cases for the relevant uses case
- [ ] I added/update the relevant documentation (either on github or on notion)
- [x] Where necessary I refactored code to improve the overall quality

### Further comments

If this is a relatively large or complex change, kick off the discussion by explaining why you chose the solution you did and what alternatives you considered, etc...

### CODE REVIEW

File: opencti-platform/opencti-front/src/private/components/analyses/external_references/ExternalReferenceStixCoreObjects.jsx [hunk 1]
```diff
@@ -52,6 +52,7 @@ const ExternalReferenceStixCoreObjectsComponent = ({ externalReference }) => {
               </ListItemIcon>
               <ListItemText
                 primary={stixCoreObjectOrRelationship?.representative?.main}
+                primaryTypographyProps={{ style: { overflow: 'hidden', textOverflow: 'ellipsis' } }}
```
Comment (lndrtrbn) [inline opencti-platform/opencti-front/src/private/components/analyses/external_references/ExternalReferenceStixCoreObjects.jsx]:
```suggestion
                primaryTypographyProps={{ style: { wordWrap: 'break-word' } }}
```

Why this suggestion ? With `textOverflow: 'ellipsis'` we truncate the text and by so lose information. Using `wordWrap: 'break-word'` force the text to wrap to new line even if it is a very long word.

**Review by lndrtrbn — CHANGES_REQUESTED** [review]

File: opencti-platform/opencti-front/src/private/components/analyses/external_references/ExternalReferenceStixCoreObjects.jsx (hunk 1 above)
Comment (helene-nguyen) [reply opencti-platform/opencti-front/src/private/components/analyses/external_references/ExternalReferenceStixCoreObjects.jsx]: Done, thanks for the suggestion :)

**Review by lndrtrbn — APPROVED** [review]
