### PR TITLE
[frontend] Fix workbench SDO deduplication (#6797)

### LINKED ISSUE #6797: Entities disappearing when editing container on workbench
## Description

When, inside an analyst workbench, I edit a report, some entities get deleted from the report.

## Environment

Testing

## Reproducible Steps

Steps to create the smallest reproducible scenario:
1. Import the following STIX bundle in the platform: [sample_issue.json](https://github.com/OpenCTI-Platform/opencti/files/15082601/sample_issue.json)
2. Edit the generated workbench
3. Go to the Containers section
4. Click on the report to edit it and then click on **Update and Complete** to edit its contained entities.

## Expected Output

See the two included indicators

## Actual Output

One of the two indicators got deleted from the workbench. Before editing the report, there was two indicators in Entities section

## Screenshots (optional)
issue_import_contained_indicators

### PR DESCRIPTION
**Pull request by SouadHadjiat**
### Proposed changes

* fix stix domain objects update deduplication : adding missing fields (pattern for indicators).

### Related issues
Issue was happening with indicators because we were deduplicating them based only on name (and we didn't have a name, so the two entities were considered the same).

* #6797 

### Checklist

- [x] I consider the submitted work as finished
- [x] I tested the code for its functionality
- [ ] I wrote test cases for the relevant uses case (coverage and e2e)
- [ ] I added/update the relevant documentation (either on github or on notion)
- [x] Where necessary I refactored code to improve the overall quality

### CODE REVIEW

File: opencti-platform/opencti-front/src/private/components/common/files/workbench/WorkbenchFileContent.jsx [hunk 1]
```diff
@@ -243,6 +243,8 @@ const importValidation = (t) => Yup.object().shape({
   connector_id: Yup.string().trim().required(t('This field is required')),
 });
 
+const uniqStixDomainObjectsFields = ['name', 'type', 'pattern', 'identity_class', 'x_opencti_location_type'];
```
Comment (SarahBocognano) [inline opencti-platform/opencti-front/src/private/components/common/files/workbench/WorkbenchFileContent.jsx:246]: If I understand well, you added the "pattern" field for indicator. Does "identity_class" & "x_opencti_location_type" are the only other field types possible in the platform ? (with name & type of course)

**Review by SarahBocognano — APPROVED** [review]

File: opencti-platform/opencti-front/src/private/components/common/files/workbench/WorkbenchFileContent.jsx (hunk 1 above)
Comment (SouadHadjiat) [reply opencti-platform/opencti-front/src/private/components/common/files/workbench/WorkbenchFileContent.jsx:246]: I'm not sure if there are other types, I only gathered the ones I found in the code, they were already used, and I added pattern for indicators.
