### PR TITLE
[frontend] Fix the positions when adding an entity in all the Knowlege graph view (#7298)

### LINKED ISSUE #7298: In knowledge graph, do not re-apply forces when adding a new entity (working already when adding a new relations)
## Use case

In knowledge graph, do not re-apply forces when adding a new entity (working already when adding a new relations).

Very frustrating current behaviour:

1. Add dozens of entities
2. Take 10 min to properly position all the nodes and having a very beautiful graphs with manual positionning. 
3. Add 1 new entities

=> Everything you have done is lost....

### PR DESCRIPTION
**Pull request by Gwendoline-FAVRE-FELIX**
### Proposed changes

When you place entities manually and then add a new entity. If the forces are deactivated, make sure that the entities stay in the place they were given

### Related issues

* #7298 
*

### Checklist

- [ ] I consider the submitted work as finished
- [ ] I tested the code for its functionality
- [ ] I wrote test cases for the relevant uses case (coverage and e2e)
- [ ] I added/update the relevant documentation (either on github or on notion)
- [ ] Where necessary I refactored code to improve the overall quality

### CODE REVIEW

File: opencti-platform/opencti-front/src/private/components/workspaces/investigations/InvestigationGraph.jsx [hunk 1]
```diff
@@ -1429,7 +1440,7 @@ class InvestigationGraphComponent extends Component {
     this.graphObjects = [...this.graphObjects, stixCoreObject];
     this.graphData = buildGraphData(
       this.graphObjects,
-      decodeGraphData(this.props.workspace.graph_data),
+      decodeGraphData(this.props.workspace.x_opencti_graph_data),
```
Comment (SouadHadjiat) [inline opencti-platform/opencti-front/src/private/components/workspaces/investigations/InvestigationGraph.jsx]: should be `graph_data`, not `x_opencti_graph_data`

**Review by SouadHadjiat — APPROVED** [review]
Pair reviewed with @Gwendoline-FAVRE-FELIX, positions were already all saved (but with null values), now we save them all with the right values, so looks good to me.
