### PR TITLE
[frontend] fix dashboard export to pdf fails when containing donuts (#10786)

### LINKED ISSUE #10786: Exporting dashboard in PDF is broken
## Description

Go to https://testing.octi.staging.filigran.io/dashboard/workspaces/dashboards/a3addcfd-a0ce-4ea1-afbd-4b35f0f38d28

Try to export in PDF

### PR DESCRIPTION
**Pull request by aHenryJard**
### Proposed changes

* Mitigate issue by downgrade apexchart to `4.4.0`

* Have better error management in case of error: close the loader and show an error message instead of waiting for ever.
* Add end to end tests on dashboard export to pdf
* Handle fetch issue on external images in text widget

### Related issues

* closes #10786 

### Checklist

- [x] I consider the submitted work as finished
- [x] I tested the code for its functionality
- [x] I wrote test cases for the relevant uses case (coverage and e2e)
- [ ] I added/update the relevant documentation (either on github or on notion)
- [x] Where necessary I refactored code to improve the overall quality

### CODE REVIEW

File: opencti-platform/opencti-front/src/components/ExportButtons.jsx [hunk 1]
```diff
@@ -104,6 +104,7 @@ class ExportButtons extends Component {
   }
 
   handleOpenPdf(event) {
+    console.log('ANGIE - handleOpenPdf');
```
Comment (aHenryJard) [inline opencti-platform/opencti-front/src/components/ExportButtons.jsx]:
```suggestion
```

File: opencti-platform/opencti-front/src/utils/Image.js [hunk 2]
```diff
@@ -7,6 +7,8 @@ const ignoredClasses = [
   'MuiDrawer-docked',
   'MuiIconButton-root',
   'MuiInputBase-root',
+  // For some reason apex legend crash pdf and png export.
+  // 'apexcharts-legend-series',
```
Comment (aHenryJard) [inline opencti-platform/opencti-front/src/utils/Image.js]:
```suggestion
```

**Review by lndrtrbn — APPROVED** [review]
