### PR TITLE
[backend] fix unresolved elements in upsert (#10856)

### LINKED ISSUE #10856: In some cases, we have multiple values in "author" (rel_created-by.internal_id)
## Description

In some cases, we have multiple values in "author" (rel_created-by.internal_id).

To determine how this can happen, but consequences are the fact that updating the author is not possible in the UI, also inconsistency in history at upsert etc.

```
POST opencti_*/_search
{
  "query": {
    "script": {
      "script": {
        "source": "doc['rel_created-by.internal_id.keyword'].length > 1",
        "lang": "painless"
      }
    }
  },
  "track_total_hits": true
}
```

Results:

* 206 in filigran instance
* 108 in se2 instance
* 323 in testing

### PR DESCRIPTION
**Pull request by JeremyCloarec**
### Proposed changes

* some upsertElement call were done with elements without their refs resolved. This could cause` multiple: false` refs to not be deleted when upserting the ref.
The ref resolving is now done in upsertElement if needed
* add a migration to only keep one author per entity with multiple authors

### Related issues

* #10856 
*

### Checklist

- [x] I consider the submitted work as finished
- [x] I tested the code for its functionality
- [ ] I wrote test cases for the relevant uses case (coverage and e2e)
- [ ] I added/update the relevant documentation (either on github or on notion)
- [ ] Where necessary I refactored code to improve the overall quality

### CODE REVIEW

File: opencti-platform/opencti-graphql/src/migrations/1742823297617-remove_multiple_authors.js [hunk 1]
```diff
@@ -0,0 +1,119 @@
...
+        params: { authorIdToKeep },
+        lang: 'painless'
+      },
+      query: {
+        match: {
+          _id: currentEntityWithMultipleAuthors._id
+        }
+      }
+    };
+    await elRawUpdateByQuery({
```
Comment (SouadHadjiat) [inline opencti-platform/opencti-graphql/src/migrations/1742823297617-remove_multiple_authors.js]: use elUpdate directly

**Review by SouadHadjiat — APPROVED** [review]
