### PR TITLE
[frontend] Fix marking definition updater (#9049)

### LINKED ISSUE #9049: Deleting a marking definition never close the confirmation popup
## Description

Deleting a marking definition never close the confirmation popup

## Reproducible Steps

1. Go to Settings => Security => Marking definitions
2. Create a new marking
3. Try to delete it

=> The delete confirmation never closes

### PR DESCRIPTION
**Pull request by Archidoit**
### Proposed changes
- Close pop up after deleting a marking definition
- fix marking definition updater

### Related issues
https://github.com/OpenCTI-Platform/opencti/issues/9049

### CODE REVIEW

File: opencti-platform/opencti-front/src/private/components/settings/marking_definitions/MarkingDefinitionLine.tsx [hunk 1]
```diff
@@ -40,23 +40,38 @@ const useStyles = makeStyles < Theme >((theme) => ({
...
+const markingDefinitionFragment = graphql`
+    fragment MarkingDefinitionLine_node on MarkingDefinition {
+        id
+        standard_id
+        definition_type
+        definition
+        x_opencti_order
+        x_opencti_color
+        created
+        modified
```
Comment (marieflorescontact) [inline opencti-platform/opencti-front/src/private/components/settings/marking_definitions/MarkingDefinitionLine.tsx:56]: `modified` seems to be unused

**Review by marieflorescontact — COMMENTED** [review]
locally tested ok 👌

**Review by JeremyCloarec — APPROVED** [review]
