### PR TITLE
[frontend] Fix MoreVert icon size in dataTable (#9783)

### LINKED ISSUE #9783: Padding right on data table is too low
## Description

We should increase a little the padding right on data table to avoid this effect:

Image

Image

Image

### PR DESCRIPTION
**Pull request by CelineSebe**
### Proposed changes

* size and style changes

### Related issues

* #9783 

### Checklist

- [x] I consider the submitted work as finished
- [x] I tested the code for its functionality
- [ ] I wrote test cases for the relevant uses case (coverage and e2e)
- [ ] I added/update the relevant documentation (either on github or on notion)
- [ ] Where necessary I refactored code to improve the overall quality

### CODE REVIEW

File: opencti-platform/opencti-front/src/private/components/settings/activity/alerting/AlertingPopover.tsx [hunk 1]
```diff
@@ -81,15 +81,14 @@ const AlertingPopover = ({ data, paginationOptions }: { data: AlertingLine_node$
   };
   // Loader
   return (
-    <div className={classes.container}>
+    <div style={{ marginLeft: -10 }}>
```
Comment (frapuks) [inline opencti-platform/opencti-front/src/private/components/settings/activity/alerting/AlertingPopover.tsx]: Don't we have a better solution than a negative margin?

Comment (CelineSebe) [reply opencti-platform/opencti-front/src/private/components/settings/activity/alerting/AlertingPopover.tsx]: done

**Review by aHenryJard — COMMENTED** [review]
Looks good on entity screen and marking screen but I still have the issue on the automation (playbook) screen with the 3 dot.
image

**Comment by Archidoit** [comment]
Working well on every screen :)

**Review by Archidoit — APPROVED** [review]
